<?php
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    $this->_userInfo = new \ZendX\System\UserInfo();
    $curent_user_id = $this->_userInfo->getUserInfo('id');
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );

    $requirePassword = true;
    $showEncodePhone = 'hidden';
    if(!empty($myForm->get('id')->getValue())) {
        $requirePassword = false;
        if($curent_user_id == '1111111111111111111111' || $curent_user_id == '2222222222222222222222'){
            $showEncodePhone = '';
        }
    }
    
    // Set lại các giá trị của từng element
    $myForm->get('sale_group_id')->setAttributes(array('data-parent' => $myForm->get('sale_branch_id')->getValue()));
    $myForm->get('branch_sale_group_id')->setAttributes(array('data-parent' => $myForm->get('sale_branch_id')->getValue()));

    $elements = array(
        array('section' => 'Tài khoản', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('name'), 'label' => 'Họ và tên', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('username'), 'label' => 'Tên đăng nhập', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('code'), 'label' => 'Mã nhân viên', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('password'), 'label' => 'Mật khẩu', 'validate' => array('require' => $requirePassword), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('password_status'), 'label' => 'Đổi mật khẩu mới', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('email'), 'label' => 'Email', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('phone'), 'label' => 'Điện thoại', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('status'), 'label' => 'Hiển thị', 'boxClass' => 'col-md-3'),
//        array('element' => $myForm->get('notifi'), 'label' => 'Nhận thông báo đơn hàng bán sai', 'boxClass' => 'col-md-3'),
//        array('element' => $myForm->get('kov_branch_id'), 'label' => 'Kho hàng Kiotviet', 'boxClass' => 'col-md-3'),

        array('section' => 'Công việc', 'boxClass' => 'col-md-12'),
        // array('element' => $myForm->get('company_branch_id'), 'label' => 'Cơ sở làm việc', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('sale_branch_id'), 'label' => 'Cơ sở', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('company_department_id'), 'label' => 'Phòng ban', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('company_position_id'), 'label' => 'Vị trí/Chức vụ', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('sale_group_id'), 'label' => 'Thuộc đội nhóm', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('branch_sale_group_id'), 'label' => 'Xem báo cáo nhóm sales', 'boxClass' => 'col-md-3 branch_sale_group_id'),
//        array('element' => $myForm->get('company_position_care_id'), 'label' => 'Chức vụ kiêm nhiệm', 'boxClass' => 'col-md-12'),

        // array('section' => 'Kinh doanh', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('sale_group_hidden'), 'label' => '', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );

    // nếu hành động là tạo
//    if($requirePassword){
//        $elements[] = array('element' => $myForm->get('encode_phone'), 'label' => 'Mã hóa số điện thoại khách hàng của', 'boxClass' => 'col-md-12 '.$showEncodePhone);
//    }
//    else{ // hành động sửa
//        if($curent_user_id == '1111111111111111111111' || $curent_user_id == '2222222222222222222222'){
//            $elements[] = array('element' => $myForm->get('encode_phone'), 'label' => 'Mã hóa số điện thoại khách hàng của', 'boxClass' => 'col-md-12 '.$showEncodePhone);
//        }
//    }

    $elements_permission = array(
        array('section' => 'Quyền truy cập hệ thống', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('permission_ids'), 'label' => 'Nhóm quyền', 'boxClass' => 'col-md-12', 'validate' => array('require' => true)),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
    $xhtml_permission = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements_permission);
?>

<form method="post" action="" class="horizontal-form form-tab" role="form" name="adminForm" id="adminForm">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
    <?php echo @$this->xViewElementErrors($elements_permission);?>
    <div class="page-content">
    	<div class="row">
            <div class="col-md-8">
                <?php echo $xhtml;?>
            </div> 
            <div class="col-md-4">
                <?php echo $xhtml_permission;?>
            </div>
		</div>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
<!--    function loadSaleGroup() {-->
<!--        $.ajax({-->
<!--    		url: '--><?php //echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'sale-group'));?><!--',-->
<!--    		type: 'POST',-->
<!--    		beforeSend: function() {-->
<!--    		    $('#load_sale_group').remove();-->
<!--    		},-->
<!--    		data: {-->
<!--    			sale_branch_id: $('select[name="sale_branch_id"]').val(),-->
<!--    			sale_group_hidden: $('input[name="sale_group_hidden"]').val(),-->
<!--    		},-->
<!--    		success: function(result) {-->
<!--    			$(result).insertBefore('input[name="sale_group_hidden"]');-->
<!--    		}-->
<!--    	});-->
<!--	}-->
<!--	loadSaleGroup();-->


	$('select[name="sale_branch_id"]').change(function() {
		var select  = 'input[name="sale_group_id"]';
		var selectx = 'input[name="branch_sale_group_id"]';
		var parent  = $(select).parent();
		$('.select2-container', parent).select2('val', '');

		$(select).attr('data-parent', $(this).val());
		$(selectx).attr('data-parent', $(this).val());

<!--		loadSaleGroup();-->
    });

    function loadBranchSaleGroup(){
        var group_mkt_leader = $('input[value="group-marketing-leader"]').is(":checked");
        if(group_mkt_leader == false){
<!--            var select = 'input[name="branch_sale_group_id"]';-->
<!--            var parent  = $(select).parent();-->
<!--            $('.select2-container', parent).select2('val', '');-->
            $('.branch_sale_group_id').css('display', "none");
        }
        else{
            $('.branch_sale_group_id').css('display', "block");
        }
    }
    loadBranchSaleGroup()

	$('input[value="group-marketing-leader"]').click(function() {
        loadBranchSaleGroup()
    });

<?php $this->headScript()->captureEnd() ?>

<style type="text/css">
.form-group .control-element > label.checkbox-inline {
    font-size: 12px;
    margin: 5px 3px;
    padding: 0 0 0 15px;
    min-width: 180px;
    max-width: 260px;
}
</style>
