<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $msgError = !empty($this->msgError) ? '<div class="alert alert-danger display"><span>' . $this->msgError . '</span></div>' : '';
    $logo = !empty($this->settings['General.System.Logo']['image']) ? '<div class="box_logo_login"><img alt="" src="'. $this->settings['General.System.Logo']['image'] .'"></div>' : '';
    echo $logo;
?>
<div class="box_login">
	<div class="box_title">Đăng nhập</div>
	<?php echo $this->flashMessenger()->render();?>
	
    <div class="box_content">
    	<form class="login-form" action="" method="post">
    		<div class="form-group">
    			<div class="input-icon">
    				<i class="fa fa-user"></i>
    				<?php echo $this->formelement($myForm->get('username'));?>
    			</div>
    		</div>
    		<div class="form-group">
    			<div class="input-icon">
    				<i class="fa fa-lock"></i>
    				<?php echo $this->formelement($myForm->get('password'));?>
    			</div>
    		</div>
    		<?php echo $msgError;?>
    		<div class="form-actions">
    		    <a href="javascript:;" class="forgot_password pull-left" onclick="javascript:alert('Vui lòng liên hệ Quản trị viên');">Quên mật khẩu?</a>
    			<button type="submit" class="btn pull-right">Đăng nhập <i class="m-icon-swapright m-icon-white"></i></button>
    		</div>
    	</form>
	</div>
</div>
<div class=""></div>