<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    $number = new \ZendX\Functions\Number();
    $date = new \ZendX\Functions\Date();

    $nv = '';
    if (in_array($this->item['type'], [KMH,PTH,THU])) {
        $nv = 'Thu';
    }
    if (in_array($this->item['type'], [KTH,PNH,CHI])) {
        $nv = 'Chi';
    }

    $field_paid_cash = abs($this->item['paid_cash']) > 0 ? array('element' => '<span class="text-info">'. number_format(abs($this->item['paid_cash'])) .'</span>', 'label' => $nv.' tiền mặt', 'boxClass' => 'col-md-3') : [];
    $field_paid_transfer = abs($this->item['paid_transfer']) > 0 ? array('element' => '<span class="text-info">'. number_format(abs($this->item['paid_transfer'])) .'</span>', 'label' => $nv.' chuyển khoản', 'boxClass' => 'col-md-3') : [];

    $elementContract = array(
        array('section' => 'Thông tin phiếu thu chi khách hàng', 'boxClass' => 'col-md-12'),
        array('element' => '<span class="text-info">'. $this->item['code'] .'</span>', 'label' => 'Mã phiếu', 'boxClass' => 'col-md-3'),
        array('element' => '<span class="text-info">'. $this->debt_type[$this->item['type']] .'</span>', 'label' => 'Loại phiếu', 'boxClass' => 'col-md-3'),
//        array('element' => '<span class="text-info">'. $date->formatToView($this->item['date']) .'</span>', 'label' => 'Ngày thu chi', 'boxClass' => 'col-md-3'),
        array('element' => '<span class="text-info">Giao dịch</span>', 'label' => 'Loại nghiệp vụ', 'boxClass' => 'col-md-3'),
        array('element' => '<span class="text-info">'.$nv.'</span>', 'label' => 'Nghiệp vụ', 'boxClass' => 'col-md-3'),
        array('element' => '<span class="text-info">'. $this->item['customer_name'] .'</span>', 'label' => 'Người nộp/nhận', 'boxClass' => 'col-md-6'),
        array('element' => '<span class="text-info">'. $this->item['customer_phone'] .'</span>', 'label' => 'Số điện thoại', 'boxClass' => 'col-md-3'),
    );
    if ($field_paid_cash) {
        $elementContract[] = $field_paid_cash;
    }
    if ($field_paid_transfer) {
        $elementContract[] = $field_paid_transfer;
    }
    $xhtmlContract = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementContract);

    $elements = array(
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true)),

        array('section' => 'Nghiệp vụ', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('date'), 'label' => 'Ngày thu chi', 'validate' => array('require' => true), 'boxClass' => 'col-sm-3'),
        array('element' => $myForm->get('category_id'), 'label' => 'Danh mục', 'validate' => array('require' => true), 'boxClass' => 'col-sm-3'),
        array('element' => $myForm->get('content_select'), 'label' => 'Nội dung chọn', 'validate' => array('require' => true), 'boxClass' => 'col-sm-3'),
        array('element' => $myForm->get('content'), 'label' => 'Nội dung nhập', 'validate' => array('require' => true), 'boxClass' => 'col-sm-3'),
        array('element' => $myForm->get('note'), 'label' => 'Ghi chú thêm', 'boxClass' => 'col-sm-12'),
    );
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    $fund_cash = abs($this->item['paid_cash']) > 0 ? array('element' => $myForm->get('accountant_funds_id_cash'), 'label' => 'Quỹ tiền mặt '.$nv, 'validate' => array('require' => true), 'boxClass' => 'col-sm-3') : [];
    $fund_transfer = abs($this->item['paid_transfer']) > 0 ? array('element' => $myForm->get('accountant_funds_id_transfer'), 'label' => 'Quỹ chuyển khoản '.$nv, 'validate' => array('require' => true), 'boxClass' => 'col-sm-3') : [];
    $elements_fund = array(
        array('section' => 'Chọn sổ quỹ', 'boxClass' => 'col-md-12'),
    );
    if ($fund_cash) {
        $elements_fund[] = $fund_cash;
    }
    if ($fund_transfer) {
        $elements_fund[] = $fund_transfer;
    }

    $xhtml_fund = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements_fund);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
    <?php echo @$this->xViewElementErrors($elements_fund);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
			<?php echo $xhtmlContract;?>
		</div>
        <div class="row">
            <?php echo $xhtml;?>
        </div>
        <div class="row">
            <?php echo $xhtml_fund;?>
        </div>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>
