<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    $number = new \ZendX\Functions\Number();
    $date = new \ZendX\Functions\Date();

    $nv = '';
    if (in_array($this->item['type'], [KMH,PTH,THU])) {
        $nv = 'Thu';
    }
    if (in_array($this->item['type'], [KTH,PNH,CHI])) {
        $nv = 'Chi';
    }

    $field_paid_cash = abs($this->item['paid_cash']) > 0 ? array('element' => '<span class="text-info">'. number_format(abs($this->item['paid_cash'])) .'</span>', 'label' => $nv.' tiền mặt', 'boxClass' => 'col-md-2') : [];
    $field_paid_transfer = abs($this->item['paid_transfer']) > 0 ? array('element' => '<span class="text-info">'. number_format(abs($this->item['paid_transfer'])) .'</span>', 'label' => $nv.' chuyển khoản', 'boxClass' => 'col-md-2') : [];

    $elementContract = array(
        array('section' => 'Thông tin phiếu thu chi khách hàng', 'boxClass' => 'col-md-12'),
        array('element' => '<span class="text-info">'. $this->item['code'] .'</span>', 'label' => 'Mã phiếu', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="text-info">'. $this->debt_type[$this->item['type']] .'</span>', 'label' => 'Loại phiếu', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="text-info">'. $date->formatToView($this->item['date']) .'</span>', 'label' => 'Ngày thu chi', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="text-info">Giao dịch</span>', 'label' => 'Loại nghiệp vụ', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="text-info">'.$nv.'</span>', 'label' => 'Nghiệp vụ', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="text-info">'. $this->contact['name'] .'</span>', 'label' => 'Khách hàng', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="text-info">'. $this->contact['phone'] .'</span>', 'label' => 'Số điện thoại', 'boxClass' => 'col-md-2'),
    );
    if ($field_paid_cash) {
        $elementContract[] = $field_paid_cash;
    }
    if ($field_paid_transfer) {
        $elementContract[] = $field_paid_transfer;
    }
    $elementContract[] = array('element' => '<span class="text-info">'. $this->user[$this->item['created_by']]['name'] .'</span>', 'label' => 'Người tạo', 'boxClass' => 'col-md-2');
    $elementContract[] = array('element' => '<span class="text-info">'. $date->formatToView($this->item['created_real'], 'd/m/Y H:i:s') .'</span>', 'label' => 'Ngày tạo', 'boxClass' => 'col-md-2');

    $xhtmlContract = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementContract);

    $elements = array(
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true)),

        array('element' => $myForm->get('created'), 'label' => 'Ngày thu chi', 'validate' => array('require' => true), 'boxClass' => 'col-sm-3'),

        array('section' => 'Phiếu Thu/Chi sẽ được di chuyển đến vị trí "<span class="text-red">PHÍA TRÊN</span>" phiếu bạn chọn', 'boxClass' => 'col-md-12'),
    );
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);


$dateFormat = new \ZendX\Functions\Date();
$numberFormat = new \ZendX\Functions\Number();
// Danh sách
$xhtmlItems = '';

if(!empty($this->list_item)) {
    $index = 0;
    $list_item  = $this->list_item;
    $total_price = 0;
    foreach ($list_item AS $item) {
        $index++;
        $id             = $item['id'];
        $created        = $dateFormat->formatToView($item['created'], 'd/m/Y H:i:s');
        $created_real   = $dateFormat->formatToView($item['created_real'], 'd/m/Y H:i:s');
        $cid            = $this->item['id'] != $item['id'] ? @$this->xFormInput('sort_item', $id, array('type' => 'radio', 'class' => '')) : '';
        $created_by     = $this->user[$item->created_by]['name'];

        $order_status = '<span class="btn btn-xs '.$this->order_status[$item->state]->content.'">'.$this->order_status[$item->state]->name.'</span>';
        $linkDetail = $item['code'];

        $xhtmlItems .= '<tr id="tr_'. $id .'">
    							<td class="text-center hidden">'. $cid .'</td>
                                <td class="text-center">'. $index .'</td>
    							<td class="text-bold">'.$linkDetail.'</td>
    							<td class="">'.  $item['customer_name'] .'</td>
    							<td class="text-center">'.  $item['customer_phone'] .'</td>
    							<td class="text-center">'. $this->debt_type[$item['type']] .'</td>
    							<td class="text-right mask_currency text-green">'. abs($item['price_total']) .'</td>
    							<td class="text-right mask_currency text-purple">'. abs($item['discount']) .'</td>
    							<td class="text-right mask_currency text-purple">'. abs($item['paid_cash']) .'</td>
    							<td class="text-right mask_currency text-purple">'. abs($item['paid_transfer']) .'</td>
    							<td class="text-right mask_currency text-orange">'. $item['old_debt'] .'</td>
    							<td class="text-right mask_currency text-red">'. $item['new_debt'] .'</td>
    							<td>'. $created_by.'</br>'.$created .'</td>
    						</tr>';
    }
}

// Head
$xhtmlHead  = '<tr>';
$xhtmlHead .= '<th width="20" class="table-checkbox text-center hidden"></th>';
$xhtmlHead .= '<th class="text-center" width="20">STT</th>';
$xhtmlHead .= '<th class="text-center" width="50">Mã phiếu</th>';
$xhtmlHead .= '<th class="text-center" width="150">Khách hàng</th>';
$xhtmlHead .= '<th class="text-center" width="80">Điện thoại</th>';
$xhtmlHead .= '<th class="text-center" width="130" >Loại phiếu</th>';
$xhtmlHead .= '<th class="text-center" width="50">Tổng tiền hàng</th>';
$xhtmlHead .= '<th class="text-center" width="50">Giảm giá</th>';
$xhtmlHead .= '<th class="text-center" width="50">Tiền mặt</th>';
$xhtmlHead .= '<th class="text-center" width="50">Chuyển khoản</th>';
$xhtmlHead .= '<th class="text-center" width="50">Nợ cũ</th>';
$xhtmlHead .= '<th class="text-center" width="50">Nợ lại</th>';
$xhtmlHead .= '<th class="text-center" width="15">Người tạo</th>';
$xhtmlHead .= '</tr>';
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
<!--    	<div class="row">-->
<!--			--><?php //echo $xhtmlContract;?>
<!--		</div>-->
        <div class="row">
            <?php echo $xhtml;?>
        </div>
        <div class="row">
            <div class="table-manager" id="table-manager">
                <div class="table-scrollable table-fixed">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <?php echo $xhtmlHead;?>
                        </thead>
                        <tbody>
                        <?php echo $xhtmlItems;?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>
<style>
    #tr_<?php echo $this->item['id']; ?>{
        background-color: #9edea1 !important;
    }
    .modal-body #table-manager .table-scrollable.table-fixed{
        height: 400px !important;
    }
</style>

