<?php
$xhtml = '
    <tr id="tr_'.$this->product['id'].'">
        <td width="100px" class="text-bold text-red text-middle">'.$this->product['products_code'].'</td>
        <td width="100px" class="text-middle">'.$this->product['products_name'].' </td>
        <td class="numbers text-center"><input class="form-control text-right" type="number" name="products_list[quantity][]" value="1" min="1"></td>
        <td class="price text-middle text-right box-price">
            <input class="form-control text-right money base_price" name="products_list[price][]" type="text" value="'.number_format($this->product['cost_price']).'" min="0">
        </td>
        <td class="total">
            <input class="form-control text-right" type="text" name="products_list[total][]" readonly value="'.number_format($this->product['cost_price']).'">
        </td>
        <td class="hidden">
            <input class="form-control" type="text" name="products_list[products_id][]" value="'.$this->product['products_id'].'">
            <input class="form-control" type="text" name="products_list[name][]" value="'.$this->product['products_name'].'">
            <input class="form-control" type="text" name="products_list[code][]" value="'.$this->product['products_code'].'">
        </td>
        <td class="text-center"><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 10px 0 0 5px; font-size: 20px;"></i></td>
    </tr>';
    echo $xhtml;
?>


