<?php
$xhtml = '
    <tr id="tr_'.$this->product['id'].'">
        <td class="text-bold text-middle">'.$this->product['contract_code'].'</td>
        <td width="100px" class="text-bold text-red text-middle">'.$this->product['code'].'</td>
        <td width="100px" class="text-middle">'.$this->product['full_name'].' </td>
        <td class="note"><input class="form-control" type="text" name="contract_product[note][]"></td>
        <td class="numbers text-center"><input class="form-control text-right" type="number" name="contract_product[quantity][]" value="1" min="1"></td>
        <td class="price text-middle text-right box-price">
            <input class="form-control text-right money base_price" name="contract_product[price][]" type="text" value="'.number_format($this->product['price']).'" min="0">
        </td>
        <td class="total">
            <input class="form-control text-right" type="text" name="contract_product[total][]" readonly value="'.number_format($this->product['price']).'">
        </td>
        <td class="hidden">
            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$this->product['product_id'].'">
            <input class="form-control" type="text" name="contract_product[contract_detail_id][]" value="'.$this->product['id'].'">
            <input class="form-control" type="text" name="contract_product[name][]" value="'.$this->product['full_name'].'">
            <input class="form-control" type="text" name="contract_product[code][]" value="'.$this->product['code'].'">
        </td>
        <td class="text-center"><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 10px 0 0 5px; font-size: 20px;"></i></td>
    </tr>';
    echo $xhtml;
?>


