<?php
if (count($this->items) > 0) {
    foreach ($this->items as $key => $product_detail) {
        if ($product_detail['numbers'] > 0) {?>
            <tr class="product_row" data-code="<?php echo $this->code; ?>" >
                <td class="hidden">
                    <input type="hidden" name="contract_product[key_id][]" value="<?php echo $product_detail['key_id']; ?>">

                    <input type="hidden" name="contract_product[product_id][]" value="<?php echo $product_detail['product_id']; ?>">
                    <input type="hidden" name="contract_product[carpet_color_id][]" value="<?php echo $product_detail['carpet_color_id']; ?>">
                    <input type="hidden" name="contract_product[tangled_color_id][]" value="<?php echo $product_detail['tangled_color_id']; ?>">

                    <input type="hidden" name="contract_product[flooring_id][]" value="<?php echo $product_detail['flooring_id']; ?>">
                    <input type="hidden" name="contract_product[keyUpdate][]" value="<?php echo $key; ?>">
                    <input type="hidden" name="contract_product[sale_branch_id][]" value="<?php echo $this->sale_branch; ?>">
                    <input type="hidden" name="contract_product[type][]" value="avaiable">
                    <input type="hidden" name="contract_product[number_production][]" value="<?php echo $product_detail['number_production']; ?>">
                    <input type="hidden" name="contract_product[number_carpet][]" value="<?php echo $product_detail['number_carpet']; ?>">
                    <input type="hidden" name="contract_product[number_tangled][]" value="<?php echo $product_detail['number_tangled']; ?>">
                    <input type="hidden" name="contract_product[price_production][]" value="<?php echo $product_detail['price_production']; ?>">
                    <input type="hidden" name="contract_product[total_production][]" value="<?php echo $product_detail['total_production']; ?>">
                </td>
                <!-- end -->

                <td class="products text-middle"><?php echo $this->product[$product_detail['product_id']]["name"]; ?></td>
                <td class="stock"><input readonly class="form-control" type="text" name="contract_product[stock][]" value=""></td>
                <td class="product-name"><input class="form-control" type="text" name="contract_product[product_name][]" value="<?php echo $product_detail['product_name']; ?>"></td>
                <td class="carpet-color text-middle"><?php echo $this->carpet_color[$product_detail['carpet_color_id']]["name"]; ?></td>
                <td class="tangled-color text-middle"><?php echo $this->tangled_color[$product_detail['tangled_color_id']]["name"]; ?></td>
                <td class="flooring text-middle"><?php echo $this->flooring[$product_detail['flooring_id']]["name"]; ?></td>
                <td class="capital_default hidden"><input readonly class="form-control text-right" readonly type="text" name="contract_product[capital_default][]" value="<?php echo number_format($product_detail['capital_default']); ?>"></td>
                <td class="numbers"><input readonly class="form-control text-right" readonly type="text" name="contract_product[numbers][]" value="<?php echo number_format($product_detail['numbers']?:1); ?>" ></td>
                <td class="listed_price"><input readonly class="form-control text-right" readonly type="text" name="contract_product[listed_price][]" value="<?php echo number_format($product_detail['listed_price']); ?>" ></td>
                <td class="price"><input class="form-control text-right" type="text" name="contract_product[price][]" min="0" value="<?php echo number_format($product_detail['price']); ?>"></td>
                <td class="sale_price"><input readonly class="form-control text-right" type="text" name="contract_product[sale_price][]" value="<?php echo number_format($product_detail['sale_price']); ?>" min="0"></td>
                <td class="vat"><input class="form-control text-right" type="text" name="contract_product[vat][]" value="<?php echo number_format($product_detail['vat']); ?>" min="0"></td>
                <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" readonly value="<?php echo number_format($product_detail['total']); ?>"></td>
                <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
            </tr><?php
        }
    }
}
?>