<?php

    $this->_userInfo = new \ZendX\System\UserInfo();
    $curent_user = $this->_userInfo->getUserInfo();
    $permission_ids = explode(',', $curent_user['permission_ids']);
    $view_price_production = false;

    if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || in_array(GDCN, $permission_ids) || in_array(MANAGER, $permission_ids) || in_array(ACCOUNTING, $permission_ids)){
        $view_price_production = true;
    }

    $dateFormat = new \ZendX\Functions\Date();

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="text-center">STT</th>';
    $xhtmlHead .= '<th class="text-center">Mã sản phẩm</th>';
    $xhtmlHead .= '<th>Tên Sản phẩm</th>';
    $xhtmlHead .= '<th>Tên xe năm sản xuất</th>';
    $xhtmlHead .= '<th class="text-center">Số Lượng</th>';
    $xhtmlHead .= '<th class="text-center">Số Lượng khách trả lại</th>';
    $xhtmlHead .= '<th class="text-right">Giá bán</th>';
    $xhtmlHead .= '<th class="text-right">Thành tiền</th>';
    $xhtmlHead .= '<th class="text-right">Khối lượng</th>';
	$xhtmlHead .= '</tr>';
    
    // Danh sách
    $xhtmlItems = '';
    if($this->items) {
        $index = 1;
        foreach ($this->items AS $item) {
            $xhtmlItems .= '<tr>
    							<td class="text-center">'. $index++.'</td>
    							<td class="text-center">'. $item->code.'</td>
    							<td>'. $item->full_name.'</td>
    							<td>'. $item->car_year.'</td>
    							<td class="text-center"><span class="mask_currency">'. $item->numbers .'</span></td>
    							<td class="text-center"><span class="mask_currency">'. $item->numbers_return .'</span></td>
    							<td class="text-right"><span class="mask_currency">'. $item->price .'</span></td>
    							<td class="text-right"><span class="mask_currency">'. $item->total .'</span></td>
    							<td class="text-right"><span class="mask_currency">'. $item->weight .'</span></td>
    						</tr>';
        }
?>
<div class="table-manager">
	<div class="table-scrollable">
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<?php echo $xhtmlHead;?>
			</thead>
			<tbody>
				<?php echo $xhtmlItems;?>
			</tbody>
		</table>
	</div>
</div>
<?php
    } else {
        echo '<span class="text-danger">Không có dữ liệu</span>';
    } 
?>
