<?php
$count = $this->count;
$itemPerpage = $this->itemPerpage;
$curentPage = $this->curentPage;
$textItemPerpage = $count > $itemPerpage ? $itemPerpage : $count;
$xhtml = '';
$show_infor = $count > 0 ? '<p class="page">Hiển thị '.$textItemPerpage.' / '.$count.' sản phẩm</p>' : 'Không có sản phẩm tìm kiếm';

if($count / $itemPerpage > 1){
    $page = (int)($count / $itemPerpage);
    if($count % $itemPerpage > 0)
        $page = $page + 1;
}
if($page > 1){
    $pageText = '<ul class="pages">';
    for($p = 1; $p <= $page; $p++){
        $active = $p == $curentPage ? "active" : '';
        $pageText .= '<li class="'.$active.'">'.$p.'</li>';
    }
    $pageText .= '</ul>';
}
$xhtml .= '<div class="listProduct" >';
foreach ($this->kovProducts as $pro) {
    $num_status = $pro['quantity'] > 0 ? $pro['quantity'] : 'Hết hàng'  ;
    $xhtml .= '<div class="col-xl-4 col-sm-4 col-xs-6 item">
            <div class="product col-xs-12" data-id="' . $pro['id'] . '" data-warehouse-id="' . $pro['warehouse_id'] .'" data-customer-type-id="' . $pro['customer_type_id']. '" >
                <div class="infor col-sm-12 col-xs-12">
                    <p class="code-product text-bold">Mã: ' . $pro['code'] .'</span> </p>
                    <p class="name-product">' . $pro['name'] . '</p>
                    <p class="price-product">Giá: ' . number_format($pro['price']) . ' vnđ</p>
                    <p>Tồn kho: ' . $num_status . '<span class="text-info"> ('.($pro['weight']/1000).' kg)</span></p>
                </div>
            </div>
        </div>';
}
$xhtml .= '</div>';
$xhtml .= '<div class="pagination">'.$show_infor.$pageText.'</div>';
echo $xhtml;

?>
<style>
    .pagination{width: 100%;float: left;margin: 10px 0px; border-bottom: 1px solid #d8d8d8;}
    .pagination p{float: left;margin-right: 20px;line-height: 24px;}
    .pagination ul li {list-style: none;display: inline-block;width: 24px;height: 24px;text-align: center;line-height: 22px;border: 1px solid #d8d8d8;margin: 0px 3px;border-radius: 3px !important;cursor: pointer;}
    .pagination ul li.active {background: #f70;color: #fff;}
    .pagination ul li:hover {background: #f70;color: #fff;}
</style>

<script>
    $('#loadProducts .item .product').on('click', function () {
        var id = $(this).attr('data-id');
        var warehouse_id = $(this).attr('data-warehouse-id');
        var customer_type_id = $(this).attr('data-customer-type-id');
        if ($('#tr_' + id).length) {
            var number = $('#tr_' + id).find('.numbers input').val();
            var price = $('#tr_' + id).find('.price > input').val();
            $('#tr_' + id).find('.numbers input').val(parseInt(number) + 1);
            $('#tr_' + id).find('.total input').val(formatNumber(parseInt(unFormatNumber(price)) * (parseInt(unFormatNumber(number)) + 1)));
            updateTotal()
        } else {
            $.ajax({
                url: '/xadmin/api/add-product-to-list/',
                method: 'POST',
                data: {id: id, warehouse_id: warehouse_id, customer_type_id: customer_type_id},
                success: function (data) {
                    $('.list-product-contract').append(data);
                    format_to_money();
                    updateTotal()
                }
            })
        }
    });

    // Load sản phẩm khi chọn phân trang
    $('#loadProducts .pagination ul li').on('click', function () {
        var curentPage = parseInt($(this).text());
        var data = {filter_products_type: $(`select[name="filter_products_type"]`).val(), filter_keyword: $(`input[name="filter_keyword"]`).val(), filter_customer_type: $(`select[name="customer_type_id"]`).val(), filter_warehouse: $(`select[name="inventory_id"]`).val(), curentPage : curentPage};
        load_action('#loadProducts', '<?php echo $this->url('routeAdmin/default',array('controller' => 'api', 'action' => 'loadKovProducts'));?>', data);
    });

    $('body').delegate(".price > input , .numbers input",'change',function(e){
        var tr_parent = $(this).parents('tr');
        var number = tr_parent.find('.numbers input').val().replace(/,/gm,'');
        var price = tr_parent.find('.price > input').val().replace(/,/gm,'');
        tr_parent.find('.total input').val(formatNumber(parseInt(number) * parseInt(price)));
        updateTotal();
    });

    //Xóa hàng trong bảng sản phẩm
    $('body').on('click', '.delete-row', function(){
        deleteTr($(this).parents('tr'));
    });

    function deleteTr(tr_parent){
        tr_parent.remove();
        updateTotal();
    }
</script>