<?php
$count = $this->count;
$itemPerpage = $this->itemPerpage;
$curentPage = $this->curentPage;
$textItemPerpage = $count > $itemPerpage ? $itemPerpage : $count;
$xhtml = '';
$show_infor = $count > 0 ? '<p class="page">Hiển thị '.$textItemPerpage.' / '.$count.' sản phẩm</p>' : 'Không có sản phẩm tìm kiếm';

if($count / $itemPerpage > 1){
    $page = (int)($count / $itemPerpage);
    if($count % $itemPerpage > 0)
        $page = $page + 1;
}
if($page > 1){
    $pageText = '<ul class="pages">';
    for($p = 1; $p <= $page; $p++){
        $active = $p == $curentPage ? "active" : '';
        $pageText .= '<li class="'.$active.'">'.$p.'</li>';
    }
    $pageText .= '</ul>';
}
$xhtml .= '<div class="listProduct" >';
foreach ($this->kovProducts as $pro) {
    $xhtml .= '<div class="col-xl-3 col-sm-4 col-xs-6 item">
            <div class="product col-xs-12" data-id="' . $pro['id'] .'" >
                <div class="infor col-sm-12 col-xs-12">
                    <p class="code-product text-bold">Mã: ' . $pro['code'] .'</span> </p>
                    <p class="name-product">' . $pro['name'] . '</p>
                    <p class="name-product">' . $pro['name_vat'] . '</p>
                </div>
            </div>
        </div>';
}
$xhtml .= '</div>';
$xhtml .= '<div class="pagination">'.$show_infor.$pageText.'</div>';
echo $xhtml;

?>
<style>
    .pagination{width: 100%;float: left;margin: 10px 0px; border-bottom: 1px solid #d8d8d8;}
    .pagination p{float: left;margin-right: 20px;line-height: 24px;}
    .pagination ul li {list-style: none;display: inline-block;width: 24px;height: 24px;text-align: center;line-height: 22px;border: 1px solid #d8d8d8;margin: 0px 3px;border-radius: 3px !important;cursor: pointer;}
    .pagination ul li.active {background: #f70;color: #fff;}
    .pagination ul li:hover {background: #f70;color: #fff;}
</style>

<script>
    $('#loadProducts .item .product').on('click', function () {
        var id = $(this).attr('data-id');
        if ($('#tr_' + id).length) {
            var number = $('#tr_' + id).find('.numbers input').val();
            $('#tr_' + id).find('.numbers input').val(parseInt(number) + 1);
        } else {
            $.ajax({
                url: '/xadmin/api/add-product-to-vat/',
                method: 'POST',
                data: {id: id},
                success: function (data) {
                    $('.list-product-contract').append(data);
                    format_to_money();
                }
            })
        }
    });

    // Load sản phẩm khi chọn phân trang
    $('#loadProducts .pagination ul li').on('click', function () {
        var curentPage = parseInt($(this).text());
        var data = {filter_products_type: $(`select[name="filter_products_type"]`).val(), filter_keyword: $(`input[name="filter_keyword"]`).val(), curentPage : curentPage};
        load_action('#loadProducts', '<?php echo $this->url('routeAdmin/default',array('controller' => 'api', 'action' => 'loadProductsVat'));?>', data);
    });


    //Xóa hàng trong bảng sản phẩm
    $('body').on('click', '.delete-row', function(){
        deleteTr($(this).parents('tr'));
    });

    function deleteTr(tr_parent){
        tr_parent.remove();
    }
</script>