<?php
$count = $this->count;
$itemPerpage = $this->itemPerpage;
$curentPage = $this->curentPage;
$textItemPerpage = $count > $itemPerpage ? $itemPerpage : $count;
$xhtml = '';
$show_infor = $count > 0 ? '<p class="page">Hiển thị '.$textItemPerpage.' / '.$count.' sản phẩm</p>' : 'Không có sản phẩm tìm kiếm';

$dateFormat = new \ZendX\Functions\Date();

if($count / $itemPerpage > 1){
    $page = (int)($count / $itemPerpage);
    if($count % $itemPerpage > 0)
        $page = $page + 1;
}
if($page > 1){
    $pageText = '<ul class="pages">';
    for($p = 1; $p <= $page; $p++){
        $active = $p == $curentPage ? "active" : '';
        $pageText .= '<li class="'.$active.'">'.$p.'</li>';
    }
    $pageText .= '</ul>';
}
$xhtml .= '<div class="listProduct" >';
$customer_type_id = '';
foreach ($this->contracts as $item) {
    $stt++;
    $id                     = $item->id;
    $code                   = $item->code;
    $date                   = $dateFormat->formatToView($item->date);
    $shipped_date           = $dateFormat->formatToView($item->shipped_date);
    $date_invoice           = $dateFormat->formatToView($item->date_invoice);
    $contact_date           = $dateFormat->formatToView($item->contact_date, 'd/m/Y H:i');
    $date_return            = $dateFormat->formatToView($item->date_return, 'd/m/Y H:i');
    $index_number           = $item->index_number;
    $fee_cod                = number_format($item->price_transport);
    $vat                    = $item->option_vat == 'yes' ? $item->vat : 0 ;
    $price_total            = $item->option_vat == 'yes' ? $item->price_total - $item->vat: $item->price_total;
    $fee_other              = $item->fee_other;
    $price_owed             = $item->price_owed;

    $total_fee_other       += $fee_other;
    $total_vat             += $vat;
    $total_cod             += $item->price_transport;
    $total_paid_cash       += $item->paid_cash;
    $total_paid_transfer   += $item->paid_transfer;
    $total_discount        += $item->discount;
    $total_price_reduce_sale        += $item->price_reduce_sale;
    $total_price_owed      += $item->price_owed;

    $order_status = '<span class="btn btn-xs '.$this->order_status[$item->state]->content.'">'.$this->order_status[$item->state]->name.'</span>';

    if ($item->return_status == 1) {
        $return_status = '<br><span class="btn btn-xs purple">Hoàn 1 phần</span>';
    }
    elseif ($item->return_status == 2) {
        $return_status = '<br><span class="btn btn-xs purple">Hoàn tất cả</span>';
    }
    else{
        $return_status = '';
    }
    $options                = $item->options ? unserialize($item['options']) : array();

    $rowSpan = '';
    $number_row = 0;
    $countProduct = count($options['product']);
    if ($countProduct > 0) {
        foreach ($options['product'] as $keyp => $valuep){
            if(!empty($valuep['product_id'])){
                $number_row++;
                $rowSpan = 'rowspan="'.$number_row.'"';
            }
        }
    }
    $invoiced = $item->invoiced == 1 ? '<span class="text-danger" title="Đã xuất hóa đơn"><i class="fa fa fa-check-circle-o"></i></span>' : '';

    $xhtmlItems .= '<tr id="tr_'. $id .'" data-id="'. $id .'">
    							<td '.$rowSpan.' class="text-center">'.$stt.'</td>
    							<td '.$rowSpan.' style="left:83px;">'. $order_status .' '.$invoiced.$date_return.$return_status.'</td>
    							<td '.$rowSpan.' class="text-bold" style="left:193px;">'. $code .'</td>
    							<td '.$rowSpan.'>Lên đơn: '. $date .'<br>Xuất kho: '.$shipped_date.'<br>Xuất HĐ: '.$date_invoice.'</td>
    							';
    if (count($options['product']) > 0) {
        foreach($options['product'] as $key => $item_product) {
            if ($key == 0 && !empty($item_product['product_id'])) {
                $xhtmlItems    .= '
                                            <td>' . $item_product['full_name'].'</td>
                                            <td class="text-center">' . (new \ZendX\Functions\StringHelper)->badgeCount($item_product['numbers']?:1) . '</td>
                                            <td class="text-right">' . number_format($item_product['price']) . '</td>
                                            ';
            }
        }
    }
    else{
        $xhtmlItems    .= '<td></td><td></td><td></td>';
    }
    $xhtmlItems .= '
                            <td '.$rowSpan.' class="text-right">'. number_format($vat + $fee_other) .'</td>
                            <td '.$rowSpan.' class="text-right">'. number_format($price_total) .'</td>
                            <td '.$rowSpan.' class="text-right">'. number_format($item->paid_cash) .'</td>
                            <td '.$rowSpan.' class="text-right">'. number_format($item->paid_transfer) .'</td>
                            <td '.$rowSpan.' class="text-right">'. number_format($item->price_reduce_sale) .'</td>
                            <td '.$rowSpan.' class="text-right">'. number_format($item->fee_shipp) .'</td>
                        </tr>';

    if (count($options['product']) > 0) {
        foreach($options['product'] as $key => $item_product) {
            if ($key > 0 && !empty($item_product['product_id'])) {
                $xhtmlItems .= '<tr>
                                    <td>' . $item_product['full_name'].'</td>
                                    <td class="text-center">' . (new \ZendX\Functions\StringHelper)->badgeCount($item_product['numbers']?:1) . '</td>
                                    <td class="text-right">' . number_format($item_product['price']) . '</td>
                                    </tr>';
            }
        }
    }
}

$xhtmlHead  = '<tr>';
$xhtmlHead .= '<th width="20">STT</th>';
$xhtmlHead .= '<th width="50">Trạng thái</th>';
$xhtmlHead .= '<th width="200">Mã số đơn</th>';
$xhtmlHead .= '<th width="80">Ngày</th>';
$xhtmlHead .= '<th width="100">Sản phẩm</th>';
$xhtmlHead .= '<th width="60" class="text-center">Số lượng</th>';
$xhtmlHead .= '<th width="100" class="text-center">Giá bán</th>';
$xhtmlHead .= '<th width="80" class="text-right">Thu khác</th>';
$xhtmlHead .= '<th width="80" class="text-right">Tổng tiền hàng</th>';
$xhtmlHead .= '<th width="80" class="text-right">Trả tiền mặt</th>';
$xhtmlHead .= '<th width="80" class="text-right">Chuyển khoản</th>';
$xhtmlHead .= '<th width="80" class="text-right">Giảm trừ DT</th>';
$xhtmlHead .= '<th width="80" class="text-right">Phí giao hàng'.'</th>';
$xhtmlHead .= '</tr>';

$xhtml .= '<div class="pagination">'.$show_infor.$pageText.'</div>';


$htmlContracts = '<div class="table-scrollable table-fixed">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					'.$xhtmlHead.'
    				</thead>
    				<tbody>
    					'.$xhtmlItems.'
    				</tbody>
    			</table>
    		</div>';
echo $htmlContracts;
?>