<?php
    $xhtml = '';
    
    $user_hidden = explode(',', $this->params['data']['user_hidden']);
    if(count($this->items) > 0) {
        foreach ($this->items AS $item) {
            $id     = $item['id'];
            $name   = $item['name'];
            if(!empty($item['content'])) {
                $name .= ' - '. $item['content'];
            }
                
            $checked = '';
            if(in_array($id, $user_hidden)) {
                $checked = ' checked="checked"';
            }
                
            $xhtml .= sprintf('
                <label class="checkbox-inline checkbox2 col-md-2 col-xs-12">
                    <input type="checkbox" name="user_branch_ids[]" value="%s"%s>%s
                </label>', $id, $checked, $name
            );
        }
?>
<div class="col-md-12" id="load_user_branch">
    <div class="form-group">
    	<label class="control-label" style="padding-bottom: 5px;">Nhân sự chọn</label>
        <div class="control-element">
            <label class="checkbox-inline checkbox2 col-md-2 col-xs-12">
                <input type="checkbox" name="tick_all" value="choice_all">Tất cả
            </label>
            <?php echo $xhtml;?>
            <div class="clr" style="padding-bottom: 20px;"></div>
        </div>
    </div>
</div>
<?php
    }
?>
