<?php
$myForm = $this->myForm;
$myForm->prepare();
$dateFormat = new \ZendX\Functions\Date();
$type = ['in' => 'Nhập hàng', 'out' => 'Xuất hàng'];

$arrControl = array(
    array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
    array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
    array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
    array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
);

$elementInfor = array(
    array('section' => 'Thông tin phiếu nhập vat', 'boxClass' => 'col-md-12'),
    array('element' => '<span class="text-info">'. $this->sale_branch[$this->item['sale_branch_id']]['name'] .'</span>', 'label' => 'Chi nhánh', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $this->user[$this->item['user_id']]['name'] .'</span>', 'label' => 'Người tạo', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $dateFormat->formatToView($this->item['created'], 'd/m/Y H:i:s') .'</span>', 'label' => 'Ngày tạo', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $type[$this->item['type']] .'</span>', 'label' => 'Hình thức', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $this->item['products_code'] .'</span>', 'label' => 'Mã sản phẩm', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $this->item['products_name'] .'</span>', 'label' => 'Tên sản phẩm', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $this->item['quantity_begin'] .'</span>', 'label' => 'Tồn đầu kỳ', 'boxClass' => 'col-md-3'),
    array('element' => '<span class="text-info">'. $this->item['quantity_end'] .'</span>', 'label' => 'Tồn cuối kỳ', 'boxClass' => 'col-md-3'),
);
$xhtmlInfor = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementInfor);

$elementsTop = array(
    array('section' => 'Thông tin kho', 'boxClass' => 'col-md-12'),
    array('element' => $myForm->get('quantity'), 'label' => 'Số lượng nhập', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
    array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
);

$xhtmlTop = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsTop);

?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
    <?php echo @$this->xViewElementErrors($elementsTop);?>

    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <?php echo $xhtmlInfor;?>
            </div>
            <div class="col-md-12">
                <?php echo $xhtmlTop;?>
            </div>
        </div>
    </div>
</form>




