<?php
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('element' => $myForm->get('name'), 'label' => 'Tên', 'validate' => array('require' => true)),
        array('element' => $myForm->get('task_category_id'), 'label' => 'Danh mục', 'validate' => array('require' => true)),
        array('element' => $myForm->get('task_project_id'), 'label' => 'Dự án'),
        array('element' => $myForm->get('main_hour'), 'label' => 'Giờ thực hiện'),
        array('element' => $myForm->get('task_status_id'), 'label' => 'Trạng thái', 'validate' => array('require' => true)),
        array('element' => $myForm->get('date_begin'), 'label' => 'Ngày thực hiện', 'validate' => array('require' => true)),
        array('element' => $myForm->get('date_end'), 'label' => 'Ngày kết thúc', 'validate' => array('require' => true)),
        array('element' => $myForm->get('content'), 'label' => 'Nội dung', 'boxClass' => 'col-sm-12'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form form-tab" role="form" name="adminForm" id="adminForm">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
	</div>
</form>