<?php
$myForm = $this->myForm;
$myForm->prepare();

$arrControl = array(
    array('name'       => 'save-close',
          'caption'    => 'Lưu &amp; Đóng',
          'link'       => 'javascript:;',
          'icon'       => 'fa-save',
          'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');',
                                'class'   => 'btn')),
    array('name'       => 'close',
          'caption'    => 'Hủy',
          'link'       => $this->url('routeAdmin/default', array('controller' => $this->params['controller'],
                                                                 'action'     => 'index')),
          'onclick'    => '',
          'icon'       => 'fa-times',
          'attributes' => array('class' => 'btn')),
);

$elements = array(
//    array('element'  => $myForm->get('month'),
//          'label'    => 'Tháng',
//          'validate' => array('require' => true),
//          'boxClass' => 'col-md-1'),
//
//    array('element'  => $myForm->get('year'),
//          'label'    => 'Năm',
//          'validate' => array('require' => true),
//          'boxClass' => 'col-md-1'),

    array('element'  => $myForm->get('from_date'),
          'label'    => 'Từ Ngày',
          'validate' => array('require' => true),
          'boxClass' => 'col-md-2'),

    array('element'  => $myForm->get('to_date'),
          'label'    => 'Đến ngày',
          'validate' => array('require' => true),
          'boxClass' => 'col-md-2'),
);
$xhtml    = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

$userhtml = '';
foreach ($this->user_marketing AS $item) {
    $userhtml .= sprintf('
        <label class="checkbox-inline checkbox2 col-md-2 col-xs-12">
            <input type="checkbox" name="user_marketing[]" value="%s">%s
        </label>', $item['id'], $item['name']);
}

?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm"
      class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption; ?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array('control' => $arrControl)); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->render(); ?>
    <?php echo @$this->xViewElementErrors($elements); ?>

    <div class="page-content">
        <div class="row">
            <?php echo $xhtml; ?>
        </div>
        <h4 class="row">
            <h4>Chọn nhân viên</h4><br>
            <label class="checkbox-inline checkbox2 col-md-2 col-xs-12">
                <input type="checkbox" name="tick_all" value="choice_all">Tất cả
            </label>
            <?php echo $userhtml; ?>
        </div>
        <div class="row">
            <div class="col-md-12">
                <?php
                if (!empty($this->params['data']['control-action'])) {
                    $params = $this->params['data']['params'];
                } else {
                    $params = !empty($this->item['params']) ? unserialize($this->item['params']) : array();
                }
                ?>
            </div>
        </div>
    </div>
</form>

<?php $this->headScript()->captureStart() ?>
$("body").on("click", "input[name=tick_all]", function(){
    if($(this).attr('checked')){
        $(this).parents().parents().find('input[type="checkbox"]').attr('checked', true);
    }else{
        $(this).parents().parents().find('input[type="checkbox"]').attr('checked', false);
    }
});
<?php $this->headScript()->captureEnd() ?>
