<?php
$dateFormat = new \ZendX\Functions\Date();

$myForm = $this->myForm;
$myForm->prepare();
$myForm->get('filter_action')->setValue($this->params['action']);
$elements = array(
    array('element' => $myForm->get('filter_branches'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_categoryId'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//    array('element' => $myForm->get('filter_evaluate'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//    array('element' => $myForm->get('filter_tailors'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

    array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_action')),
    array('element' => $myForm->get('order')),
    array('element' => $myForm->get('order_by')),
);
$xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

// Head
$xhtmlHead  = '<tr>';
$xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
$xhtmlHead .= '<th class="text-center" width="60">STT</th>';
$xhtmlHead .= '<th class="text-center">Mã hóa đơn</th>';
$xhtmlHead .= '<th class="text-center">Chi nhánh</th>';
$xhtmlHead .= '<th class="text-center">Nhân viên</th>';
$xhtmlHead .= '<th class="text-center">Mã KH</th>';
$xhtmlHead .= '<th class="text-center">Khách hàng</th>';
//$xhtmlHead .= '<th class="text-center">Điện thoại</th>';
$xhtmlHead .= '<th class="text-center">Tổng tiền hàng</th>';
$xhtmlHead .= '<th class="text-center">Giảm giá</th>';
$xhtmlHead .= '<th class="text-center">Tổng sau giảm giá</th>';
$xhtmlHead .= '<th class="text-center">Trạng thái</th>';
$xhtmlHead .= '<th class="text-center">Mã Đơn hàng</th>';
$xhtmlHead .= '<th class="text-center">Ngày tạo</th>';
$xhtmlHead .= '</tr>';

// Danh sách
$xhtmlItems = '';
if($this->items->count() > 0) {
    $stt = 0;
    foreach ($this->items AS $key => $item) {
        $levels = [];
        $stt++;
        $id             = $item->Id;
        $Code           = $item->Code;
        $BranchName     = $item->BranchName;
        $SoldByName     = $item->SoldByName;
        $CustomerCode   = $item->CustomerCode;
        $CustomerName   = $item->CustomerName;
        $CustomerPhone  = $item->CustomerPhone;
        $Total          = $item->Total;
        $TotalPayment   = $item->TotalPayment;
        $Discount       = $item->Discount;
        $StatusValue    = $item->StatusValue;
        $OrderCode      = $item->OrderCode;
        $CreatedDate    = $item->CreatedDate;

        $cid            = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        $controlStatus  = $this->linkAdminStatus($id, $item->status);
        $controls       = $controlStatus;
        $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit', 'id' => $id));

        $xhtmlItems .= '<tr id="tr_'.$id.'">
    							<td>'. $cid .'</td>
                                <td class="text-center">'. $stt .'</td>
                                <td class="text-center text-bold text-green">'.$Code.'</td>
                                <td>'.$BranchName.'</td>
                                <td>'.$SoldByName.'</td>
                                <td class="text-center text-bold text-info">'.$CustomerCode.'</td>
                                <td>'.$CustomerName.'</td>
                                <td class="text-right"><span class="mask_currency">'. $Total .'</span></td>
                                <td class="text-right"><span class="mask_currency">'. $Discount .'</span></td>
                                <td class="text-right"><span class="mask_currency">'. ($Total - $Discount) .'</span></td>
                                <td class="text-center">'.$StatusValue.'</td>
                                <td class="text-center text-bold text-danger">'.$OrderCode.'</td>
                                <td class="text-center">'.$CreatedDate.'</td>
                           </tr>';
    }
}

// Control
$arrControl = array(
    array( 'name' => 'add', 'caption' => 'Đồng bộ', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'update')), 'icon' => 'fa-refresh', 'attributes' => array( 'onclick' => '', 'class' => 'btn' ) ),
    array( 'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown', ),
        'children' => array(
            array( 'name' => 'export', 'caption' => 'Xuất mẫu nhập excel', 'link' => 'javascript:;', 'icon' => 'fa-file-excel-o', 'attributes' => array( 'onclick' => 'javascript:templateImportTechnicalTailors();')) ,
        ), 'children-class' => 'dropdown-menu pull-right'
    ),
);
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
        <div class="row">
            <?php echo $xhtmlFilter;?>
        </div>
    </div>
    <div class="page-content">
        <div class="table-manager" id="table-manager">
            <div class="table-scrollable table-fixed">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <?php echo $xhtmlHead;?>
                    </thead>
                    <tbody>
                    <?php echo $xhtmlItems;?>
                    </tbody>
                </table>
            </div>
            <?php
            echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action'])), 'options' => $this->params['paginator']['options']));
            ?>
        </div>
    </div>
</form>
