<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần import dữ liệu <a href="'. URL_FILES .'/template/Mau_nhap_combo_san_pham.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => '', 'boxClass' => 'col-md-1'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->combos)) {
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<tr>
            					    <th class="col-80">Công cụ</th>
            						<th class="col-50 text-center">STT</th>
            						<th>Tên combo</th>
            						<th>sản phẩm</th>
            						<th>Màu thảm</th>
            						<th>Màu rối</th>
            						<th>Loại sản phẩm</th>
            						<th>Số lượng</th>
            						<th>Giá bán</th>
            					</tr>
            				</thead>
            				<tbody>
            					<?php
            					$index = 0;
            					foreach ($this->combos AS $key => $val) {
            							$index++;
            							$row_span = count($val['product_list']);
            							$status = $val['status'] == 'Hoàn thành' ? 'green' : 'red'
            					?>
            					<tr id="tr_<?php echo $index;?>">
            					    <td class="text-middle" rowspan="<?php echo $row_span;?>"><a href="javascript:;" class="btn btn-xs <?php echo $status;?>"><?php echo $val['status'];?></a></td>
        							<td class="text-middle text-center" rowspan="<?php echo $row_span;?>"><?php echo $index;?></td>
                                    <td class="text-middle" rowspan="<?php echo $row_span;?>"><span class="date"><?php echo $key;?></span></td>
                                    <?php
                                    foreach($val['product_list'][0] as $pro){ ?>
                                        <td><?php echo $pro;?></td>
                                    <?php
                                    }
                                    ?>
        						</tr>
        						<?php
                                    if(count($val['product_list'] > 1)){
                                        foreach($val['product_list'] as $key => $value){
                                            if($key > 0){
                                                foreach($value as $pro){ ?>
                                                    <td><?php echo $pro;?></td>
                                                <?php
                                                }
                                            }
                                        }
                                    }
            					} 
        						?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>