<?php
$dateFormat = new \ZendX\Functions\Date();

$myForm = $this->myForm;
$myForm->prepare();
$myForm->get('filter_action')->setValue($this->params['action']);
$elements = array(
    array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_status'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

    array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_action')),
    array('element' => $myForm->get('order')),
    array('element' => $myForm->get('order_by')),
);
$xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

// Head
$xhtmlHead  = '<tr>';
$xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
$xhtmlHead .= '<th class="text-center" width="60">STT</th>';
$xhtmlHead .= '<th>Tên combo</th>';
$xhtmlHead .= '<th class="text-center">Giá</th>';
$xhtmlHead .= '<th >Ghi chú</th>';
$xhtmlHead .= '<th class="text-center" width="150">Trạng thái</th>';
$xhtmlHead .= '</tr>';

// Danh sách
$xhtmlItems = '';
if($this->items->count() > 0) {
    $stt = 0;
    foreach ($this->items AS $key => $item) {
        $levels = [];
        $stt++;
        $id             = $item->id;
        $name           = $item->name;
        $note           = $item->note;
        $price_total    = $item->price_total;
        $cid            = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        $controlStatus  = $this->linkAdminStatus($id, $item->status);
        $controls       = $controlStatus;
        $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit', 'id' => $id));

        $xhtmlItems .= '<tr id="tr_'. $id .'">
    							<td>'. $cid .'</td>
                                <td  class="text-center">'. $stt .'</td>
                                <td><a href="'.$linkEdit.'">'.$name.'</a></td>
                                <td class="text-right">'. number_format($price_total) .'</td>
                                <td>'. $note .'</td>
    							<td class="text-center">'. $controls .'</td>
                           </tr>';
    }
}

// Control
$arrControl = array(
    array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'add')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => '', 'class' => 'btn' ) ),
    array( 'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown', ),
        'children' => array(
            array( 'name' => 'active', 'caption' => 'Đang bán', 'link' => 'javascript:;', 'icon' => 'fa-check-square-o', 'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 0);', ) ),
            array( 'name' => 'inactive', 'caption' => 'Ngừng bán', 'link' => 'javascript:;', 'icon' => 'fa-circle-o', 'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 1);', ) ),
            array( 'name' => 'import', 'caption' => 'Import dữ liệu', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import')), 'icon' => 'fa fa-upload' ),
            array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash', 'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');' ) ),
        ), 'children-class' => 'dropdown-menu pull-right'
    ),
);
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
        <div class="row">
            <?php echo $xhtmlFilter;?>
        </div>
    </div>
    <div class="page-content">
        <div class="table-manager" id="table-manager">
            <div class="table-scrollable table-fixed">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <?php echo $xhtmlHead;?>
                    </thead>
                    <tbody>
                    <?php echo $xhtmlItems;?>
                    </tbody>
                </table>
            </div>
            <?php
            echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action'])), 'options' => $this->params['paginator']['options']));
            ?>
        </div>
    </div>
</form>
