<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('element' => $myForm->get('filter_date_begin'), 'label' => 'Từ ngày', 'validate' => array('require' => true), 'boxClass' => 'col-sm-2'),
        array('element' => $myForm->get('filter_date_end'), 'label' => 'Đến ngày', 'validate' => array('require' => true), 'boxClass' => 'col-sm-2'),
        array('element' => $myForm->get('filter_form'), 'label' => 'Nguồn dữ liệu', 'validate' => array('require' => true)),
        array('element' => $myForm->get('filter_event'), 'label' => 'Chọn hội thảo', 'validate' => array('require' => true)),
        array('element' => $myForm->get('submit'), 'label' => '&nbsp;', 'boxClass' => 'col-md-2'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form form-tab" role="form" name="adminForm" id="adminForm">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->items)) {
            if($this->items->count() > 0) {  
		?>
    	<div class="row">
			<div class="col-md-12"><h3 class="form-section">Danh sách khách hàng</h3></div>
			<div class="col-md-12">
				<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<tr>
    						<th class="col-50">STT</th>
    						<th>Họ tên</th>
    						<th>Điện thoại</th>
    						<th>Email</th>
    						<th>ID Contact</th>
    						<th>ID Event</th>
    						<th>Công cụ</th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php
    					$index = 0;
    					foreach ($this->items AS $key => $val) { 
							$index++;
							
							$contact_id     = $val['contact_id'];
							$contact_name   = $val['contact_name'];
                            $contact_phone  = $val['contact_phone'];
                            $contact_email  = $val['contact_email'];
    					?>
    					<tr id="tr_<?php echo $index;?>" data-index="<?php echo $index;?>">
							<td><?php echo $index;?></td>
							<td><span class="name"><?php echo $contact_name;?></span></td>
							<td><span class="phone"><?php echo $contact_phone;?></span></td>
							<td><span class="email"><?php echo $contact_email;?></span></td>
							<td><span class="contact_id"><?php echo $contact_id;?></span></td>
							<td><span class="event_id"><?php echo $this->params['data']['filter_event'];?></span></td>
						    <td><a href="javascript:;" data-index="<?php echo $index;?>" class="btn btn-xs default">Import</a></td>
						</tr>
						<?php
    					} 
						?>
					</tbody>
    			</table>
			</div>
		</div>
		<?php
    		} else {
    			echo '<div class="alert alert-danger">Không có dữ liệu</div>';
    		}
		}
		?>
	</div>
</form>
<?php
if(!empty($this->items)) {
    if($this->items->count() > 0) {  
?>
<?php $this->headScript()->captureStart() ?>
    
	function startImportContact(index) {
		var item = '#tr_'+ index;
		
		if($(item).size() > 0) {
            $.ajax({
    			url: "<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'event'));?>",
    			type: 'POST',
    			data: {
                    'contact_id': $(item + ' .contact_id').text(),
                    'event_id': $(item + ' .event_id').text(),
    			},
    			beforeSend: function() {
    				$(item + ' .btn').html('Đang xử lý ...').removeClass('default').addClass('yellow');
    			},
    			success: function(result) {
    				setTimeout(function(){
    					if(result == 'Update') {
    						$(item + ' .btn').html(result).removeClass('yellow green').addClass('blue');
    					} else {
    						$(item + ' .btn').html(result).removeClass('yellow blue').addClass('green');
    					}
    				    var index_next = parseInt(index) + 1;
    				    startImportContact(index_next); 
    			    }, 100);
    			}
    		});
		} else {
		    alert('Chuyển khách hàng vào sự kiện thành công');
		}
	}
	startImportContact(1);
    
<?php $this->headScript()->captureEnd() ?>
<?php
    }
} 
?>