<?php
    // Filter
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    if(count($myForm->get('filter_sale_branch')->getValueOptions()) == 1) {
        $myForm->get('filter_sale_branch')->setEmptyOption('');
    }
    if(count($myForm->get('filter_form')->getValueOptions()) == 1) {
        $myForm->get('filter_form')->setEmptyOption('');
    }
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_begin'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_end'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_sale_branch'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_location_city'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_form'), 'boxClass' => 'col-md-3 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_active'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
    
    if(!empty($this->currentForm)) {
	    $configFields = new \ZendX\Functions\Form($this->currentForm['fields']);
	    $configFields = $configFields->getSetting();
    } else {
    	$configFields = array(
    		array('label' => 'Langding page', 'name' => 'form_id', 'type' => 'id', 'list' => true, 'option' => $this->listForm),
    	);
    }

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th class="col-50">STT</th>';
    $xhtmlHead .= '<th class="col-80">Công cụ</th>';
	$xhtmlHead .= $this->linkAdminSort('Ngày', 'created', $this->params['ssFilter'], null);
	$xhtmlHead .= '<th>Họ tên</th>';
	$xhtmlHead .= '<th>Điện thoại</th>';
	$xhtmlHead .= '<th>Email</th>';
	$xhtmlHead .= '<th>Tỉnh thành</th>';
	$xhtmlHead .= '<th>Địa điểm đăng ký</th>';
	$xhtmlHead .= '<th>Cơ sở đăng ký</th>';
	$xhtmlHead .= '<th>Người quản lý</th>';
	$xhtmlHead .= '<th>Phản hồi</th>';
    foreach ($configFields AS $field) {
        if($field['list'] == 'true') {
            $xhtmlHead .= $this->linkAdminSort($field['label'], $field['name'], $this->params['ssFilter'], null);
        }
    }
    $xhtmlHead .= '<th>Nguồn</th>';
	$xhtmlHead .= '</tr>';

    // Danh sách
    $xhtmlItems = '';
    if(!empty($this->items)) {
        $index = 0;
        
        foreach ($this->items AS $item) {
            $index++;
            $id                     = $item->id;
            $contact_name           = $item->contact_name;
            $contact_phone          = $item->contact_phone;
            $contact_email          = $item->contact_email;
            $contact_address        = $item->contact_address;
            $contact_location_city  = $this->location_city[$item->contact_location_city_id]['name'] ? $this->location_city[$item->contact_location_city_id]['name'] : 'Ngoại tỉnh';
            $contact_user           = $item->contact_user_id ? $this->user[$item->contact_user_id]['fullname'] : '';
            $contact_company_branch = $item->contact_company_branch_id ? $this->company_branch[$item->contact_company_branch_id]['name'] : '';
            $contact_company_group  = $item->contact_company_group_id ? $this->company_group[$item->contact_company_group_id]['name'] : '';
            $training_location      = $this->training_location[$item->training_location_id]['name'];
            $company_branch         = $this->company_branch[$item->company_branch_id]['name'];
            $created                = date_format(date_create($item->created), 'd/m/Y H:i:s');
            $source                 = explode('?', $item->source);
            $source                 = $source[0];
            $source_detail          = explode('?', $item->source_detail);
            $source_detail          = $source_detail[0];
            $cid                    = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));

            // Link Action
            $linkEdit               = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form', 'id' => $id));
            $linkView               = $this->url('routeAdmin/default', array('controller' => 'form-data', 'action' => 'index', 'id' => $id));
            
            // Control Action
            $controlEdit            = $this->linkAdminHtml($linkEdit, array('type' => 'icon', 'title' => 'Sửa', 'class' => 'btn btn-xs yellow', 'icon' => 'fa fa-edit'));
            $controlStatus          = $this->linkAdminStatus($id, $item->status);
            $controlManager         = $this->linkAdminHtml('javascript:;', array('type' => 'text', 'value' => 'Chưa tiếp nhận', 'title' => 'Người quản lý', 'class' => 'btn btn-xs purple', 'icon' => 'fa fa-sticky-note', 'onclick' => 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'manager')) .'\', {\'id\': \''. $id .'\'});'));
            if(!empty($item->contact_user_id)) {
                $controlManager = '';
            }
            $controls               = $controlManager;
            
            // Select result
            $selectResult  = '<select data-id="'. $id .'" name="result['. $id .'][form-data-result][]" class="form-control input-xs">';
            $selectResult .= '<option value="">-- Phản hồi --</option>';
            foreach ($this->form_data_result AS $value_form_data_result) {
                $selected_form_data_result = '';
                if($item->result_id == $value_form_data_result['id']) {
                    $selected_form_data_result = ' selected="selected"';
                }
                $selectResult .= '<option value="'. $value_form_data_result['id'] .'"'. $selected_form_data_result .'>'. $value_form_data_result['name'] .'</option>';
            }
            $selectResult .= '</select>';
            $xhtmlColumn    = '';
            foreach ($configFields AS $field) {
                if($field['list'] == 'true') {
                    $td = nl2br($item[$field['name']]);
                    switch ($field['type']) {
                        case 'json':
                            $tdTmp = unserialize($item[$field['name']]);
                            $td = '';
                            if(!empty($tdTmp)) {
	                            if(!empty($field['sprintf'])) {
	                                foreach ($tdTmp AS $value) {
	                                    $td .= sprintf($field['sprintf'], $value);
	                                }
	                            } else {
	                                $td = implode(', ', $tdTmp);
	                            }
                            }
                            break;
                        case 'textarea':
                            $td = nl2br($item[$field['name']]);
                            break;
                        case 'id':
                            $td = $field['option'][$item[$field['name']]]['name'];
                            break;
                        default:
                            if($field['name'] == 'training_class_id') {
                                $td = $this->training_class[$item[$field['name']]]['name'];
                            } elseif ($field['name'] == 'product_id') {
                                $td = $this->product[$item[$field['name']]]['name'];
                            } else {
                                $td = $item[$field['name']];
                            }
                    }
                    
                    $style = '';
                    if(($field['name'] == 'content') || ($field['name'] == 'address')) {
                    	$style = ' style="white-space: normal;"';
                    }
                    $xhtmlColumn .= '<td'. $style .'>'. $td .'</td>';
                }
            }
            
            $manager = !empty($item->manager) ? unserialize($item->manager) : array();
            $manager_str = '';
            if(!empty($manager['manager']['manager_add'])) {
                $manager_str .= $manager['manager']['manager_add'];
                $user_name .= $manager['manager']['add_by'];
            }
            
            $xhtmlItems .= '<tr id="tr_'. $id .'">
    							<td>'. $cid .'</td>
    							<td>'. $index .'</td>
							    <td style="text-align:center;">'. $controls .'</td>
    							<td>'. $created .'</td>
    							<td>'. $contact_name .'</td>
    							<td>'. $contact_phone .'</td>
    							<td>'. $contact_email .'</td>
    							<td>'. $contact_location_city .'</td>
    							<td>'. $training_location .'</td>
    							<td>'. $company_branch .'</td>
    							<td>
							        <div>'.$contact_user.'</div>
							        <div>'.$contact_company_branch.' - '.$contact_company_group.'</div>
				                </td>
					            <td>'. $selectResult .'</td>
    							'. $xhtmlColumn .'
    							<td>'. $source .'<br>'. $source_detail .'</td>
    						</tr>';
        }
    }
    
    // Control
    $arrControl = array(
        array( 'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' ), 
            'children' => array( 
                array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash', 'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');' ) ),
                array( 'name' => 'divider' ),
                array( 'name' => 'event', 'caption' => 'Chuyển vào sự kiện', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'event')), 'icon' => 'fa-dot-circle-o'), 
                array( 'name' => 'divider' ), 
                array( 'name' => 'import', 'caption' => 'Import dữ liệu', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import')), 'icon' => 'fa fa-sign-in'), 
                array( 'name' => 'export', 'caption' => 'Xuất bản excel', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'export')), 'icon' => 'fa-file-excel-o', 'attributes' => array( 'onclick' => 'javascript:exportList();' ) )
            ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
        <?php
        $permission_ids = explode(',', $this->currentForm['permission_ids']);
        $aclInfo    = new \ZendX\System\UserInfo();
        $userInfo   = $aclInfo->getUserInfo();
        $permissionInfo  = $aclInfo->getPermissionInfo();
        
        $flag = false;
        foreach ($permissionInfo AS $permission) {
            if($permission['permission'] == 'full') {
                $flag = true;
                break;
            }
            if(in_array($permission['id'], $permission_ids)) {
                $flag = true;
                break;
            }
        }
        
        // Nếu không chọn form nào thì kiểm tra có danh sách form được quyền truy cập không
        if(!empty($this->listForm) && empty($this->currentForm)) {
            $flag = true;
        }
        
        if($flag == true) {
        ?>
    	<div class="table-manager" id="table-manager">
    		<div class="">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
            ?>
    	</div>
    	<?php
    	} else {
    	    echo '<div class="alert alert-danger" role="alert"> Bạn không có quyền truy cập vào chuyên mục này </div>';
    	} 
    	?>
	</div>
</form>
<?php $this->headScript()->captureStart() ?>
    $('#adminForm table select').change(function() {
        $.ajax({
			url: '<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit-result'));?>',
			type: 'POST',
			data:{
			     result_id: $(this).val(),
			     id: $(this).attr('data-id')
			},
			beforeSend: function() {
				pageLoading('loading', '.page-container');
			},
			success: function(result) {
				if(result != '') {
					xToastr('error', 'Lỗi không thể xử lý yêu cầu', '');
				}
				pageLoading('close', '.page-container');
			}
		});
    });
<?php $this->headScript()->captureEnd() ?>