<?php
    // Filter
    $myForm				= $this->myForm;
    $model = $this->model;
    $myForm->prepare();
    $dateFormat = new \ZendX\Functions\Date();
    $numberFormat = new \ZendX\Functions\Number();

    $userInfo = new \ZendX\System\UserInfo();
    $curent_user = $userInfo->getUserInfo();
    $permission_ids = explode(',', $curent_user['permission_ids']);
    
    if(count($myForm->get('filter_sale_branch')->getValueOptions()) == 1) {
        $myForm->get('filter_sale_branch')->setEmptyOption('');
    }
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_begin'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_end'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_product_group_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_sale_branch'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_marketer_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Danh sách
    $xhtmlItems = '';
    
    if(!empty($this->items)) {
        $index = 0;
        $list_item  = $this->items;
        $total_price = 0;
        foreach ($list_item AS $item) {
            $index++;
            $id                     = $item['id'];
            $cid                    = $this->xFormInput('cid[]', $item['id'], array('type' => 'checkbox', 'class' => 'checkboxes'));
            $from_date              = $dateFormat->formatToView($item['from_date'], 'd/m/Y');
            $to_date                = $dateFormat->formatToView($item['to_date'], 'd/m/Y');
            $created                = $dateFormat->formatToView($item['created'], 'd/m/Y H:i:s');
            $price                  = $numberFormat->formatToNumber($item['price']);
            $total_price            += $price;
            $note                   = $item['note'];
            $marketer               = $item['marketer_id'] ? $this->user[$item['marketer_id']]['name'] : '';
            $branch                 = $item['sale_branch_id'] ? '<br>'.$this->branch[$item['sale_branch_id']]['name'] : '';
            $product_group          = $item['product_group_id'] ? $this->product_group[$item['product_group_id']]->name : '';
            $cid                    = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
            
            // Link Action
            $linkEdit               = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit', 'id' => $item->id));
            $controlEdit            = $this->linkAdminHtml($linkEdit, array('type' => 'icon', 'title' => 'Sửa', 'class' => 'btn btn-xs yellow', 'icon' => 'fa fa-edit'));
            $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit', 'id' => $id));
            
            $xhtmlItems .= '<tr id="tr_'. $id .'" data-contact="'.$item['contact_id'].'">
    							<td>'. $cid .'</td>
                                <td>'. $index .'</td>
    							<td>'. $from_date .'</td>
    							<td>'. $to_date .'</td>
    							<td><a href="'. $linkEdit .'">'.  $marketer.$branch .'</a></td>
    							<td>'. $product_group .'</td>
    							<td class="text-right mask_currency">'. $price .'</td>
    							<td>'. $note .'</td>
    							<td>'. $created .'</td>
    						</tr>';
        }
    }

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th width="30" class="table-checkbox"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';;
    $xhtmlHead .= '<th width="50">STT</th>';
    $xhtmlHead .= $this->linkAdminSort('Từ ngày', 'from_date', $this->params['ssFilter'], array('width' => '150'));
    $xhtmlHead .= $this->linkAdminSort('Đến ngày', 'to_date', $this->params['ssFilter'], array('width' => '150'));
    $xhtmlHead .= '<th width="160">Nhân viên MKT</th>';
    $xhtmlHead .= '<th width="150">Sản phẩm quan tâm</th>';
    $xhtmlHead .= '<th width="160" class="text-right">Chi phí: <span class="mask_currency text-red">'.$total_price.'</span></th>';
    $xhtmlHead .= '<th width="130">Ghi chú</th>';
    $xhtmlHead .= '<th width="130">Ngày tạo</th>';
    $xhtmlHead .= '</tr>';
    
    // Control
    $arrControl = array(
        array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'add')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => 'javascript:void(0)', 'class' => 'btn', ) ),
        array(
            'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown', ),
            'children' => array(
                array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash', 'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');' ) ),
            ),
            'children-class' => 'dropdown-menu pull-right'
        ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
<!--    		<div class="table-scrollable table-fixed-head">-->
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
            ?>
    	</div>
	</div>
</form>
