<?php
    $dateFormat = new \ZendX\Functions\Date();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $color_price_owed       = 'text-info';
    if(($this->contract['price_paid'] / $this->contract['price_total'] * 100) < 60) {
        $color_price_owed   = 'text-red';
    } elseif (($this->contract['price_paid'] / $this->contract['price_total'] * 100) < 100) {
        $color_price_owed   = 'text-purple';
    }
    $elementContract = array(
        array('section' => 'Thông tin thanh toán', 'boxClass' => 'col-md-12'),
        array('element' => '<span class="mask_currency text-info">'. $this->contract['price'] .'</span>', 'label' => 'Đơn giá', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="mask_currency text-info">'. $this->contract['price_promotion'] .'</span>', 'label' => 'Chiết khấu', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="mask_currency text-info">'. $this->contract['price_total'] .'</span>', 'label' => 'Thành tiền', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="mask_currency text-purple">'. $this->contract['price_paid'] .'</span>', 'label' => 'Đã thanh toán', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="mask_currency text-info">'. $this->contract['price_accrued'] .'</span>', 'label' => 'Đã chi', 'boxClass' => 'col-md-2'),
        array('element' => '<span class="mask_currency '. $color_price_owed .'">'. $this->contract['price_owed'] .'</span>', 'label' => 'Công nợ', 'boxClass' => 'col-md-2'),
    );
    $xhtmlContract = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementContract);
    
    // Hiển thị thông tin hóa đơn
    $price      = $this->item['paid_price'] ? $this->item['paid_price'] : $this->item['accrued_price'];
    $elementBill = array(
        array('section' => 'Thông tin hóa đơn', 'boxClass' => 'col-md-12'),
        array('element' => $dateFormat->formatToView($this->item['date']), 'label' => 'Ngày', 'boxClass' => 'col-md-3'),
        array('element' => $this->item['type'], 'label' => 'Phân loại', 'boxClass' => 'col-md-3'),
        array('element' => '<span class="mask_currency">'. $price .'</span>', 'label' => 'Giá tiền', 'boxClass' => 'col-md-3'),
    );
    $xhtmlBill = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementBill);
    
    $elements = array(
        array('section' => 'Nội dung', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('note_log'), 'label' => 'Lý do xóa', 'validate' => array('require' => true), 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('type'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
	<?php
	if(empty($this->item['checked_id'])) { 
	?>
    <?php echo @$this->xViewElementErrors($elements);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
			<?php echo $xhtmlContract;?>
		</div>
    	<div class="row">
			<?php echo $xhtmlBill;?>
		</div>
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
    </form>
    <?php
	} else {
		echo '<div class="alert alert-danger">Hóa đơn đã được duyệt nên không thể xóa. Vui lòng liên hệ với kế toán</div>';
	} 
    ?>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<?php
	if(empty($this->item['checked_id'])) {
	?>
	<button type="button" class="btn green save-close">Xác nhận xóa</button>
	<?php
	} 
	?>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>
