<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('section' => 'Thông tin chung', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('month'), 'label' => 'Tháng', 'validate' => array('require' => true), 'boxClass' => 'col-md-1'),
        array('element' => $myForm->get('year'), 'label' => 'Năm', 'validate' => array('require' => true), 'boxClass' => 'col-md-1'),
        array('element' => $myForm->get('name'), 'label' => 'Tiêu đề', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
    	<div class="row">
			<div class="col-md-12"><h3 class="form-section">Chỉ tiêu chi tiết</h3></div>
			<div class="col-md-12">
			    <?php
			    if(!empty($this->params['data']['control-action'])) {
			        $params = $this->params['data']['params'];
			    } else {
			        $params = !empty($this->item['params']) ? unserialize($this->item['params']) : array();
			    }
			    ?>
                <div class="table-manager" id="table-manager" style="margin-bottom: 50px;">
            		<div class="table-scrollable table-small">
            			<table class="table table-striped table-bordered">
            				<thead>
            					<tr>
                                    <th class="col-120">Cơ sở</th>
                                    <th class="col-150">Đội nhóm</th>
                                    <th>Doanh thu</th>
                                    <?php
                                    foreach ($this->product_type AS $key_product => $val_product) {
                                        echo '<th>đơn hàng '. $val_product['name'] .'</th>';
                                    } 
                                    ?>
                                    <th>Số lượng liên hệ chăm sóc</th>
                                    <th>Số lượng liên hệ</th>
            					</tr>
        					</thead>
            				<tbody>
            				    <tr id="tr_total" class="danger text-bold total">
                                    <td>Phòng kinh doanh</td>
                                    <td></td>
                                    <?php $i = 1; ?>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[total][price]" value="<?php echo $params['total']['price'];?>" class="form-control input-xs mask_currency"></td>
                                    <?php
                                    foreach ($this->product_type AS $key_product => $val_product) {
                                    ?>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[total][<?php echo $val_product['alias'];?>]" value="<?php echo $params['total'][$val_product['alias']];?>" class="form-control input-xs mask_currency"></td>
                                    <?php
                                    } 
                                    ?>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[total][history]" value="<?php echo $params['total']['history'];?>" class="form-control input-xs mask_currency"></td>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[total][contact]" value="<?php echo $params['total']['contact'];?>" class="form-control input-xs mask_currency"></td>
        						</tr>
            				    <?php
            				    foreach ($this->sale_branch AS $key_branch => $val_branch) { 
            				    ?>
            					<tr id="tr_<?php echo $val_branch['id'];?>" class="success text-bold sale_branch">
                                    <td><?php echo $val_branch['name'];?></td>
                                    <td></td>
                                    <?php $i = 1; ?>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'];?>][price]" value="<?php echo $params[$val_branch['id']]['price'];?>" class="form-control input-xs mask_currency"></td>
                                    <?php
                                    foreach ($this->product_type AS $key_product => $val_product) {
                                    ?>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'];?>][<?php echo $val_product['alias'];?>]" value="<?php echo $params[$val_branch['id']][$val_product['alias']];?>" class="form-control input-xs mask_currency"></td>
                                    <?php
                                    } 
                                    ?>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'];?>][history]" value="<?php echo $params[$val_branch['id']]['history'];?>" class="form-control input-xs mask_currency"></td>
                                    <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'];?>][contact]" value="<?php echo $params[$val_branch['id']]['contact'];?>" class="form-control input-xs mask_currency"></td>
        						</tr>
        							<?php
                				    foreach ($this->sale_group_type AS $key_group_type => $val_group_type) { 
                				    ?>
                					<tr id="tr_<?php echo $val_branch['id'] .'_'. $val_group_type['id'];?>" class="active text-bold sale_group_type">
                                        <td><?php echo $val_branch['name'];?></td>
                                        <td><?php echo $val_group_type['name'];?></td>
                                        <?php $i = 1; ?>
                                        <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'] .'_'. $val_group_type['id'];?>][price]" value="<?php echo $params[$val_branch['id'] .'_'. $val_group_type['id']]['price'];?>" class="form-control input-xs mask_currency"></td>
                                        <?php
                                        foreach ($this->product_type AS $key_product => $val_product) {
                                        ?>
                                        <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'] .'_'. $val_group_type['id'];?>][<?php echo $val_product['alias'];?>]" value="<?php echo $params[$val_branch['id'] .'_'. $val_group_type['id']][$val_product['alias']];?>" class="form-control input-xs mask_currency"></td>
                                        <?php
                                        } 
                                        ?>
                                        <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'] .'_'. $val_group_type['id'];?>][history]" value="<?php echo $params[$val_branch['id'] .'_'. $val_group_type['id']]['history'];?>" class="form-control input-xs mask_currency"></td>
                                        <td class="column" id="column_<?php echo $i++;?>"><span class="mask_currency"></span><input type="hidden" name="params[<?php echo $val_branch['id'] .'_'. $val_group_type['id'];?>][contact]" value="<?php echo $params[$val_branch['id'] .'_'. $val_group_type['id']]['contact'];?>" class="form-control input-xs mask_currency"></td>
            						</tr>
            						    <?php
            						    foreach ($this->sale_group AS $key_group => $val_group) {
            						        if($val_group_type['alias'] == $val_group['type']) {
            						            if((($val_group['document_id'] == $val_branch['id']) && !empty($val_group['status'])) || (($val_group['sale_branch_id'] == $val_branch['id']) && !empty($params[$val_group['id']]))) {
            						                unset($this->sale_group[$key]);
            						    ?>
                    					<tr class="target_item" id="tr_<?php echo $val_group['id'];?>" data-branch="tr_<?php echo $val_branch['id'];?>" data-group-type="tr_<?php echo $val_branch['id'] .'_'. $val_group_type['id'];?>">
                                            <td><?php echo $val_branch['name'];?></td>
                                            <td><?php echo $val_group['name'] .' - '. $val_group['content'];?></td>
                                            <?php $i = 1; ?>
                                            <td class="column" id="column_<?php echo $i++;?>"><input type="text" name="params[<?php echo $val_group['id'];?>][price]" value="<?php echo $params[$val_group['id']]['price'];?>" class="form-control input-xs mask_currency"></td>
                                            <?php
                                            foreach ($this->product_type AS $key_product => $val_product) {
                                            ?>
                                            <td class="column" id="column_<?php echo $i++;?>"><input type="text" name="params[<?php echo $val_group['id'];?>][<?php echo $val_product['alias'];?>]" value="<?php echo $params[$val_group['id']][$val_product['alias']];?>" class="form-control input-xs mask_currency"></td>
                                            <?php
                                            } 
                                            ?>
                                            <td class="column" id="column_<?php echo $i++;?>"><input type="text" name="params[<?php echo $val_group['id'];?>][history]" value="<?php echo $params[$val_group['id']]['history'];?>" class="form-control input-xs mask_currency"></td>
                                            <td class="column" id="column_<?php echo $i++;?>"><input type="text" name="params[<?php echo $val_group['id'];?>][contact]" value="<?php echo $params[$val_group['id']]['contact'];?>" class="form-control input-xs mask_currency"></td>
                						</tr>
            						    <?php
    						                    }
            						        }
            						    }
                				    }
            				    }
        						?>
    						</tbody>
            			</table>
            		</div>
                </div>
			</div>
		</div>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
    $(document).ready(function() {
        function update_target() {
            // Lấy tổng tiền cho các cơ sở
            $('tr.sale_branch').each(function() {
                var id_branch = $(this).attr('id');
                $('.column', this).each(function() {
                    var result = 0;
                    var id_column = $(this).attr('id');
                    $('tr.target_item[data-branch="'+ id_branch +'"]').each(function() {
                        if($('#'+ id_column +' input', this).val() == '') {
                            result = result + 0;
                        } else {
                            result = result + parseInt($('#'+ id_column +' input', this).autoNumeric('get'));
                        }
                    });
                    $('span.mask_currency', this).autoNumeric('set', result);
                    $('input.mask_currency', this).autoNumeric('set', result);
                });
            });
            
            // Lấy tổng tiền cho các nhóm
            $('tr.sale_group_type').each(function() {
                var id_group_type = $(this).attr('id');
                $('.column', this).each(function() {
                    var result = 0;
                    var id_column = $(this).attr('id');
                    $('tr.target_item[data-group-type="'+ id_group_type +'"]').each(function() {
                        if($('#'+ id_column +' input', this).val() == '') {
                            result = result + 0;
                        } else {
                            result = result + parseInt($('#'+ id_column +' input', this).autoNumeric('get'));
                        }
                    });
                    $('span.mask_currency', this).autoNumeric('set', result);
                    $('input.mask_currency', this).autoNumeric('set', result);
                });
            });
            
            // Lấy tổng tiền
            $('tr.total').each(function() {
                $('.column', this).each(function() {
                    var result = 0;
                    var id_column = $(this).attr('id');
                    $('tr.target_item').each(function() {
                        if($('#'+ id_column +' input', this).val() == '') {
                            result = result + 0;
                        } else {
                            result = result + parseInt($('#'+ id_column +' input', this).autoNumeric('get'));
                        }
                    });
                    $('span.mask_currency', this).autoNumeric('set', result);
                    $('input.mask_currency', this).autoNumeric('set', result);
                });
            });
        }
        update_target();
        
        $('.target_item input').blur(function() {
            update_target();
        });
    });
<?php $this->headScript()->captureEnd() ?>