<?php
    $dateFormat = new \ZendX\Functions\Date();

    $myForm = $this->myForm;
    $myForm->prepare();
    $myForm->get('filter_action')->setValue($this->params['action']);
    
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_begin'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_end'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_guarantee'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_sale_branch'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_sale_group'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_user'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        // array('element' => $myForm->get('filter_debt'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_action')),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th>Công cụ</th>';
    $xhtmlHead .= '<th>Mã vận đơn</th>';
    $xhtmlHead .= '<th>Mã số đơn</th>';
    $xhtmlHead .= '<th>Ngày</th>';
    $xhtmlHead .= '<th>Nhân viên</th>';
    $xhtmlHead .= '<th>Tên khách hàng</th>';
    $xhtmlHead .= '<th>Điện thoại</th>';
    $xhtmlHead .= '<th>Địa chỉ</th>';
    $xhtmlHead .= '<th>Ngày bảo hành</th>';
    $xhtmlHead .= '<th>Nội dung bảo hành</th>';
    $xhtmlHead .= '<th>VAT</th>';
    $xhtmlHead .= '<th width="80">Tổng tiền</th>';
    $xhtmlHead .= '<th>Vận chuyển</th>';
    $xhtmlHead .= '<th>Hàng sẵn có</th>';
    $xhtmlHead .= '<th>Loại thảm</th>';
    $xhtmlHead .= '<th>Tên xe - Năm sản xuất</th>';
    $xhtmlHead .= '<th>Màu sắc thảm</th>';
    $xhtmlHead .= '<th>Màu rối</th>';
    $xhtmlHead .= '<th>Số hàng ghế</th>';
    $xhtmlHead .= '<th>Lót cốp</th>';
    $xhtmlHead .= '<th>Bộ phận sản xuất</th>';
    $xhtmlHead .= '<th>Trạng thái</th>';
    $xhtmlHead .= '<th>Ghi chú sales</th>';
    $xhtmlHead .= '<th>Ghi chú sản xuất</th>';
    $xhtmlHead .= '<th>Hàng hoàn</th>';
    $xhtmlHead .= '<th>Giảm giá</th>';
    $xhtmlHead .= '<th>Người quản lý</th>';
    $xhtmlHead .= '<th>Người tạo</th>';
	$xhtmlHead .= '</tr>';
    
    // Danh sách
    $xhtmlItems = '';
    if($this->items->count() > 0) {
    	$stt = 0;
        foreach ($this->items AS $key => $item) {
        	$stt++;
        	$cid                    = @$this->xFormInput('cid[]', $item->id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        	
        	$id                     = $item->id;
        	$code                   = $item->code;
            $date                   = $dateFormat->formatToView($item->date);
            $contact_phone          = $item->contact_phone;
            $contact_name           = $item->contact_name;
            $price_carpet           = number_format($item->price_carpet);
            $price_nano             = number_format($item->price_nano);
            $vat                    = number_format($item->vat);
            $price_promotion        = number_format($item->price_promotion);
            $price_total            = $item->price_total;
            $price_paid             = $item->price_paid;
            $price_accrued          = $item->price_accrued;
            $price_owed             = $item->price_owed;
            $user_name              = $item->user_id ? $this->user[$item->user_id]['name'] : '';
            $transport              = $item->transport_id ? $this->transport[$item->transport_id]['name'] : '';
            $type_of_carpet         = $item->type_of_carpet_id ? $this->type_of_carpet[$item->type_of_carpet_id]['name'] : '';
            $carpet_color           = $item->carpet_color_id ? $this->carpet_color[$item->carpet_color_id]['name'] : '';
            $tangled_color          = $item->tangled_color_id ? $this->tangled_color[$item->tangled_color_id]['name'] : '';
            $row_seats              = $item->row_seats_id ? $this->row_seats[$item->row_seats_id]['name'] : '';
            $flooring               = $item->flooring_id ? $this->flooring[$item->flooring_id]['name'] : '';
            $production_department  = $item->production_department_type ? $this->production_department[$item->production_department_type]['name'] : '';
            $stock                  = $item->stock;
            $bill_code              = $item->bill_code;
            $product_return         = $item->product_return;
            $guarantee_date         = $dateFormat->formatToView($item->guarantee_date);
            $guarantee_note         = $item->guarantee_note;
            $status                 = $item->status_id ? $this->status[$item->status_id]['name'] : '';
            $sale_group_id          = $item->sale_group_id ? '<br>'. $this->sale_group[$item->sale_group_id]['name'] : '';
            $sale_branch_id         = $item->sale_branch_id ? ' - '. $this->sale_branch[$item->sale_branch_id]['name'] : '';
            $created                = $dateFormat->formatToView($item->created, 'd/m/Y H:i:s');
            $created_by             = $this->user[$item->created_by]['name'];
            $sale_group_created_by  = $this->user[$item->created_by]['sale_group_id'] ? '<br>'.  $this->sale_group[$this->user[$item->created_by]['sale_group_id']]['name'] : '';
            $sale_branch_created_by = $this->user[$item->created_by]['sale_branch_id'] ? ' - '.  $this->sale_branch[$this->user[$item->created_by]['sale_branch_id']]['name'] : '';
            $options                = $item->options ? unserialize($item['options']) : array();
            $contact_options        = $item->contact_options ? unserialize($item['contact_options']) : array();
            $color_price_owed       = '';
            // Link Action
            $linkView               = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => 'contract', 'action' => 'view')) .'\', {\'id\': \''. $id .'\'});';
            $linkGuaranteeAdd            = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'guarantee-add')) .'\', {\'id\': \''. $id .'\'});';
            
            // Control Action
            $controlView            = $this->linkAdminHtml($linkView, array('type' => 'icon', 'title' => 'Xem chi tiết', 'class' => 'btn btn-xs blue', 'icon' => 'fa fa-info'));
            
            $controls               = $controlView . $controlEdit;
            $controls              .= '<div class="btn-group">
    									<button class="btn green btn-xs dropdown-toggle" type="button" data-toggle="dropdown">
    									   <i class="fa fa-cog"></i> <i class="fa fa-angle-down"></i>
    									</button>
    									<ul class="dropdown-menu" role="menu">
    										<li><a href="javascript:;" onclick="'. $linkGuaranteeAdd .'"><i class="fa fa-edit"></i> Thêm bảo hành</a></li>
    									</ul>
                                    </div>';
            if (!empty($options['contact_info'])) {
                $contact_phone          = $options['contact_info']['phone'];
                $contact_name           = $options['contact_info']['name'];
            }
            $xhtmlItems .= '<tr id="tr_'. $id .'" data-id="'. $id .'">
    							<td>'. $cid .'</td>
                                <td class="controls">'. $controls .'</td>
                                <td>'. $bill_code .'</td>
    							<td>'. $code .'</td>
    							<td>'. $date .'</td>
    							<td>'. $user_name .'</td>
    							<td>'. $contact_name .'</td>
    							<td>'. $contact_phone .'</td>
                                <td>'. $contact_options['address'] .'</td>
                                <td>'. $guarantee_date .'</td>
                                <td>'. $guarantee_note .'</td>
                                <td>'. $vat .'</td>
                                <td>'. number_format($price_total) .'</td>
    							<td>'. $transport .'</td>
    							<td>'. $stock .'</td>
    							<td>'. $type_of_carpet .'</td>
    							<td>'. $options['product_name'] .'</td>
    							<td>'. $carpet_color .'</td>
    							<td>'. $tangled_color .'</td>
    							<td>'. $row_seats .'</td>
    							<td>'. $flooring .'</td>
    							<td>'. $production_department .'</td>
    							<td>'. $status .'</td>
    							<td>'. $options['sale_note'] .'</td>
    							<td>'. $options['production_note'] .'</td>
    							<td>'. $options['product_return'] .'</td>
    							<td>'. $price_promotion .'</td>
							    <td>'. $created_by . $sale_group_created_by . $sale_branch_created_by .'</td>
							    <td>'. $created_by . $sale_group_created_by . $sale_branch_created_by .'</td>
    						</tr>';
        }
    }
    
    // Control
    $arrControl = array(
        // array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'add')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => '', 'class' => 'btn' ) ),
        // array( 
        //     'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' ), 
        //     'children' => array( 
        //         array('name' => 'transfer',
        //             'caption' => 'Chuyển quyền quản lý',
        //             'link' => 'javascript:;',
        //             'icon' => 'fa-refresh',
        //             'attributes' => array( 'onclick' => 'javascript:contactChangeUser();') ),
        //         array( 'name' => 'divider' ), 
        //         array( 'name' => 'print', 'caption' => 'In đơn hàng', 'link' => 'javascript:;',  'icon' => 'fa-print', 'attributes' => array( 'onclick' => 'javascript:contractPrint();') ),
        //         array( 'name' => 'import', 'caption' => 'Cập nhật mã vận đơn', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import')), 'icon' => 'fa fa-upload' ),
        //         array( 'name' => 'export', 'caption' => 'Xuất bản excel', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'export')), 'icon' => 'fa-file-excel-o') 
        //     ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
        	?>
    	</div>
	</div>
</form>
