<script src="/public/template/backend/js/form.js?v='. date('YmdHi');?>" type="text/javascript"></script>
<?php
$dateFormat = new \ZendX\Functions\Date();
$number = new \ZendX\Functions\Number();
$i = 0;

foreach ($this->items as $item) {
    if($item['production_department_type'] == STATUS_CONTRACT_PRODUCT_POST or 1==1) {
        if(1==1 or $this->product_type_contract[$item['production_type_id']] == 'Đơn tỉnh' || ($this->product_type_contract[$item['production_type_id']] == 'Đơn Hà Nội' && !empty($this->user[$item['shipper_id']]['name']))){

            $code = $item['code'];
            $name = $item['name'];
            $user = $this->user[$item['created_by']]['name'];
            $user_phone = $this->user[$item['created_by']]['phone'];
            $shiper = $this->shippers[$item['ghtk_code']]['name'];
            $options = !empty($item['options']) ? unserialize($item['options']) : array();
            $contact_name = $item['contact_name'];
            $contact_phone = $item['contact_phone'];
            $price_deposits = $item['price_paid'];
            $fee_other = $item['fee_other'];
            $contact_license_plate = $item['contact_license_plate'];
            $note = $item['sale_note'];
            $date = date('d/m/Y');
            $contact_options = !empty($item['contact_options']) ? unserialize($item['contact_options']) : array();
            $contact_address = $options['contract_received']['address'];// địa chỉ nhận hàng
            $products = $options['product'];

            $location_city = !empty($item['location_city_id']) ?  ' - '.$this->location_city[$item['location_city_id']]['name'] : '';
            $location_district = !empty($item['location_district_id']) ? ' - '.$this->location_district[$item['location_district_id']]['name'] : '';
            $location_town = !empty($item['location_town_id']) ?  ' - '.$this->location_town[$item['location_town_id']]['name'] : '';

            $infor_contact = '
                            <p><span class="title">Ngày tháng:</span> </span> ' . $date . '</p>
                            <div class="label">
                                <p><span class="title">Mã đơn hàng:</span> ' . $code . '</p>
                                <p><span class="title">Tên sales:</span> ' . $user . '</p>
                                <p><span class="title">Tên khách hàng:</span> ' . $name . '</p>
                            </div>
                            <div class="label">
                                <p><span class="title">Tên NV giao hàng:</span> ' . $shiper . '</p>
                                <p><span class="title">SĐT Sales:</span> ' . $user_phone . '</p>
                                <p><span class="title">SĐT khách hàng:</span> ' . $item['phone'] . '</p>
                            </div>
                            <p><span class="title">Địa chỉ:</span> </span> ' . $item['address'] .$location_town.$location_district.$location_city. '</p>
                            <p><span class="title">Ghi chú sale:</span> </span> ' . $note . '</p>
                            ';

            $product_html = '';
            $total_listed_price = $total_sale_price = $total_total = 0;
            $total_vat = $item['vat'];

            foreach ($products as $key => $value) {
                $product_name = $value['full_name'];
                $product_number = $value['numbers'];
                $driver = $value['car_year'];

                $listed_price = $value['listed_price'];
                $total_listed_price += $listed_price;
                $percenter = $value['percenter'];
                $price_base = $value['price'];
                $total_price_base += $price_base;
                $total = $value['total'];
                $total_total += $total;
                $sale_price = $price_base - $total;
                $total_sale_price += $sale_price;
                // $total_vat += $value['vat'];
                $product_code = $value['code'];

                $product_html .= '<tr>
                                    <td>' . $product_code . '</td>
                                    <td>' . $product_name . '</td>
                                    <td class="text-center">' . $product_number . '</td>
                                    <td>' . $driver . '</td>
                                    <td class="text-right mask_currency">' . number_format($price_base) . '</td>
                                    <!--<td class="text-right mask_currency">' . number_format($listed_price) . '</td>-->
                                    <td class="text-right">' . number_format($sale_price) . '</td>
                                    <td class="text-right">' . number_format($total) . '</td>
                                </tr>
                                ';
            }
            $total_pay = $total_total + $total_vat + $fee_other - $price_deposits;
            ?>

            <div class="content-print">
                <div class="head-print">
                    <div class="logo">
                        <img src="/public/files/upload/default/images/logo-ok2.jpg">
                    </div>
                    <div class="company">
                        <h3>CÔNG TY TNHH SẢN XUẤT VÀ THƯƠNG MẠI XUẤT<br>NHẬP KHẨU FOREWIN</h3>
                        <p>Địa chỉ: Cụm Khu Công Nghiệp Quang Minh, Mê Linh, Hà Nội</p>
                        <p>Hotline : 0968 233 117 - 0961 793845</p>
                    </div>
                </div>
                <div class="infor-contact">
                    <h4>Phiếu giao hàng và thanh toán</h4>
                    <?php echo $infor_contact; ?>
                </div>
                <div class="infor-order">
                    <table border="1">
                        <tr>
                            <th>Mã sản phẩm</th>
                            <th>Sản phẩm</th>
                            <th>Số lượng</th>
                            <th>Tên xe - Năm sản xuất</th>
                            <th>Giá bán</th>
                            <th>Chiết khấu</th>
                            <th>Thành tiền</th>
                        </tr>
                        <?php echo $product_html; ?>

                        <tr>
                            <td colspan="3" class="text-right">Tổng giá bán</td>
                            <!--                    <td colspan="5" class="text-right">-->
                            <?php //echo number_format($total_listed_price); ?><!--</td>-->
                            <td colspan="7" class="text-right"><?php echo number_format($total_price_base); ?></td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-right">Tổng chiết khấu</td>
                            <td colspan="5" class="text-right"><?php echo number_format($total_sale_price); ?></td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-right">Tổng thành tiền <span class="text-red">(1)</span></td>
                            <td colspan="5" class="text-right"><?php echo number_format($total_total); ?></td>
                        </tr>
                        <tr>
                            <!--                    <td colspan="4" class="text-right">Tổng tiền đặt cọc</td>-->
                            <td colspan="3" class="text-right">Tổng tiền đã thanh toán <span class="text-red">(2)</span>
                            </td>
                            <td colspan="5" class="text-right"><?php echo number_format($price_deposits); ?></td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-right">Tiền thuế GTGT (VAT 10%) <span class="text-red">(3)</span>
                            </td>
                            <td colspan="5" class="text-right"><?php echo number_format($total_vat); ?></td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-right">Phụ phí <span class="text-red">(4)</span>
                            </td>
                            <td colspan="5" class="text-right"><?php echo number_format($fee_other); ?></td>
                        </tr>
                        <tr>
                            <td colspan="3" class="text-right">Tổng Tiền thanh toán <span
                                        class="text-red">(1) - (2) + (3) +(4)</span></td>
                            <td colspan="5" class="text-right"><?php echo number_format($total_pay); ?></td>
                        </tr>
                    </table>

                    <p class="pb-5 pt-5">Số tiền viết bằng chữ: <span
                                style="color: red"><?php echo $number->convertString($total_pay); ?></span></p>
                    <i>(Ghi chú : sản phẩm được bảo hành bằng sđt. Biển số trên phần mềm Forewin)</i>
                    <p class="text-right"><span>Ngày..........</span><span>Tháng..........</span><span>Năm..........</span>
                    </p>
                    <div class="chu-ky d-flex pb-80 pt-20">
                        <p class="w-25 text-center">Khách hàng</p>
                        <p class="w-25 text-center">Kế toán</p>
                        <p class="w-25 text-center">Người lập</p>
                        <p class="w-25 text-center">Thủ quỹ</p>
                    </div>
                </div>
            </div>
            <br clear="all" style="page-break-before:always"/>
            <?php
        }
        else{?>
            <div class="content-print">
                Đơn <?php echo $item['code']; ?> chưa có nhân viên giao hàng
            </div>
            <?php
        }

    }
    else{?>
        <div class="content-print">
            Đơn <?php echo $item['code']; ?> chưa có trạng thái đã giao hàng
        </div>
        <?php
    }
}
?>

<style>
    .text-red{
        color: red;
    }
    *{
        margin:0px;
        padding:0px;
        box-sizing:border-box;
        moz-box-sizing:border-box;
        webkit-box-sizing:border-box;
    }
    .w-25{
        width: 25%;
    }
    .d-flex{
        display: flex;
    }
    .pt-20{
        padding-top: 20px;
    }
    .pb-80{
        padding-bottom: 80px;
    }
    .pt-5{
        padding-top: 5px;
    }
    .pb-5{
        padding-bottom: 5px;
    }
    .pl-25{
        padding-right: 40px;
    }
    body{
        background: rgba(0,0, 0, 0.7);
        font-family: Arial, Helvetica, sans-serif;
    }
    table{
        border-collapse: collapse;
        width: 100%;
    }
    table th{
        padding: 5px;
        text-transform: capitalize;
        font-size: 14px;
    }
    table td{
        padding: 5px;
        text-transform: capitalize;
        font-size: 13px;
        font-weight: bold;
    }
    .content-print {
        min-width: 210mm;
        max-width: 297mm;
        margin: auto;
        background: #fff;
        padding: 20px;
        /*background: #fff url("/public/files/upload/default/images/logo-ok2.jpg") no-repeat center;*/
    }
    .content-print .head-print{
        width: 100%;
        display: flex;
    }
    .content-print .head-print .logo{
        width: 30%;
        text-align: center;
    }
    .content-print .head-print .logo img {
        width: 70%;
    }
    .content-print .head-print .company {
        width: 70%;
        padding: 0 20px;
        text-align: center;
    }
    .content-print .head-print .company h3{
        font-weight: bold;
        font-size: 18px;
        text-transform: uppercase;
        margin: 5px 0px;
        width: 100%;
    }
    .content-print .head-print .company p {
        padding: 3px 0;
        font-size: 14px;
        text-transform: capitalize;
        margin: 0;
    }
    .content-print .infor-contact{
        width: 100%;
        margin-bottom: 20px;
    }
    .content-print .infor-contact h4{
        text-align: center;
        font-size: 20px;
        text-transform: capitalize;
        padding: 10px 0 20px;
    }
    .content-print .infor-contact .label{
        width: 50%;
        float: left;
    }
    .content-print .infor-contact p {
        margin: 0;
        padding: 5px 30px;
        font-size: 15px;
        display: flex;
        text-transform: capitalize;
    }
    .content-print .infor-contact p span{
        min-width: 160px;
        display: inline-block;
    }
    .text-right{
        text-align: right;
    }
    .text-center{
        text-align: center;
    }

    @media print {
        tr.title{
            background-color: #d8d8d8 !important;
            -webkit-print-color-adjust: exact;
        }
    }

</style>
