<?php
    $dateFormat = new \ZendX\Functions\Date();

    $myForm = $this->myForm;
    $myForm->prepare();

$permission_ids = explode(',', $curent_user['permission_ids']);
$encode_phone = explode(',', $curent_user['encode_phone']);
$phone_code = true;
if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || !in_array('technical_contract', $encode_phone)) {
    $phone_code = false;
}

    $myForm->get('filter_action')->setValue($this->params['action']);
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_begin'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_end'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
//        array('element' => $myForm->get('filter_bill_code'), 'boxClass' => 'col-md-1 col-sm-2 col-xs-6'),
        array('element' => $myForm->get('filter_contract_type'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
//        array('element' => $myForm->get('filter_status_guarantee_id'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
//        array('element' => $myForm->get('filter_sale_branch'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//        array('element' => $myForm->get('filter_sale_group'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//        array('element' => $myForm->get('filter_user'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_product'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_status_type'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_status'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_technical_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_tailors_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//        array('element' => $myForm->get('filter_coincider'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_carpet_color'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_tangled_color'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_flooring'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_status_store'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_action')),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th width="30" class="table-checkbox"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th width="30"></th>';
    $xhtmlHead .= '<th width="70">Công cụ</th>';
    $xhtmlHead .= '<th width="180">Trạng thái</th>';
    $xhtmlHead .= '<th width="90">Mã số đơn</th>';
    $xhtmlHead .= '<th width="80">Ngày</th>';
    $xhtmlHead .= '<th width="150">Nhân viên</th>';
    $xhtmlHead .= '<th width="150">Tên khách hàng</th>';
    $xhtmlHead .= '<th width="90">Điện thoại</th>';
    $xhtmlHead .= '<th width="150">Địa chỉ</th>';
    $xhtmlHead .= '<th width="80">Tổng tiền</th>';
    $xhtmlHead .= '<th width="100">Hàng sẵn có</th>';
    $xhtmlHead .= '<th width="120">Sản phẩm</th>';
    $xhtmlHead .= '<th width="120">Số lượng</th>';
    // $xhtmlHead .= '<th width="100">Loại thảm</th>';
    $xhtmlHead .= '<th width="200">Tên xe - Năm sản xuất</th>';
    $xhtmlHead .= '<th>Thợ kỹ thuật</th>';
    $xhtmlHead .= '<th>Thợ may</th>';
    $xhtmlHead .= '<th width="150">Ghi chú sales</th>';
    $xhtmlHead .= '<th>Loại đơn</th>';
	$xhtmlHead .= '</tr>';
    
    // Danh sách
    $xhtmlItems = '';
    if($this->items->count() > 0) {
    	$stt = 0;
        foreach ($this->items AS $key => $item) {
        	$stt++;
        	$cid                    = @$this->xFormInput('cid[]', $item->id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        	
        	$id                     = $item->id;
        	$code                   = $item->code;
            $date                   = $dateFormat->formatToView($item->date);
//            $contact_phone          = $item->contact_phone;
            $contact_phone          = $phone_code && $item->contact_phone && $item->user_id != $curent_user['id'] && $item->created != $curent_user['id'] ? substr_replace($item->contact_phone, "***", 4, 3) : $item->contact_phone;
            $contact_name           = $item->contact_name;
            $price_carpet           = number_format($item->price_carpet);
            $price_nano             = number_format($item->price_nano);
            $vat                    = number_format($item->vat);
            $price_promotion        = number_format($item->price_promotion);
            $price_total            = $item->price_total;
            $price_paid             = $item->price_paid;
            $price_accrued          = $item->price_accrued;
            $price_owed             = $item->price_owed;
            $user_name              = $item->user_id ? $this->user[$item->user_id]['name'] : '';
            $transport              = $item->transport_id ? $this->transport[$item->transport_id]['name'] : '';
            $type_of_carpet         = $item->type_of_carpet_id ? $this->type_of_carpet[$item->type_of_carpet_id]['name'] : '';
            $carpet_color           = $item->carpet_color_id ? $this->carpet_color[$item->carpet_color_id]['name'] : '';
            $tangled_color          = $item->tangled_color_id ? $this->tangled_color[$item->tangled_color_id]['name'] : '';
            $row_seats              = $item->row_seats_id ? $this->row_seats[$item->row_seats_id]['name'] : '';
            $flooring               = $item->flooring_id ? $this->flooring[$item->flooring_id]['name'] : '';
            $order_type             = $item->status_store ? 'Đơn cửa hàng' : 'Đơn thường';
            $lock                   = $item->lock ? '<i class="fa fa-lock" aria-hidden="true" style="color: #bbb; padding-top: 3px;"></i>' : '';

            $status_prouduct        = $item->production_department_type ? $this->status_product[$item->production_department_type]['name'] : '';
            $status_check           = $item->status_check_id ? $this->status_check[$item->status_check_id]['name'] : '';
            $status_acccounting     = $item->status_acounting_id ? $this->status_accounting[$item->status_acounting_id]['name'] : '';
            if(!empty($status_acccounting)){
                $status = $status_acccounting;
            }
            elseif (!empty($status_check)){
                $status = $status_check;
            }
            else{
                $status = $status_prouduct;
            }
            $status = 'Sản xuất: '.$status_prouduct.'<br>'.'Giục đơn: '.$status_check.'<br>'.'Kế toán: '.$status_acccounting;

            $stock                  = $item->stock;
            $bill_code              = $item->bill_code;
            $product_return         = $item->product_return;
            $shipper_id             = $this->shipper[$item->shipper_id];

            $sale_group_id          = $item->sale_group_id ? '<br>'. $this->sale_group[$item->sale_group_id]['name'] : '';
            $sale_branch_id         = $item->sale_branch_id ? ' - '. $this->sale_branch[$item->sale_branch_id]['name'] : '';
            $created                = $dateFormat->formatToView($item->created, 'd/m/Y H:i:s');

            $user                   = $this->user[$item->user_id]['name'];
            $sale_group_user        = $this->user[$item->user_id]['sale_group_id'] ? '<br>'.  $this->sale_group[$this->user[$item->user_id]['sale_group_id']]['name'] : '';
            $sale_branch_user       = $this->user[$item->user_id]['sale_branch_id'] ? ' - '.  $this->sale_branch[$this->user[$item->user_id]['sale_branch_id']]['name'] : '';

            $created_by             = $this->user[$item->created_by]['name'];
            $sale_group_created_by  = $this->user[$item->created_by]['sale_group_id'] ? '<br>'.  $this->sale_group[$this->user[$item->created_by]['sale_group_id']]['name'] : '';
            $sale_branch_created_by = $this->user[$item->created_by]['sale_branch_id'] ? ' - '.  $this->sale_branch[$this->user[$item->created_by]['sale_branch_id']]['name'] : '';
            $options                = $item->options ? unserialize($item['options']) : array();
            $contact_options        = $item->contact_options ? unserialize($item['contact_options']) : array();
            $address = !empty($options['contract_received']['address']) ? $options['contract_received']['address'] : $contact_options['address'];
            $order_type             = $item->status_store ? 'Đơn cửa hàng' : 'Đơn thường';

            $coincider_code = '';
            if(!empty($item->coincider_status)){
                $coincider_code = 'Trùng với<br>'.$item->coincider_code;
            }

            $color_price_owed       = '';
            // Link Action
            $linkView               = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => 'contract', 'action' => 'view')) .'\', {\'id\': \''. $id .'\'});';
            $linkEdit               = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit-technical-tailors')) .'\', {\'id\': \''. $id .'\'});';
            $linkDelete             = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'delete', 'id' => $id));
            
            // Control Action
            $controlView            = '<a href="javascript:;" onclick="'. $linkView .'" title="Xem chi tiết" class="btn btn-xs blue"><i class="fa fa-info"></i></a>';
            $controlEdit            = '<a href="javascript:;" onclick="'. $linkEdit .'" title="Sửa đơn hàng" class="btn btn-xs yellow btn-edit-check"><i class="fa fa-edit"></i></a>';
            
            $controls               = $controlView . $controlEdit;

            if (!empty($options['contact_info'])) {
                $contact_phone          = $options['contact_info']['phone'];
                $contact_name           = $options['contact_info']['name'];
            }

            $color_text_row = '';
            if($item->production_department_type == STATUS_CONTRACT_PRODUCT_POST){
                $color_text_row = 'style ="background-color: #9edea1"';
            }
            if($item->production_department_type == STATUS_CONTRACT_PRODUCT_CANCEL){
                $color_text_row = 'style ="background-color: #e29494"';
            }
            if($item->production_department_type == STATUS_CONTRACT_PRODUCT_PRODUCTED){
                $color_text_row = 'style ="background-color: #aed2f5"';
            }

            $rowSpan = '';
            $number_row = 0;
            $listed_price = 0;
            $countProduct = count($options['product']);
            if ($countProduct > 0) {
                foreach ($options['product'] as $keyp => $valuep){
                    if(!empty($valuep['product_id'])){
                        $number_row++;
                        $rowSpan = 'rowspan="'.$number_row.'"';
                        $listed_price += $valuep['listed_price'];
                    }
                }
            }

            $xhtmlItems .= '<tr id="tr_'. $id .'" data-id="'. $id .'"'.$color_text_row.'>
    							<td '.$rowSpan.'>'. $cid .'</td>
    							<td '.$rowSpan.'>'. $lock .'</td>
                                <td '.$rowSpan.' class="controls">'. $controls .'</td>
                                <td '.$rowSpan.'>'. $status .'</td>
    							<td '.$rowSpan.' class="text-bold">'. $code .'</td>
    							<td '.$rowSpan.'>'. $date .'</td>
    							<td '.$rowSpan.'>'. $user_name .'</td>
    							<td '.$rowSpan.'>'. $contact_name .'</td>
    							<td '.$rowSpan.'>'. $contact_phone .'</td>
    							<td class="av-read" '.$rowSpan.' title="'.$address.'">'. $address .'</td>
    							<td '.$rowSpan.'>'. number_format($price_total) .'</td>';
            if (count($options['product']) > 0) {
                foreach($options['product'] as $key => $item_product) {
                    $technical = '';
                    $tailors   = '';
                    if(!empty($item_product['technical_id'])){
                        $technical_id = explode(',', $item_product['technical_id']);
                        foreach($technical_id as $value){
                            $technical .= $this->technical[$value]['name'].', ';
                        }
                    }
                    if(!empty($item_product['tailors_id'])){
                        $tailors_id = explode(',', $item_product['tailors_id']);
                        foreach($tailors_id as $value){
                            $tailors .= $this->tailors[$value]['name'].', ';
                        }
                    }

                    if ($key == 0 && !empty($item_product['product_id'])) :
                    $carpet_color           = $item_product['carpet_color_id'] ? $this->carpet_color[$item_product['carpet_color_id']]['name'] : '';
                    $tangled_color          = $item_product['tangled_color_id'] ? $this->tangled_color[$item_product['tangled_color_id']]['name'] : '';
                    $flooring               = $item_product['flooring_id'] ? $this->flooring[$item_product['flooring_id']]['name'] : '';
                    $productName = $item->kov_status ? $this->kovProduct[$item_product['product_id']]['fullName'] : $this->product[$item_product['product_id']]['name'];
                    $xhtmlItems .= '
                                    <td>'. $item_product['stock'] .'</td>
                                    <td title="'.$productName.'">'. $productName .'  '.$carpet_color.'  '.$tangled_color.'  '.$flooring.'</td>
                                    <td class="text-center">' . (new \ZendX\Functions\StringHelper)->badgeCount($item_product['numbers']?:1) . '</td>
                                    <td class="av-read" title="'.$item_product['product_name'].'">'. $item_product['product_name'] .'</td>
                                    <td>'. $technical .'</td>
                                    <td>'. $tailors .'</td>';
                    endif;
                }
            } else {
                $xhtmlItems .= '<td></td>
    							<td></td>
    							<td></td>
    							<td></td>
    							<td></td>
                                <td></td>';
            }
            $xhtmlItems .= '
    							<td class="av-read" '.$rowSpan.'>'. $options['sale_note'] .'</td>
    							<td class="av-read" '.$rowSpan.'>'. $order_type .'</td>
                            </tr>';
            if (count($options['product']) > 0) {
                foreach($options['product'] as $key => $item_product) {
                    if ($key > 0 && !empty($item_product['product_id'])) :
                        $technical = '';
                        $tailors   = '';
                        if(!empty($item_product['technical_id'])){
                            $technical_id = explode(',', $item_product['technical_id']);
                            foreach($technical_id as $value){
                                $technical .= $this->technical[$value]['name'].', ';
                            }
                        }
                        if(!empty($item_product['tailors_id'])){
                            $tailors_id = explode(',', $item_product['tailors_id']);
                            foreach($tailors_id as $value){
                                $tailors .= $this->tailors[$value]['name'].', ';
                            }
                        }
                        $carpet_color           = $item_product['carpet_color_id'] ? $this->carpet_color[$item_product['carpet_color_id']]['name'] : '';
                        $tangled_color          = $item_product['tangled_color_id'] ? $this->tangled_color[$item_product['tangled_color_id']]['name'] : '';
                        $flooring               = $item_product['flooring_id'] ? $this->flooring[$item_product['flooring_id']]['name'] : '';
                        $productName = $item->kov_status ? $this->kovProduct[$item_product['product_id']]['fullName'] : $this->product[$item_product['product_id']]['name'];
                        $xhtmlItems .= '<tr '.$color_text_row.'>
                                        <td>'. $item_product['stock'] .'</td>
                                        <td title="'.$productName.'">'. $productName .'  '.$carpet_color.'  '.$tangled_color.'  '.$flooring.'</td>
                                        <td class="text-center">' . (new \ZendX\Functions\StringHelper)->badgeCount($item_product['numbers']?:1) . '</td>
                                        <td class="av-read" title="'.$item_product['product_name'].'">'. $item_product['product_name'] .'</td>
                                        <td>'. $technical .'</td>
                                        <td>'. $tailors .'</td>
                                        </tr>';
                    endif;
                }
            }
        }
    }
    $blank = "'blank'";
    // Control
    $arrControl = array(
        array(
            'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' ), 
            'children' => array( 
//                array( 'name' => 'print-production', 'caption' => 'In sản xuất', 'link' => 'javascript:;',  'icon' => 'fa-print', 'attributes' => array( 'onclick' => 'javascript:contractPrintProduction('.$blank.');') ),
//                array( 'name' => 'print-ship', 'caption' => 'In giao hàng', 'link' => 'javascript:;',  'icon' => 'fa-print', 'attributes' => array( 'onclick' => 'javascript:contractPrint('.$blank.');') ),
//                array( 'name' => 'export', 'caption' => 'Xuất bản excel', 'link' => 'javascript:;', 'icon' => 'fa-file-excel-o', 'attributes' => array( 'onclick' => 'javascript:contractExport();')) ,
//                array('name' => 'excel-update','caption' => 'Cập nhật trạng thái từ Excel','link' => '/xadmin/production/update-excel','icon' => 'fa fa-file-excel-o',
//                    'attributes' => array(
//                        'title' => 'Cập nhật trạng thái đơn hàng đã chọn từ tệp Excel',
//                    ),
//                ) ,
//                array('name' => 'transported','caption' => 'Xác nhận - Đã giao hàng','link' => 'javascript:;','icon' => 'fa fa-truck',
//                    'attributes' => array(
//                        'onclick' => 'javascript:updateItem(\'transported\', \'Trạng thái đơn hàng chỉ được cập nhật một lần! <br> Bạn có chắc chắn muốn cập nhật đơn hàng về trạng thái: Đã giao hàng ?\');',
//                        'title' => 'Cập nhật trạng thái đơn hàng đã chọn thành trạng thái: Đã giao hàng',
//                    ),
//                ) ,

                array( 'name' => 'export', 'caption' => 'Xuất mẫu nhập excel', 'link' => 'javascript:;', 'icon' => 'fa-file-excel-o', 'attributes' => array( 'onclick' => 'javascript:templateImportTechnicalTailors();')) ,
                array( 'name' => 'import_technical', 'caption' => 'Import thợ kỹ thuật', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import-technical')), 'icon' => 'fa fa-upload' ),
                array( 'name' => 'export-technical', 'caption' => 'Xuất excel', 'link' => 'javascript:;', 'icon' => 'fa-file-excel-o', 'attributes' => array( 'onclick' => 'javascript:templateImportTechnicalTailors(\'export-technical\');')) ,
            ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable table-fixed">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action'])), 'options' => $this->params['paginator']['options']));
        	?>
    	</div>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
    
    $('.btn-edit-check').on('click', function() {
        var parent_td = $(this).parent('td');
        var parent_tr = parent_td.parent('tr');
        parent_tr.find('input[name="cid[]"]').attr('checked', 'checked');
    });
<?php $this->headScript()->captureEnd() ?>