<?php
    $myForm = $this->myForm;
    $myForm->prepare();

    $elements = array(
        array('section' => 'Đánh giá nhân viên sale', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('sale_level'), 'label' => 'Mức độ hài lòng nhân viên sale', 'validate' => array('require' => true), 'boxClass' => 'col-md-12 box-radio'),
        array('element' => $myForm->get('sale_note'), 'label' => 'Ý kiến đóng góp cho nhân viên sales', 'boxClass' => 'col-md-12'),
        array('section' => 'Đánh giá sản phẩm', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('technical_level'), 'label' => 'Mức độ hài lòng sản phẩm', 'validate' => array('require' => true), 'boxClass' => 'col-md-12 box-radio'),
        array('element' => $myForm->get('technical_product'), 'label' => 'Sản phẩm kỹ thuật', 'boxClass' => 'col-md-12 box-product hidden'),
        array('element' => $myForm->get('technical_note'), 'label' => 'Ý kiến đóng góp sản phẩm', 'boxClass' => 'col-md-12'),

        array('element' => $myForm->get('code')),
        array('element' => $myForm->get('contract_id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true)),
    );
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    $element_tailors = array(
        array('section' => 'Đánh giá thợ may', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('tailors_level'), 'label' => 'Mức độ hài lòng thợ may', 'validate' => array('require' => true), 'boxClass' => 'col-md-12 box-radio'),
        array('element' => $myForm->get('tailors_product'), 'label' => 'Sản phẩm thợ may', 'boxClass' => 'col-md-12 box-product-tailors hidden'),
        array('element' => $myForm->get('tailors_note'), 'label' => 'Ý kiến đóng góp thợ may', 'boxClass' => 'col-md-12'),
    );
    $xhtml_tailors = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $element_tailors);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
    <?php echo @$this->xViewElementErrors($element_tailors);?>
    <div class="row">
        <?php if($this->check_order){ ?>
        <div class="col-md-12">
            <h3 class="form-section">Thông tin khách hàng</h3>
        </div>
        <div class="col-md-3">
            <label class="control-label">Đơn hàng</label>
            <div class="form-control-info text-orange text-bold">
                <span class="text-info contract_code"><?php echo $this->contract['code']; ?></span>
            </div>
        </div>
        <div class="col-md-3">
            <label class="control-label">Giá trị</label>
            <div class="form-control-info text-orange text-bold">
                <span class="text-info contract_price_title"><?php echo $this->contract['price_total']; ?></span>
            </div>
        </div>
        <div class="col-md-3">
            <label class="control-label">Khách hàng</label>
            <div class="form-control-info text-orange text-bold">
                <span class="text-info contact_name"><?php echo $this->contact['name']; ?></span>
            </div>
        </div>
        <div class="col-md-3">
            <label class="control-label">Số điện thoại</label>
            <div class="form-control-info text-orange text-bold">
                <span class="text-info contact_phone"><?php echo $this->contact['phone']; ?></span>
            </div>
        </div>
        <?php }else{ ?>
            <div class="col-md-3">
                <div class="form-group">
                    <label class="control-label">Mã đơn hàng</label>
                    <div class="control-element">
                        <input type="text" name="contract_code" class="form-control" placeholder="Nhập mã đơn hàng" value="">
                    </div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    <label class="control-label">.</label>
                    <div class="control-element">
                        <input type="button" name="search" class="form-control btn btn-sm green" value="Tìm kiếm">
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <h3 class="form-section">Thông tin khách hàng</h3>
                <p class="text-red"><?php echo $this->notify ?></p>
            </div>
        <?php } ?>
    </div>
    <?php if($this->check_order){ ?>
    <form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
			<?php echo $xhtml;?>
			<?php if($this->evaluate_tailors) echo $xhtml_tailors; ?>
		</div>
    </form>
    <?php } ?>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Gửi đánh giá</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>

<script type="text/javascript">
    $('input[name="search"]').click(function() {
        var order_code = $('input[name="contract_code"]').val();
        if(order_code.length){
            $('.modal-scrollable').remove();
            $('.modal-backdrop.fade.in').remove();
            popupAction('/xadmin/evaluate/form/', {'code': order_code});
        }
    });

    $('input[name="technical_level"]').click(function() {
        showProduct($(this).val());
    });
    showProduct($("input[name='technical_level']:checked").val());

    function showProduct(level){
        if(level < 4){
            $('.box-product').removeClass('hidden');
            $(".box-product select").select2('val', '');
        }
        else {
            $('.box-product').addClass('hidden');
            $(".box-product select").select2('val', '');
        }
    }

    $('input[name="tailors_level"]').click(function() {
        showProductTailors($(this).val());
    });
    showProductTailors($("input[name='tailors_level']:checked").val());

    function showProductTailors(level){
        if(level < 4){
            $('.box-product-tailors').removeClass('hidden');
            $(".box-product-tailors select").select2('val', '');
        }
        else {
            $('.box-product-tailors').addClass('hidden');
            $(".box-product-tailors select").select2('val', '');
        }
    }

    $('.box-radio .control-element label').each(function (index) {
        var img = (index % 5) + 1 ;
        img = img.toString();
        $(this).attr('style' , "background: url(/public/files/upload/default/images/"+img+".png) no-repeat right;");
    });

</script>

<style>
    .box-radio .control-element label {
        line-height: 32px;
        margin-right: 30px;
        width: 120px;
        height: 110px;
        position: relative;
    }
    .box-radio .control-element label input {
        width: 15px;
        float: left;
        position: absolute;
        bottom: -22px;
        left: 57%;
    }
</style>
