<?php
if($this->items->count() > 0) {
	$dateFormat = new \ZendX\Functions\Date();

	// Head
	$xhtmlHead  = '<tr>';
	$xhtmlHead .= '<th>STT</th>';
	$xhtmlHead .= '<th>Ngày nhập</th>';
	$xhtmlHead .= '<th>Hành động</th>';
	$xhtmlHead .= '<th>Kết quả</th>';
	$xhtmlHead .= '<th>Phân loại</th>';
	$xhtmlHead .= '<th>Nội dung/Ghi chú</th>';
	$xhtmlHead .= '<th>Hẹn chăm sóc lại</th>';
	$xhtmlHead .= '<th>Người thực hiện</th>';
	$xhtmlHead .= '</tr>';
	
	$xhtmlItems = '';
	$index = 0;
	foreach ($this->items AS $item) {
		$index++;
		$id             = $item->id;
		$created        = $dateFormat->formatToView($item->created, 'd/m/Y H:i');
		$action_id		= $this->sale_history_action[$item->action_id]['name'];
		$result_id		= $this->sale_history_result[$item->result_id]['name'];
		$type_id		= $this->sale_history_type[$item->type_id]['name'];
		$content		= $item->content;
		$return			= $dateFormat->formatToView($item->return);
		$return_content	= $item->return_content;
		$user_id        = $item->user_id ? $this->user[$item->user_id]['name'] : '';
		$sale_group_id  = $item->sale_group_id ? ' - '. $this->sale_group[$item->sale_group_id]['name'] : '';
		$sale_branch_id = $item->sale_branch_id ? ' - '. $this->sale_branch[$item->sale_branch_id]['name'] : '';

		$xhtmlItems .= '<tr id="tr_'. $id .'">
    							<td>'. $index .'</td>
    							<td>'. $created .'</td>
    							<td>'. $action_id .'</td>
    							<td>'. $result_id .'</td>
    							<td>'. $type_id .'</td>
    							<td>'. $content .'</td>
    							<td>'. $return .'</td>
    							<td>'. $user_id . $sale_group_id . $sale_branch_id .'</td>
    						</tr>';
	}
?>
<div class="table-manager">
	<div class="table-scrollable">
		<table class="table table-striped table-bordered table-hover">
			<thead>
				<?php echo $xhtmlHead;?>
			</thead>
			<tbody>
				<?php echo $xhtmlItems;?>
			</tbody>
		</table>
	</div>
</div>
<?php
} else {
    echo '<span class="text-danger">Không có dữ liệu</span>';
} 
?>
