<?php
$dateFormat = new \ZendX\Functions\Date();

$myForm = $this->myForm;
$myForm->prepare();
$myForm->get('filter_action')->setValue($this->params['action']);
$elements = array(
    array('element' => $myForm->get('filter_branches'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_categoryId'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//    array('element' => $myForm->get('filter_evaluate'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//    array('element' => $myForm->get('filter_tailors'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

    array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    array('element' => $myForm->get('filter_action')),
    array('element' => $myForm->get('order')),
    array('element' => $myForm->get('order_by')),
);
$xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

// Head
$xhtmlHead  = '<tr>';
$xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
$xhtmlHead .= '<th class="text-center" width="60">STT</th>';
$xhtmlHead .= '<th>Kho hàng</th>';
$xhtmlHead .= '<th>Nhóm hàng</th>';
$xhtmlHead .= '<th class="text-center">Mã sản phẩm</th>';
$xhtmlHead .= '<th>Tên sản phẩm</th>';
$xhtmlHead .= '<th>Loại sản phẩm</th>';
$xhtmlHead .= '<th class="text-center">Tồn kho</th>';
$xhtmlHead .= '<th class="text-center">KH đặt</th>';
$xhtmlHead .= '<th class="text-center">Giá vốn Kiotviet</th>';
$xhtmlHead .= '<th class="text-center">Giá vốn CRM</th>'; // trước là phần điều chỉnh cộng thêm một giá trị cố định
//$xhtmlHead .= '<th class="text-center">Phụ phí</th>';
//$xhtmlHead .= '<th class="text-center">Giá vốn CRM</th>';
$xhtmlHead .= '<th class="text-center">Giá bán</th>';
$xhtmlHead .= '<th class="text-center" width="70">Trạng thái</th>';
$xhtmlHead .= '</tr>';

// Danh sách
$xhtmlItems = '';
if($this->items->count() > 0) {
    $stt = 0;
    foreach ($this->items AS $key => $item) {
        $levels = [];
        $stt++;
        $id             = $item->id;
        $code           = $item->code;
        $fullName       = $item->fullName;
        $categoryId     = $this->categories[$item->categoryId];
        $basePrice      = $item->basePrice;
        $branch_cost        = $item->branch_cost;
        $branch_cost_new    = $item->branch_cost_new;
//        $branch_fee         = $item->branch_fee;
        $product_type       = $item->product_type == 1 ? 'Hàng có sẵn' : 'Hàng sản xuất';
//        $branch_cost_crm    = $branch_cost + $item->branch_cost_new + $branch_fee;
        $branch_onHand      = $item->branch_onHand; // Tồn kho
        $branch_reserved    = $item->branch_reserved; // Khách đặt
        $branch           = $this->sale_branch[$item->branch_id]['name']; // Kho hàng

        $cid            = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        $controlStatus  = $this->linkAdminStatus($id, $item->status);
        $controls       = $controlStatus;
        $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit', 'id' => $id));
        $unit = $branch_cost_new ? '%' : '';

        $xhtmlItems .= '<tr id="tr_'.$id.'">
    							<td>'. $cid .'</td>
                                <td  class="text-center">'. $stt .'</td>
                                <td>'.$branch.'</td>
                                <td>'.$categoryId.'</td>
                                <td class="text-center">'.$code.'</td>
                                <td>'.$fullName.'</td>
                                <td>'.$product_type.'</td>
                                <td class="text-center">'.$branch_onHand.'</td>
                                <td class="text-center">'.$branch_reserved.'</td>
                                <td class="text-right"><span class="mask_currency">'. $branch_cost .'</span></td>
                                <td class="text-right"><span class="mask_currency">'. $branch_cost_new .'</span></td>
                                <td class="text-right"><span class="mask_currency">'. $basePrice .'</span></td>
    							<td class="text-center">'. $controls .'</td>
                           </tr>';
    }
}

// Control
$arrControl = array(
    array( 'name' => 'add', 'caption' => 'Đồng bộ', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'update')), 'icon' => 'fa-refresh', 'attributes' => array( 'onclick' => '', 'class' => 'btn' ) ),
    array( 'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown', ),
        'children' => array(
//            array( 'name' => 'active', 'caption' => 'Sử dụng', 'link' => 'javascript:;', 'icon' => 'fa-check-square-o', 'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 0);', ) ),
//            array( 'name' => 'inactive', 'caption' => 'Ngừng bán', 'link' => 'javascript:;', 'icon' => 'fa-circle-o', 'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 1);', ) ),
//            array(
//                'name' => 'available','caption' => 'Hàng bán sẵn','link' => 'javascript:;','icon' => 'fa fa-balance-scale',
//                'attributes' => array(
//                    'onclick' => 'javascript:updateItem(\'available\', \'Các sản phẩm đã chọn sẽ chuyển sang loại là hàng bán sẵn.<br> bạn có chắc chắn muốn chuyển tất cả không ?\');',
//                    'title' => 'Chuyển sản phẩm thành hàng bán sẵn',
//                ),
//            ) ,
//            array(
//                'name' => 'unavailable','caption' => 'Hàng sản xuất','link' => 'javascript:;','icon' => 'fa fa-user',
//                'attributes' => array(
//                    'onclick' => 'javascript:updateItem(\'unavailable\', \'Các sản phẩm đã chọn sẽ chuyển sang loại là hàng sản xuất.<br> bạn có chắc chắn muốn chuyển tất cả không ?\');',
//                    'title' => 'Chuyển sản phẩm thành hàng sản xuất',
//                ),
//            ) ,
//            array(
//                'name' => 'tailors','caption' => 'Có đánh giá thợ may','link' => 'javascript:;','icon' => 'fa fa-check',
//                'attributes' => array(
//                    'onclick' => 'javascript:updateItem(\'tailors\', \'Các sản phẩm đã chọn sẽ chuyển sang sản phẩm được đánh giá thợ may.<br> bạn có chắc chắn muốn chuyển tất cả không ?\');',
//                    'title' => 'Có đánh giá thợ may',
//                ),
//            ) ,
//            array(
//                'name' => 'untailors','caption' => 'Bỏ đánh giá thợ may','link' => 'javascript:;','icon' => 'fa fa-times',
//                'attributes' => array(
//                    'onclick' => 'javascript:updateItem(\'untailors\', \'Các sản phẩm đã chọn sẽ bỏ đánh giá thợ may.<br> bạn có chắc chắn muốn chuyển tất cả không ?\');',
//                    'title' => 'Bỏ đánh giá thợ may',
//                ),
//            ) ,
            array( 'name' => 'export', 'caption' => 'Xuất mẫu nhập excel', 'link' => 'javascript:;', 'icon' => 'fa-file-excel-o', 'attributes' => array( 'onclick' => 'javascript:templateImportTechnicalTailors();')) ,
            array( 'name' => 'import', 'caption' => 'Import dữ liệu', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import')), 'icon' => 'fa fa-upload' ),
        ), 'children-class' => 'dropdown-menu pull-right'
    ),
);
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
        </div>
        <div class="clearfix"></div>
    </div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
        <div class="row">
            <?php echo $xhtmlFilter;?>
        </div>
    </div>
    <div class="page-content">
        <div class="table-manager" id="table-manager">
            <div class="table-scrollable table-fixed">
                <table class="table table-striped table-bordered table-hover">
                    <thead>
                    <?php echo $xhtmlHead;?>
                    </thead>
                    <tbody>
                    <?php echo $xhtmlItems;?>
                    </tbody>
                </table>
            </div>
            <?php
            echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action'])), 'options' => $this->params['paginator']['options']));
            ?>
        </div>
    </div>
</form>
