<?php
    $date = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('section' => 'Thông tin', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần import dữ liệu <a href="'. URL_FILES .'/template/Mau_nhap_data_co_san.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('marketing_channel_id'), 'label' => 'Kênh marketing', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('submit'), 'label' => '&nbsp;', 'boxClass' => 'col-md-2'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->sheetData)) {  
		?>
    	<div class="row">
			<div class="col-md-12"><h3 class="form-section">Danh sách Import</h3></div>
			<div class="col-md-12">
				<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<tr>
    						<th class="col-50">STT</th>
    						<th>Trạng thái</th>
                            <th>Ngày ra data</th>
    						<th>Tên</th>
    						<th>Điện thoại</th>
    						<th>Tên xe - Năm sản xuất</th>
    						<th>Ghi chú</th>
    						<th>Mã nhân viên MKT</th>
    						<th>Mã nhân viên Sale quản lý</th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php
    					$index = 0;
    					foreach ($this->sheetData AS $key => $val) { 
    						if((int)$val['D'] > 0) {
    							$index++;
    							$phone = $number->formatToData(trim($val['D']));
    							if(substr($phone, 0, 1) != '0') {
                                    $phone = '0'. $phone;
                                }
    					?>
    					<tr id="tr_<?php echo $index;?>" data-index="<?php echo $index;?>">
							<td><?php echo $index;?></td>
                            <td><a href="javascript:;" data-index="<?php echo $index;?>" class="btn btn-xs default">Import</a></td>
							<td><span class="date"><?php echo trim($val['B']);?></span></td>
							<td><span class="name"><?php echo trim($val['C']);?></span></td>
							<td><span class="phone"><?php echo $phone;?></span></td>
							<td><span class="note"><?php echo trim($val['E']);?></span></td>
                            <td><span class="content"><?php echo trim($val['F']);?></span></td>
                            <td><span class="marketer_id"><?php echo trim($val['G']);?></span></td>
                            <td><span class="sales_id"><?php echo trim($val['H']);?></span></td>
						</tr>
						<?php
    						}
    					} 
						?>
					</tbody>
    			</table>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
    <?php
    if(!empty($this->import) && !empty($this->sheetData)) {  
    ?>
    function startImportContact(index) {
        var item = '#tr_'+ index;
        if($(item).size() > 0) {
            var data = {
                'marketing_channel_id': $('select[name="marketing_channel_id"]').val(),
            };
            $(item +' span').each(function() {
                data[$(this).attr('class')] = $(this).text();
            });

            $.ajax({
                url: "<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import2'));?>",
                type: 'POST',
                data: data,
                beforeSend: function() {
                    $(item + ' .btn').html('Đang xử lý ...').removeClass('default').addClass('yellow');
                },
                success: function(result) {
                    setTimeout(function(){
                        $(item).removeClass('active');

                        if(result == 'Thành công') {
                            $(item + ' .btn').html(result).removeClass('yellow').addClass('green');
                        } 
                        else{
                            $(item + ' .btn').html(result).removeClass('yellow').addClass('red');
                        }

                        var index_next = parseInt(index) + 1;
                        startImportContact(index_next); 
                    }, 100);
                }
            });
        } else {
            alert('Import thành công');
        }
    }
    startImportContact(1);
    <?php
    }
    ?>
<?php $this->headScript()->captureEnd() ?>