<form action="#" class="frmData" name="frmData" method="POST">
    <div class="box_title">Đăng ký mua sản phẩm</div>
    <div class="box_content">
        <div class="row">
            <div class="col-md-12">
                <div class="form-group" id="input-name">
                    <input name="name" type="text" class="form-control" placeholder="Họ và tên">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group" id="input-phone">
                    <input name="phone" type="text" class="form-control" placeholder="Điện thoại">
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group" id="input-email">
                    <input name="email" type="text" class="form-control" placeholder="Email">
                </div>
            </div>
            <div class="col-md-12">
                <div class="btnSuccess">
                    <input type="submit" class="input-lg btn-blue" value="Đăng ký ngay">
                </div>
            </div>
        </div>
    </div>
</form>
