<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index', 'id' => $this->params['route']['id'])), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    // Set lại các giá trị của từng element
    $myForm->get('location_district_id')->setAttributes(array('data-parent' => $myForm->get('location_city_id')->getValue()));
    
    $elements = array(
        array('section' => 'Thông tin khách hàng', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('phone'), 'label' => 'Số điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('name'), 'label' => 'Họ và tên', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('sex'), 'label' => 'Giới tính', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('source_group_id'), 'label' => 'Nguồn liên hệ', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('source_known_id'), 'label' => 'Nguồn biết đến', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('location_city_id'), 'label' => 'Tỉnh thành', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('location_district_id'), 'label' => 'Quận huyện', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('email'), 'label' => 'Email', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('birthday'), 'label' => 'Ngày sinh', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('address'), 'label' => 'Địa chỉ nơi ở', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('facebook'), 'label' => 'Facebook', 'boxClass' => 'col-md-2'),
        array('div' => '', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('subject_id'), 'label' => 'Đối tượng', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('school_id'), 'label' => 'Trường', 'validate' => array('require' => true), 'boxClass' => 'col-md-2', 'boxId' => 'school_id'),
        array('element' => $myForm->get('major_id'), 'label' => 'Chuyên ngành', 'validate' => array('require' => true), 'boxClass' => 'col-md-2', 'boxId' => 'major_id'),
        array('element' => $myForm->get('note'), 'label' => 'Ghi chú', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
	<?php
	$date = new \ZendX\Functions\Date();
	if($date->diff(date('Y-m-d'), $this->event['public_date']) >= 0) {
	?>
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
	</div>
	<?php
	} else {
	    echo '<div class="page-content"><div class="alert alert-danger">Sự kiện đã kết thúc</div></div>';
	} 
	?>
</form>

<?php $this->headScript()->captureStart() ?>
    // Xử lý load tỉnh thành
	$('select[name="location_city_id"]').change(function() {
		var select = 'input[name="location_district_id"]';
		var parent = $(select).parent();
		$('.select2-container', parent).select2('val', '');
		$(select).attr('data-parent', $(this).val());
    });
    
    // Check phân loại
    function checkSubject(id) {
		if(id == '153897020539z686271u83') {
			$('#school_id').removeClass('hidden');
			$('#major_id').removeClass('hidden');
		} else {
		    $('#school_id').addClass('hidden');
			$('#major_id').addClass('hidden');
		}
    }
    var subject_id = '<?php echo $myForm->get('subject_id')->getValue(); ?>';
    if(subject_id) {
        checkSubject(subject_id);
    }
    $('select[name="subject_id"]').change(function() {
        checkSubject($(this).val());
    });
    
    // Kiểm tra thông tin khách hàng
    if($('input[name="phone"]').val()) {
        var val = $('input[name="phone"]').val().trim();
        checkContactToElement(val, null);
    }
    
    $('input[name="phone"]').blur(function() {
        var val = $(this).val().trim();
        checkContactToElement(val, 'element');
    });
    
    $('input[name="phone"]').keypress(function (event) {
		if(event.charCode == 13) {
			$('input[name="phone"]').blur();
		}
	});
<?php $this->headScript()->captureEnd() ?>