<?php
$myForm = $this->myForm;
$myForm->prepare();

$arrControl = array(
    array('name'       => 'save',
          'caption'    => 'Lưu',
          'link'       => 'javascript:;',
          'icon'       => 'fa-check',
          'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');',
                                'class'   => 'btn')),
    array('name'       => 'save-new',
          'caption'    => 'Lưu &amp; Mới',
          'link'       => 'javascript:;',
          'icon'       => 'fa-paste',
          'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');',
                                'class'   => 'btn')),
    array('name'       => 'save-close',
          'caption'    => 'Lưu &amp; Đóng',
          'link'       => 'javascript:;',
          'icon'       => 'fa-save',
          'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');',
                                'class'   => 'btn')),
    array('name'       => 'close',
          'caption'    => 'Hủy',
          'link'       => $this->url('routeAdmin/default', array('controller' => $this->params['controller'],
                                                                 'action'     => 'index')),
          'onclick'    => '',
          'icon'       => 'fa-times',
          'attributes' => array('class' => 'btn')),
);

$elements = array(
    array('section'  => 'Thông tin chung',
          'boxClass' => 'col-md-12'),

    array('element'  => $myForm->get('year'),
          'label'    => 'Năm',
          'validate' => array('require' => true),
          'boxClass' => 'col-md-2'),

    array('element'  => $myForm->get('month'),
          'label'    => 'Tháng',
          'validate' => array('require' => true),
          'boxClass' => 'col-md-2'),

    array('element'  => $myForm->get('user_id'),
          'label'    => 'Nhân viên',
          'validate' => array('require' => true),
          'boxClass' => 'col-md-2'),

    array('element'  => $myForm->get('id'),
          'validate' => array('require' => true)),
);
$xhtml    = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm"
      class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption; ?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array('control' => $arrControl)); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->render(); ?>
    <?php echo @$this->xViewElementErrors($elements); ?>

    <div class="page-content">
        <div class="row">
            <?php echo $xhtml; ?>
        </div>
        <div class="row">
            <div class="col-md-12"><h3 class="form-section">Chi tiết chấm công</h3></div>
            <div class="col-md-12">
                <?php
                if (!empty($this->params['data']['control-action'])) {
                    $params = $this->params['data']['params'];
                } else {
                    $params = !empty($this->item['params']) ? unserialize($this->item['params']) : array();
                }
                ?>
                <div class="table-manager" id="table-manager" style="margin-bottom: 50px;">
                    <div>
                        <table class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <?php
                                        for ($i = 1; $i <= $this->number_day; $i++){
                                            ?>
                                            <th class="text-center" style="min-width: 70px;"><?php echo $i; ?></th>
                                            <?php
                                        }
                                    ?>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <?php
                                        for ($i = 1; $i <= $this->number_day; $i++){
                                            $i = $i < 10 ? '0'.$i : $i;
                                            ?>
                                            <td class="column"">
                                            <input type="text"  autocomplete="off" name="params[<?php echo $i; ?>]" value="<?php echo $params[$i]; ?>" class="form-control input-xs">
                                            </td>
                                            <?php
                                        }
                                    ?>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>