<?php
$myForm = $this->myForm;
$myForm->prepare();

$arrControl = array(
    array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
    array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
    array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
    array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
);

$elementsTop = array(
    array('section' => 'Thông tin nhà cung cấp', 'boxClass' => 'col-md-12'),
    array('element' => $myForm->get('customer_id'), 'label' => 'Nhà cung cấp', 'validate' => array('require' => true), 'boxClass' => 'col-md-6'),
    array('element' => $myForm->get('inventory_id'), 'label' => 'Kho nhập hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-6'),
    array('element' => $myForm->get('note'), 'label' => 'Mô tả', 'boxClass' => 'col-md-12'),
);

$xhtmlTop = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsTop);

$elementsBottom = array(
    array('section' => 'Thành tiền hóa đơn', 'boxClass' => 'col-md-12'),
    array('element' => $myForm->get('price_total'), 'label' => 'Tổng tiền hàng', 'boxClass' => 'col-md-4'),
    array('element' => $myForm->get('paid_cash'), 'label' => 'Trả tiền mặt', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
    array('element' => $myForm->get('paid_transfer'), 'label' => 'Chuyển khoản', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
    array('element' => $myForm->get('discount'), 'label' => 'giảm giá', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
    array('element' => $myForm->get('amount_owed'), 'label' => 'Nợ cũ', 'boxClass' => 'col-md-4'),
    array('element' => $myForm->get('new_debt'), 'label' => 'Nợ lại', 'boxClass' => 'col-md-4'),
    array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
);
$xhtmlBottom = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsBottom);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
    <?php echo @$this->xViewElementErrors($elementsTop);?>
    <?php echo @$this->xViewElementErrors($elementsBottom);?>

    <div class="page-content">
        <div class="row">
            <div class="col-md-6">
                <?php echo $xhtmlTop;?>
            </div>
            <div class="col-md-6">
                <?php echo $xhtmlBottom;?>
            </div>
            <div class="col-md-10">
                <p class="text-alert"></p>
                <?php
                if(!empty($this->check_product_id)){
                    ?>
                    <div class="alert alert-block alert-danger">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <p><?php echo $this->check_product_id; ?></p>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12 form-section" style="padding: 0px;">
                    <div>
                        <span class="title-load-product">Sản phẩm</span>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group" style="margin-bottom: 5px;">
                            <select name="filter_products_type" class="form-control select2 select2_basic" style="display: none;">
                                <option value="">- Chọn nhóm hàng -</option>
                                <?php foreach($this->products_type as $key => $value){?>
                                    <option value="<?=$key?>"><?=$value?></option>
                                    <?php
                                } ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="control-element">
                                <input type="text" name="filter_keyword" class="form-control" value="" placeholder="Nhập tên sản phẩm" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12" style="padding: 0px;">
                    <div id="loadProducts">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-6">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="form-section">Danh sách sản phẩm</h3>
                    <div class="contract_product table-scrollable" style="min-height: 400px" >
                        <table class="table table-striped table-bordered table-hover table-product">
                            <thead>
                            <tr>
                                <th width="100px" class="text-center">Mã SP</th>
                                <th width="150px" class="text-center">Tên SP</th>
                                <th width="80px" class="text-center">S.lượng</th>
                                <th width="150px" class="text-center">Giá tiền</th>
                                <th width="150px" class="text-center">Thành tiền</th>
                                <th width="30px" class="text-center">Xóa</th>
                            </tr>
                            </thead>
                            <tbody class="product_body list-product-contract">
                            <?php
                            if(!empty($this->productList)){
                                $number   = new \ZendX\Functions\Number();
                                $productList = $this->productList;
                                $productHtml = '';
                                for($i = 0; $i < count($productList['products_id']); $i++) {
                                    $check_number = empty($productList['quantity'][$i]) ? 'has-error' : "";
                                    $check_price = empty($productList['price'][$i]) ? 'has-error' : "";

                                    $productHtml .= '<tr data-id="'.$productList['products_id'][$i].'">
                                                        <td width="100px" class="text-bold text-red text-middle">'.$productList['code'][$i].'</td>
                                                        <td width="100px" class="text-middle">'.$productList['name'][$i].'</td>
                                                        <td class="numbers '.$check_number.'"><input class="form-control text-right money" type="number" name="products_list[quantity][]" value="'.$productList['quantity'][$i].'" min="1"></td>
                                                        <td class="price text-middle text-right box-price '.$check_price.'">
                                                            <input class="form-control text-right money base_price " name="products_list[price][]" type="text" value="'.$productList['price'][$i].'" min="0">
                                                        </td>
                                                        <td class="total"><input class="form-control text-right" type="text" name="products_list[total][]" value="'.$productList['total'][$i].'" readonly></td>
                                                        <td class="hidden">
                                                            <input class="form-control" type="text" name="products_list[products_id][]" value="'.$productList['products_id'][$i].'">
                                                            <input class="form-control" type="text" name="products_list[name][]" value="'.$productList['name'][$i].'">
                                                            <input class="form-control" type="text" name="products_list[code][]" value="'.$productList['code'][$i].'">
                                                        </td>
                                                       
                                                        <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
                                                    </tr>';
                                }
                                echo $productHtml;
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<link href="/public/template/backend/css/contract.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">

<?php $this->headScript()->captureStart() ?>

$("input[name='filter_keyword']").on('keydown', function (e) {
if (e.key === 'Enter' || e.keyCode === 13) {
var data = {filter_products_type: $(`select[name="filter_products_type"]`).val(), filter_keyword: $(`input[name="filter_keyword"]`).val(), filter_warehouse: $(`select[name="inventory_id"]`).val()};
load_action('#loadProducts', '<?php echo $this->url('routeAdmin/default',array('controller' => 'api', 'action' => 'loadProductsWarehouseInput'));?>', data);
return false;
}
});

$(`select[name="filter_products_type"], select[name="customer_type_id"], select[name="inventory_id"]`).change(function () {
var data = {filter_products_type: $(`select[name="filter_products_type"]`).val(), filter_keyword: $(`input[name="filter_keyword"]`).val(), filter_warehouse: $(`select[name="inventory_id"]`).val()};
load_action('#loadProducts', '<?php echo $this->url('routeAdmin/default',array('controller' => 'api', 'action' => 'loadProductsWarehouseInput'));?>', data);
});


<?php $this->headScript()->captureEnd() ?>


<?php $this->HeadScript()->appendFile('/public/template/backend/js/contracts/warehouse-input.js','text/javascript');?>



