<?php
    $userInfo = new \ZendX\System\UserInfo();


    $myForm = $this->myForm;
    $myForm->prepare();

    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );

    // Set lại các giá trị của từng element
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'id' => 'form_section', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('code'), 'label' => 'Mã', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('name'), 'label' => 'Tên kho', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('phone'), 'label' => 'Điện thoại ', 'validate' => array('require' => false), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('note'), 'label' => 'Mô tả', 'validate' => array('require' => false), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('address'), 'label' => 'Địa chỉ', 'validate' => array('require' => false), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('ordering'), 'label' => 'Thứ tự', 'validate' => array('require' => true), 'boxClass' => 'col-md-1'),
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>

    <?php echo $this->flashMessenger()->render();?>
    <?php echo @$this->xViewElementErrors($elements);?>

    <div class="page-content">
    	<div class="row" id="info_data">
			<?php echo $xhtml;?>
		</div>
	</div>
</form>
