<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $elements = array(
        array('element' => $myForm->get('status_acounting_id'), 'label' => 'Trạng thái', 'boxClass' => 'col-md-12', 'validate' => array('require' => true)),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true))
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
        <div class="row">
            <div class="col-md-12">
                <p id="alert-returned" style="display:none; font-weight: 700; font-size: 16px; color: red;" class="alert alert-warning">Bạn đã chọn trạng thái Đã nhận hoàn. Vui lòng kiểm tra kỹ trước khi lưu. Trạng thái này sau khi lưu sẽ không thể sửa lại.</p>
            </div>
        </div>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>

<script type="text/javascript">
    $('#adminFormModal [name="status_acounting_id"]').change(function(){
        if (this.value == 'da-nhan-hoan') {
            $('#alert-returned').slideDown();
        } else {
            $('#alert-returned').slideUp();
        }
    });
</script>