<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    $userInfo = new \ZendX\System\UserInfo();
    $user_info = $userInfo->getUserInfo();
    $can_edit = in_array(ADMIN,explode(',',$user_info['permission_ids'])) || in_array(SYSTEM,explode(',',$user_info['permission_ids'])) || in_array(ACCOUNTING,explode(',',$user_info['permission_ids']));

    $options = unserialize($this->contract['options']);

    $elementsBottom = array(
        array('div' => '', 'boxClass' => 'col-xs-12'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true))
    );
    $xhtmlBottom = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsBottom);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
    <?php if (!$can_edit) { ?>
    <p class="alert alert-danger">Không thể sửa đơn đã được cập nhật trạng thái Sản xuất.</p>
    <?php } else { ?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
        <div class="contract_product table-scrollable">
            <?php
                if(!empty($this->check_product_id)){
                    ?>
                    <div class="alert alert-block alert-danger">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <p><?php echo $this->check_product_id; ?></p>
                    </div>
                    <?php
                }
            ?>

            <table class="table table-striped table-bordered table-hover table-product" style="min-width:1920px">
                <thead>
                    <tr>
                        <th width="200px">Sản phẩm</th>
                        <th width="150px">Hàng có sẵn</th>
                        <th width="230px">Tên xe - năm sản xuất</th>
                        <th width="200px">Màu thảm</th>
                        <th width="200px">Màu rối</th>
                        <th width="200px">Loại sản phẩm</th>
                        <th class="hidden">Giá vốn mặc định</th>
                        <th>Số lượng</th>
                        <th width="">Giá niêm yết</th>
                        <th>Giá bán</th>
                        <th>Giảm giá</th>
                        <th>VAT</th>
                        <th>Thành tiền</th>
                        <th>Giá vốn</th>
                    </tr>
                </thead>
                <tbody class="product_body">
                <?php
                $numbers = 0;
                $total_price = 0;
                if (count($options['product']) > 0) {
                    foreach ($options['product'] as $product_detail){
                        $numbers = $numbers + $product_detail['numbers'];
                        $total_price = $total_price + $product_detail['total'];
                        if (!empty($product_detail['sale_price'])) {
                            $salePrice = $product_detail['sale_price'];
                        } else {
                            $salePrice = 0;
                        }

                        if (!empty($product_detail['vat'])) {
                            $vat = $product_detail['vat'];
                        } else {
                            $vat = 0;
                        }
                        ?>
                        <tr class="product_row ">
                            <input class="form-control" type="hidden" name="contract_product[key_id][]" value="<?php echo $product_detail['key_id']; ?>">
                            <td class="products">
                                <select class="select-product select2 select2_basic form-control" onchange="changeOption(this)" disabled name="contract_product[product_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php 
                                        foreach ($this->product_type as $value) {
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-product="<?php echo $value['id']; ?>" data-price="<?php echo $value['price']; ?>" <?php echo ($product_detail['product_id'] == $value['id'])?'selected': false;?>><?php echo $value["name"] ?></option>
                                    <?php
                                        }
                                    ?>
                                </select>

                            </td>
                            <td class="stock"><input class="form-control" type="text" name="contract_product[stock][]" readonly value="<?php echo $product_detail['stock']; ?>"></td>
                            <td class="product-name"><input class="form-control" type="text" name="contract_product[product_name][]" title="<?php echo $product_detail['product_name']; ?>" readonly value="<?php echo $product_detail['product_name']; ?>"></td>
                            <td class="carpet-color">
                                <select class="select-product select2 select2_basic form-control" disabled onchange="changeOption(this)" name="contract_product[carpet_color_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php 
                                    foreach ($this->carpet_color as $value) {  
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-carpet-color="<?php echo $value['id']; ?>" data-price="<?php echo $value['price']; ?>" <?php echo ($product_detail['carpet_color_id'] == $value['id'])?'selected': false;?>><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="tangled-color">
                                <select class="select-product select2 select2_basic form-control" disabled ?> onchange="changeOption(this)" name="contract_product[tangled_color_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php 
                                    foreach ($this->tangled_color as $value) {  
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-tangled-color="<?php echo $value['id']; ?>" data-price="<?php echo $value['price']; ?>" <?php echo ($product_detail['tangled_color_id'] == $value['id'])?'selected': false;?>><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="flooring">
                                <select class="select-product select2 select2_basic form-control" disabled onchange="changeOption(this)" name="contract_product[flooring_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php 
                                    foreach ($this->flooring as $value) {  
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-flooring="<?php echo $value['id']; ?>" data-price="<?php echo $value['price']; ?>" <?php echo ($product_detail['flooring_id'] == $value['id'])?'selected': false;?>><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="numbers"><input class="form-control text-right" readonly type="text" onchange="changeOption(this)" name="contract_product[numbers][]" value="<?php echo number_format($product_detail['numbers']); ?>" min="1"></td>
                            <td class="listed_price"><input class="form-control text-right" readonly type="text" name="contract_product[listed_price][]" value="<?php echo number_format($product_detail['listed_price']); ?>" min="1"></td>
                            <td class="price"><input class="form-control text-right money" readonly type="text" name="contract_product[price][]" min="0" value="<?php echo number_format($product_detail['price']); ?>"></td>
                            <td class="sale_price"><input class="form-control text-right money" readonly type="text" name="contract_product[sale_price][]" readonly value="<?php echo number_format($salePrice); ?>" min="0"></td>
                            <td class="vat"><input class="form-control text-right money" readonly type="text" name="contract_product[vat][]" value="<?php echo number_format($vat); ?>" min="0"></td>
                            <td class="total"><input class="form-control text-right"  type="text" name="contract_product[total][]" readonly value="<?php echo number_format($product_detail['total']); ?>"></td>
                            <td class="icon_delete"><input class="form-control text-right money" type="text" name="contract_product[capital_default][]" value="<?php echo number_format($product_detail['capital_default']); ?>"></td>
                        </tr>
                    <?php
                    }
                } else {
                ?>
                <tr align="center">
                    <td colspan="5" >Không có sản phẩm</td>
                </tr>
                <?php
                }
                ?>
                </tbody>
                <tfoot>
                    <tr>
                        <td>Tổng</td>
                        <td></td>
                        <td></td>
                        <td><?php //echo $numbers; ?></td> 
                        <td></td>
                        <td></td> 
                        <td></td> 
                        <td></td> 
                        <td></td> 
                        <td></td> 
                        <td></td>
                        <td class="total_price text-right" style="padding: 10px 18px;"><?php echo number_format($total_price); ?></td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
        </div>

        <div class="row">
            <?php echo $xhtmlBottom;?>
        </div>
    </form>
<?php } ?>
<?php
if(!empty($this->contract['status_guarantee_id'])) {
    echo '<style>.code-old{display:block}</style>';
}
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
    <?php if ($can_edit) { ?>
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
    <?php } ?>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>

<style>
.custom-modal {
    width: 90% !important;
    margin-left: -45% !important;
}

#form-product-return {
    padding: 5px 0 10px 0;
    overflow: hidden;
}
#form-product-return input[type="text"] {
    float: left;
    padding: 4px 5px;
    border-right: 0px;
    border: 1px #ccc solid;
    font-size: 14px;
}
#form-product-return input[type="button"] {
    float: left;
    padding: 5px 10px 3px 10px;
    border-left: 0;
    border: 1px #5cb85c solid;
    background: #5cb85c;
    font-size: 14px;
    color: #fff;
}
</style>
<script>
    format_to_money();
</script>
