<?php
    $this->_userInfo = new \ZendX\System\UserInfo();
    $curent_user = $this->_userInfo->getUserInfo();
    $permission_ids = explode(',', $curent_user['permission_ids']);
$encode_phone = explode(',', $curent_user['encode_phone']);
$phone_code = true;
if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || !in_array('accountant_contract', $encode_phone)) {
    $phone_code = false;
}

    $is_system = false;
    $is_admin = false;
    $is_accounting = false;

    if(in_array(SYSTEM, $permission_ids)){
        $is_system = true;
    }
    if(in_array(ADMIN, $permission_ids)){
        $is_admin = true;
    }
    if(in_array(ACCOUNTING, $permission_ids)){
        $is_accounting = true;
    }

    $dateFormat = new \ZendX\Functions\Date();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_begin'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_end'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_sale_branch'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_sale_group'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_user'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_shipper_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_production_type_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

        array('element' => $myForm->get('filter_status_type'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_status'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_owed'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),

        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th width="30" class="table-checkbox"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th width="30"></th>';
    $xhtmlHead .= '<th width="70">Công cụ</th>';
    $xhtmlHead .= '<th width="180">Trạng thái</th>';
    $xhtmlHead .= '<th width="120">Mã vận đơn</th>';
    $xhtmlHead .= '<th width="90">Mã số đơn</th>';
    $xhtmlHead .= '<th width="80">Ngày</th>';
    $xhtmlHead .= '<th width="150">Nhân viên</th>';
    $xhtmlHead .= '<th width="150">Tên khách hàng</th>';
    $xhtmlHead .= '<th width="90">Điện thoại</th>';
    $xhtmlHead .= '<th width="150">Địa chỉ</th>';
//    $xhtmlHead .= '<th width="80">VAT</th>';
    $xhtmlHead .= '<th width="80">Tổng tiền</th>';
    $xhtmlHead .= '<th width="150">Giảm trừ doanh thu</th>';
    $xhtmlHead .= '<th width="80">Công nợ</th>';
    $xhtmlHead .= '<th width="200">Sản phẩm</th>';
    $xhtmlHead .= '<th width="100">Số lượng</th>';
    // $xhtmlHead .= '<th width="100">Loại thảm</th>';
    $xhtmlHead .= '<th width="200">Tên xe - Năm sản xuất</th>';
    // $xhtmlHead .= '<th width="100">Trạng thái</th>';
    $xhtmlHead .= '<th width="150">Ghi chú sales</th>';
    $xhtmlHead .= '<th width="150">Ghi chú sản xuất</th>';
//    $xhtmlHead .= '<th width="100">Hàng hoàn</th>';
//    $xhtmlHead .= '<th width="100">Giảm giá</th>';
    $xhtmlHead .= '<th width="140">NV giao hàng</th>';
    $xhtmlHead .= '<th width="140">Người quản lý</th>';
    $xhtmlHead .= '<th width="140">Người tạo</th>';
	$xhtmlHead .= '</tr>';
    
    // Danh sách
    $xhtmlItems = '';
    if($this->items->count() > 0) {
    	$stt = 0;
        foreach ($this->items AS $key => $item) {
        	$stt++;
        	$cid                    = @$this->xFormInput('cid[]', $item->id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        	
        	$id                     = $item->id;
        	$code                   = $item->code;
            $date                   = $dateFormat->formatToView($item->date);
            $contact_phone          = $item->contact_phone;
            $contact_phone          = $phone_code && $item->contact_phone ? substr_replace($item->contact_phone, "***", 4, 3) : $item->contact_phone;
            $contact_name           = $item->contact_name;
            $vat                    = number_format($item->vat);
            $price_promotion        = number_format($item->price_promotion);
            $price_reduce_sale      = number_format($item->price_reduce_sale);
            $price_total            = $item->price_total;
            $price_paid             = $item->price_paid;
            $price_accrued          = $item->price_accrued;
            $price_owed             = $item->price_owed > 0 ? $item->price_owed : 0;
            $user_name              = $item->user_id ? $this->user[$item->user_id]['name'] : '';
            $transport              = $item->transport_id ? $this->transport[$item->transport_id]['name'] : '';
            $type_of_carpet         = $item->type_of_carpet_id ? $this->type_of_carpet[$item->type_of_carpet_id]['name'] : '';
            $production_department  = $item->production_department_type ? $this->production_department[$item->production_department_type]['name'] : '';
            $bill_code              = $item->bill_code;
            $product_return         = $item->product_return;
            $shipper_id             = $this->shipper[$item->shipper_id];
            $lock                   = $item->lock ? '<i class="fa fa-lock" aria-hidden="true" style="color: #bbb; padding-top: 3px;"></i>' : '';

            $status_prouduct        = $item->production_department_type ? $this->status_product[$item->production_department_type]['name'] : '';
            $status_check           = $item->status_check_id ? $this->status_check[$item->status_check_id]['name'] : '';
            $status_acccounting     = $item->status_acounting_id ? $this->status_accounting[$item->status_acounting_id]['name'] : '';
            if(!empty($status_acccounting)){
                $status = $status_acccounting;
            }
            elseif (!empty($status_check)){
                $status = $status_check;
            }
            else{
                $status = $status_prouduct;
            }
            $status = 'Sản xuất: '.$status_prouduct.'<br>'.'Giục đơn: '.$status_check.'<br>'.'Kế toán: '.$status_acccounting;

            $sale_group_id          = $item->sale_group_id ? '<br>'. $this->sale_group[$item->sale_group_id]['name'] : '';
            $sale_branch_id         = $item->sale_branch_id ? ' - '. $this->sale_branch[$item->sale_branch_id]['name'] : '';
            $created                = $dateFormat->formatToView($item->created, 'd/m/Y H:i:s');

            $user                   = $this->user[$item->user_id]['name'];
            $sale_group_user        = $this->user[$item->user_id]['sale_group_id'] ? '<br>'.  $this->sale_group[$this->user[$item->user_id]['sale_group_id']]['name'] : '';
            $sale_branch_user       = $this->user[$item->user_id]['sale_branch_id'] ? ' - '.  $this->sale_branch[$this->user[$item->user_id]['sale_branch_id']]['name'] : '';

            $created_by             = $this->user[$item->created_by]['name'];
            $sale_group_created_by  = $this->user[$item->created_by]['sale_group_id'] ? '<br>'.  $this->sale_group[$this->user[$item->created_by]['sale_group_id']]['name'] : '';
            $sale_branch_created_by = $this->user[$item->created_by]['sale_branch_id'] ? ' - '.  $this->sale_branch[$this->user[$item->created_by]['sale_branch_id']]['name'] : '';

            $order_type             = $item->status_store ? 'Đơn cửa hàng' : 'Đơn thường';

            $options                = $item->options ? unserialize($item['options']) : array();
            $contact_options        = $item->contact_options ? unserialize($item['contact_options']) : array();
            $address = !empty($options['contract_received']['address']) ? $options['contract_received']['address'] : $contact_options['address'];

            $color_price_owed       = '';
            // Link Action
            $linkView               = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => 'contract', 'action' => 'view')) .'\', {\'id\': \''. $id .'\'});';
            $linkEdit               = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit')) .'\', {\'id\': \''. $id .'\'});';
            $linkEditReduce         = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit-reduce')) .'\', {\'id\': \''. $id .'\'});';
            $linkEditStatus         = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit-status')) .'\', {\'id\': \''. $id .'\'});';
            $linkDelete             = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'delete', 'id' => $id));
            $linkBillAdd            = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'bill-add')) .'\', {\'id\': \''. $id .'\'});';
            $linkContactEdit        = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'contact-edit')) .'\', {\'id\': \''. $item['contact_id'] .'\'});';
            $linkEditCostPrice      = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit-cost-price')) .'\', {\'id\': \''. $id .'\'});';
            $linkReturnConfirm      = 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'return')) .'\', {\'id\': \''. $id .'\'});';

            // Control Action
            $controlView            = $this->linkAdminHtml($linkView, array('type' => 'icon', 'title' => 'Xem chi tiết', 'class' => 'btn btn-xs blue', 'icon' => 'fa fa-info'));

            $menu_edit_status = '';
//            if($is_system || $is_admin){
                $menu_edit_status = '<li><a href="javascript:;" onclick="'. $linkEditStatus .'"><i class="fa fa-pencil-square-o"></i> Sửa trạng thái</a></li>';
//            }
            $menu_edit_code_price = '';
            if($is_system || $is_admin || $is_accounting) {
                $menu_edit_code_price = $item->status_check_id == 'thanh-cong' ? '<li><a href="javascript:;" onclick="' . $linkEditCostPrice . '"><i class="fa fa-edit"></i> Sửa giá vốn</a></li>' : '';
            }
            
            $controls               = $controlView;
            $controls              .= '<div class="btn-group">
    									<button class="btn green btn-xs dropdown-toggle" type="button" data-toggle="dropdown">
    									   <i class="fa fa-cog"></i> <i class="fa fa-angle-down"></i>
    									</button>
    									<ul class="dropdown-menu" role="menu">
    										<li><a href="javascript:;" onclick="'. $linkBillAdd .'"><i class="fa fa-money"></i> Thêm hóa đơn</a></li>
    										<li><a href="javascript:;" onclick="'. $linkEditReduce .'"><i class="fa fa-money"></i> Thêm giảm trừ doanh thu</a></li>
    										'.$menu_edit_status.'
    										'.$menu_edit_code_price.'
    										<li><a href="javascript:;" onclick="'. $linkReturnConfirm .'"><i class="fa fa-reply"></i> Xác nhận đã nhận hoàn</a></li>
    									</ul>
                                    </div>';

            if (!empty($options['contact_info'])) {
                $contact_phone          = $options['contact_info']['phone'];
                $contact_name           = $options['contact_info']['name'];
            }
            $countProduct = count($options['product']);
            if ($countProduct > 0) {
                $rowSpan = 'rowspan="'.$countProduct.'"';
            } else {
                $rowSpan = '';
            }

            $color_text_row = '';
            if($item->status_acounting_id == STATUS_CONTRACT_ACOUNTING_MONEY){
                $color_text_row = 'style ="background-color: #9edea1"';
            }
            if($item->status_acounting_id == STATUS_CONTRACT_ACOUNTING_RETURN){
                $color_text_row = 'style ="background-color: #e29494"';
            }

            $xhtmlItems .= '<tr id="tr_'. $id .'" data-id="'. $id .'"'.$color_text_row.'>
    							<td '.$rowSpan.'>'. $cid .'</td>
    							<td '.$rowSpan.'>'. $lock .'</td>
                                <td '.$rowSpan.' class="controls">'. $controls .'</td>
                                <td '.$rowSpan.'>'. $status .'</td>
                                <td '.$rowSpan.'>'. $bill_code .'</td>
    							<td '.$rowSpan.' class="text-bold">'. $code .'</td>
    							<td '.$rowSpan.'>'. $date .'</td>
    							<td '.$rowSpan.'>'. $user_name .'</td>
    							<td '.$rowSpan.'>'. $contact_name .'</td>
    							<td '.$rowSpan.'>'. $contact_phone .'</td>
    							<td class="av-read" '.$rowSpan.'>'. $address .'</td>
    							<td '.$rowSpan.'>'. number_format($price_total) .'</td>
    							<td '.$rowSpan.'>'. $price_reduce_sale .'</td>
    							<td '.$rowSpan.'>'. number_format($price_owed) .'</td>';
            if (count($options['product']) > 0) {
                foreach($options['product'] as $key => $item_product) {

                    if ($key == 0) :
                     $productName = $item->kov_status ? $this->kovProduct[$item_product['product_id']]['fullName'] : $this->product[$item_product['product_id']]['name'];
                    $carpet_color           = $item_product['carpet_color_id'] ? $this->carpet_color[$item_product['carpet_color_id']]['name'] : '';
                    $tangled_color          = $item_product['tangled_color_id'] ? $this->tangled_color[$item_product['tangled_color_id']]['name'] : '';
                    $flooring               = $item_product['flooring_id'] ? $this->flooring[$item_product['flooring_id']]['name'] : '';
                    $xhtmlItems .= '
                                    <td>'. $productName .'  '.$carpet_color.'  '.$tangled_color.'  '.$flooring.'</td>
                                    <td class="text-center">' . (new \ZendX\Functions\StringHelper)->badgeCount($item_product['numbers']?:1) . '</td>
                                    <td class="av-read" title = "'.$item_product['product_name'].'">'. $item_product['product_name'] .'</td>
                                    ';
                    endif;
                }
            } else {
                $xhtmlItems .= '<td></td>
    							<td></td>
    							<td></td>
    							<td></td>
                                <td></td>';
            }
            $xhtmlItems .= '
    							<td class="av-read" '.$rowSpan.'>'. $options['sale_note'] .'</td>
    							<td class="av-read" '.$rowSpan.'>'. $options['production_note'] .'</td>
    							<td '.$rowSpan.'>'. $shipper_id .'</td>
							    <td '.$rowSpan.'>'. $user . $sale_group_user . $sale_branch_user .'</td>
							    <td '.$rowSpan.'>'. $created_by . $sale_group_created_by . $sale_branch_created_by .'</td>
                            </tr>';
            if (count($options['product']) > 0) {
                foreach($options['product'] as $key => $item_product) {
                    if ($key > 0) :
                    $productName = $item->kov_status ? $this->kovProduct[$item_product['product_id']]['fullName'] : $this->product[$item_product['product_id']]['name'];
                    $carpet_color           = $item_product['carpet_color_id'] ? $this->carpet_color[$item_product['carpet_color_id']]['name'] : '';
                    $tangled_color          = $item_product['tangled_color_id'] ? $this->tangled_color[$item_product['tangled_color_id']]['name'] : '';
                    $flooring               = $item_product['flooring_id'] ? $this->flooring[$item_product['flooring_id']]['name'] : '';
                    $xhtmlItems .= '<tr '.$color_text_row.'>
                                    <td>'. $productName .'  '.$carpet_color.'  '.$tangled_color.'  '.$flooring.'</td>
                                    <td class="text-center">' . (new \ZendX\Functions\StringHelper)->badgeCount($item_product['numbers']?:1) . '</td>
                                    <td class="av-read" title = "'.$item_product['product_name'].'">'. $item_product['product_name'] .'</td>
                                    </tr>';
                    endif;
                }
            }
        }
    }
    $blank = "'blank'";
    // Control
    $arrControl = array(
        array( 'name' => 'import', 'caption' => 'Import trạng thái', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import-status')), 'icon' => 'fa fa-upload', 'attributes' => array( 'onclick' => '', 'class' => 'btn' ) ),
        // array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'add')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => '', 'class' => 'btn' ) ),
        array( 
            'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' ), 
            'children' => array( 
                array( 'name' => 'import', 'caption' => 'Nhập thanh toán từ giao vận', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'import-from-shipping')), 'icon' => 'fa fa-usd'),
//                array(
//                        'name' => 'return',
//                        'caption' => 'Xác nhận - Đã nhận hoàn',
//                        'link' => 'javascript:;',
//                        'icon' => 'fa fa-reply',
//                        'attributes' => array(
//                                'onclick' => 'javascript:updateItem(\'return\', \'Trạng thái đơn hàng chỉ được cập nhật một lần! <br> Bạn có chắc chắn muốn cập nhật đơn hàng về trạng thái: Đã nhận hoàn ?\');',
//                                'title' => 'Cập nhật trạng thái đơn hàng đã chọn thành trạng thái: Đã nhận hoàn',
//                        ),
//                ) ,
                array( 'name' => 'print-ship', 'caption' => 'In Hóa đơn thanh toán', 'link' => 'javascript:;',  'icon' => 'fa-print', 'attributes' => array( 'onclick' => 'javascript:contractPrint('.$blank.');') ),

//                array(
//                    'name' => 'cancel',
//                    'caption' => 'Xác nhận - Hủy không gửi',
//                    'link' => 'javascript:;',
//                    'icon' => 'fa fa-times',
//                    'attributes' => array(
//                        'onclick' => 'javascript:updateItem(\'cancel\', \'Trạng thái đơn hàng chỉ được cập nhật một lần! <br> Bạn có chắc chắn muốn cập nhật đơn hàng về trạng thái: Hủy không gửi ?\');',
//                        'title' => 'Cập nhật trạng thái đơn hàng đã chọn thành trạng thái: Hủy không gửi',
//                    ),
//                ) ,
            ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable table-fixed">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
        	?>
    	</div>
	</div>
</form>
    
<?php $this->headScript()->captureStart() ?>
    <!-- resize_col_table('#table-manager'); -->
<?php $this->headScript()->captureEnd() ?>