<?php
    $myForm = $this->myForm;
    $myForm->prepare();

    $elements = array(
        array('element' => $myForm->get('product_id'), 'label' => 'Sản phẩm', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('group_carpet_color_id'), 'label' => 'Nhóm màu thảm', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('group_tangled_color_id'), 'label' => 'Nhóm màu rối', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('flooring_id'), 'label' => 'Loại sản phẩm', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('price'), 'label' => 'Giá niêm yết', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('percenter'), 'label' => '% Khuyến mãi', 'validate' => array('require' => false), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true))
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>