<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần import dữ liệu <a href="'. URL_FILES .'/template/Mau_nhap_kho_hang_co_san.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => '.', 'boxClass' => 'col-md-1'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->results)) {
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<tr>
            					    <th class="col-80">Trạng thái</th>
            						<th class="col-50 text-center">STT</th>
            						<th>Sản phẩm</th>
            						<th>Kho KOV</th>
            						<th>Chi nhánh CRM</th>
            						<th>Mã đơn hàng</th>
            						<th>Tên xe - năm sản xuất</th>
            						<th>Số lượng</th>
            					</tr>
            				</thead>
            				<tbody>
            					<?php
                                $xhtmlBody = '';
            					foreach ($this->results AS $key => $val) {
            					    $color = $val['status'] == 'Hoàn thành' ? 'class="text-green"' : 'class="text-red"';
                                    $xhtmlBody .= '<tr>
                                                        <td '.$color.'>'.$val['status'].'</td>
                                                        <td>'.($key+1).'</td>
                                                        <td>'.$val['productId'].'</td>
                                                        <td>'.$val['branchId'].'</td>
                                                        <td>'.$val['sale_branch_id'].'</td>
                                                        <td>'.$val['contract_code'].'</td>
                                                        <td>'.$val['name_year'].'</td>
                                                        <td>'.$val['quantity'].'</td>
                                                    </tr>';
                                }
            					echo $xhtmlBody
            					?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>