<?php 
    $myForm = $this->myForm;
    $myForm->prepare();

    $string = new \ZendX\Functions\Gid();
    $random = $string->random();
    
    $myForm->get('sale_group_id')->setAttributes(array('data-parent' => $myForm->get('sale_branch_id')->getValue()));
    if(!empty($this->params['ssFilter']['sale_group_id'])) {
        $myForm->get('sale_group_id')->setAttributes(array('data-text-label' => $this->saleGroup[$this->params['ssFilter']['sale_group_id']]['name']));
    }

    $this->_userInfo = new \ZendX\System\UserInfo();
    $curent_user = $this->_userInfo->getUserInfo();
    $permission_ids = explode(',', $curent_user['permission_ids']);
    if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || in_array(MANAGER, $permission_ids)){
        $elements = array(
            array('element' => $myForm->get('date_begin'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('date_end'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('code'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('paid_cost'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('sale_branch_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('sale_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//            array('element' => $myForm->get('filter_status_type'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_status_sale'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_status_check'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_status_accounting'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        );
    }
    elseif(in_array(GDCN, $permission_ids)){
        $elements = array(
            array('element' => $myForm->get('date_begin'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('date_end'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('code'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('paid_cost'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//            array('element' => $myForm->get('sale_branch_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('sale_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
//            array('element' => $myForm->get('filter_status_type'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_status_sale'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_status_check'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_status_accounting'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        );
    }
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);


$arrControl = array(
    array(
        'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' ),
        'children' => array(
            array( 'name' => 'hidden', 'caption' => 'Đã thanh toán giá vốn', 'link' => 'javascript:;', 'icon' => 'fa fa-lock', 'attributes' => array('onclick'=>'javascript:contractLock(\'paidCost\');')),
            array( 'name' => 'hidden', 'caption' => 'Chưa thanh toán giá vốn', 'link' => 'javascript:;', 'icon' => 'fa fa-unlock-alt', 'attributes' => array('onclick'=>'javascript:contractLock(\'noPaidCost\');')),
            array( 'name' => 'hidden', 'caption' => 'Xuất excel', 'link' => 'javascript:;', 'icon' => 'fa fa-file-excel-o', 'attributes' => array('class'=>'exportToExcel')),
        ), 'children-class' => 'dropdown-menu pull-right'
    ),
);

?>
<div class="report1" id="adminReport_<?php echo $random; ?>">
    <div class="report-control">
    	<div class="title pull-left"><?php echo $this->caption;?></div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
        </div>
		<div class="clearfix"></div>
	</div>
	<div class="report-wrapper">
    	<div class="report-filter">
    	    <form>
        	    <div class="row">
                    <?php echo $xhtmlFilter;?>
                </div>
            </form>
    	</div>
        <form method="post" id="adminFormFilter" action="/xadmin/contract/filter/">
    	<div class="report-content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="report-table" id="table-manager">
                        <div class="table-scrollable table-fixed">
                			<table class="table table-striped table-bordered table-hover table2excel">
                				<?php echo $this->reportTable;?>
                			</table>
            			</div>
        			</div>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>
<style>
    table thead tr th{
        vertical-align: middle !important;
    }
    .report1 .report-control {
        min-height: 36px;
        line-height: 36px;
        padding-left: 10px;
        margin-bottom: 10px;
        border-bottom: 1px solid #d8d8d8;
        color: #333;
        font-size: 14px;
    }
    .report1 .report-control a{
        color: #333;
    }
    div.table-fixed thead tr:nth-child(2) th {
        top: 28px;
    }
</style>

<script src="/public/template/backend/js/data2excel.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        var idReport = '#adminReport_<?php echo $random; ?>';
        var ajaxUrl = "<?php echo $this->url('routeReport/default', array('controller' => $this->params['controller'], 'action' => $this->params['action'])); ?>";
        function report_<?php echo $random?>() {
            $.ajax({
        		url: ajaxUrl,
        		type: 'POST',
        		data: $(idReport + ' form').serialize(),
        		beforeSend: function() {
        			pageLoading('loading', idReport + ' .report-content');
        		},
        		success: function(result) {
        			result = JSON.parse(result);
        			// Load dữ liệu ra table
        			$(idReport + ' .report-table table').html(result.reportTable);
        			pageLoading('close', idReport + ' .report-content');
        			Form.init();
        			checkAll();
                    // resize_col_table('#table-manager');
        		}
        	});
        }
        report_<?php echo $random?>();
        $(idReport + ' form button[name="submit"]').click(function() {
        	report_<?php echo $random?>();
        });

        $(idReport + ' select').change(function() {
    		report_<?php echo $random?>();
        });
        //$(idReport + ' input').change(function() {
        //	report_<?php //echo $random?>//();
        //});

        var h_window = $(window).height();
        var h_content = h_window - $('.header.navbar').outerHeight() - $('.report-control').outerHeight() - $('.report-filter').outerHeight();
        $('#table-manager .table-scrollable').css({'height': h_content - 31 + 'px'});

        $( window ).resize(function() {
            var h_window = $(window).height();
            var h_content = h_window - $('.header.navbar').outerHeight() - $('.report-control').outerHeight() - $('.report-filter').outerHeight();
            $('#table-manager .table-scrollable').css({'height': h_content - 31 + 'px'});
        });
    });
</script>
