<?php
$myForm = $this->myForm;
$myForm->prepare();
$dateFormat = new \ZendX\Functions\Date();
$contact_options = !empty($this->contact['options']) ? unserialize($this->contact['options']) : array();
$contract_options = !empty($this->contract['options']) ? unserialize($this->contract['options']) : array();
$contract_product = $this->contract_product;

$elements = array(
    array('element' => $myForm->get('history_content'), 'label' => 'Ghi chú hoàn đơn', 'boxClass' => 'col-md-12', 'validate' => array('require' => true)),
    array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    array('element' => $myForm->get('modal'), 'validate' => array('require' => true)),
    array('section' => 'Danh sách sản phẩm', 'boxClass' => 'col-md-12'),
);


$xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

?>

<?php
if($this->params['data']['modal'] != 'success') {
?>
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
        <h4 class="modal-title"><?php echo $this->caption;?></h4>
    </div>
<div class="modal-body">
    <?php
    }
    ?>
    <?php echo @$this->xViewElementErrors($elements);?>
    <form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
        <div class="row">
            <?php echo $xhtml;?>
        </div>
        <div class="contract_product table-scrollable" >
            <table class="table table-striped table-bordered table-hover" style="min-width:1920px">
                <thead>
                <tr>
                    <th width="400px">Sản phẩm</th>
                    <th width="200px">Số lượng trả lại</th>
                    <th width="200px">Số lượng đã mua</th>
                    <th width="200px" class="hidden">CM sản phẩm</th>
                    <th width="200px">Hàng có sẵn</th>
                    <th width="300px">Tên xe - năm sản xuất</th>
                    <th width="400px">Màu thảm</th>
                    <!-- <th width="200px">CM thảm</th> -->
                    <th width="400px">Màu rối</th>
                    <!-- <th width="200px">CM rối</th> -->
                    <th width="400px">Loại sản phẩm</th>
                    <th width="200px">Giá bán</th>
                    <th width="200px">Giảm giá</th>
                    <th width="200px">VAT</th>
                    <th width="200px">Thành tiền bán</th>
                </tr>
                </thead>
                <tbody class="product_body">
                <?php
                $numbers = 0;
                $total_price = 0;
                $total_production = 0;
                $total_price = 0;
                if (count($contract_options['product']) > 0) {
                    foreach ($contract_options['product'] as $key_product => $product_detail){
                        $priceCarpet = 0;
                        $priceTangled = 0;
                        $total_production_price = 0;
                        $type = '';
                        $carpetColor  = $this->getHelperPluginManager()->getServiceLocator()->get('Admin\Model\CarpetColorTable')->getItem(array('id' => $product_detail['carpet_color_id']), null);
                        $tangledColor = $this->getHelperPluginManager()->getServiceLocator()->get('Admin\Model\TangledColorTable')->getItem(array('id' => $product_detail['tangled_color_id']), null);
                        $product      = $this->getHelperPluginManager()->getServiceLocator()->get('Admin\Model\ProductTable')->listItem(null, array('task' => 'cache'));

                        if (!empty($carpetColor)) {
                            $priceCarpet = $this->colorGroup[$carpetColor['parent']]['price'];
                        }
                        if (!empty($tangledColor)) {
                            $priceTangled = $this->colorGroup[$tangledColor['parent']]['price'];
                        }

                        $priceProduction = $priceCarpet + $priceTangled;
                        $total_price = $total_price + $product_detail['total'];

                        // số lượng sản xuất thảm
                        $number_carpet = !empty($product_detail['number_carpet']) || $product_detail['number_carpet'] == 0 ? $product_detail['number_carpet'] : null;
                        // số lượng sản xuất rối
                        $number_tangled = !empty($product_detail['number_tangled']) || $product_detail['number_tangled'] == 0 ? $product_detail['number_tangled'] : null;
                        // số lượng sản xuất SP
                        $number_production = !empty($product_detail['number_production']) || $product_detail['number_production'] == 0 ? $product_detail['number_production'] : null;
                        $numbers = $product_detail['numbers']?:1;
                        $refund = $product_detail['refund']?:'';

                        if(!empty($contract_product)){
                            $number_carpet     = $contract_product['number_carpet'][$key_product];
                            $number_tangled    = $contract_product['number_tangled'][$key_product];
                            $number_production = $contract_product['number_production'][$key_product];
                            $numbers = $contract_product['numbers'][$key_product];
                        }

                        $total_price_sell = !empty($product_detail['price']) ? $product_detail['price'] : 0;
                        if (!empty($product_detail['number_carpet']) || !empty($product_detail['number_tangled'])) {
                            $total_production_price = $number_carpet * $priceCarpet + $number_tangled * $priceTangled;
                        } else {
                            $total_production_price = $numbers * $product[$product_detail['product_id']]['price'];
                        }

                        $total_production = $total_production + $total_price_sell;

                        if (!empty($product_detail['stock'])) {
                            $type = 'readonly';
                        }
                        ?>

                        <tr class="product_row">
                            <td class="products"><input class="form-control" type="text" readonly value="<?php echo $this->product[$product_detail['product_id']]['name']; ?>"></td>
                            <td class="refund"><input class="form-control" name="contract_product[refund][]" type="number" min="0" max="<?php echo $numbers;?>" value="<?php echo $refund; ?>" placeholder=""></td>
                            <td class="numbers"><input class="form-control" name="contract_product[numbers][]" type="number" min="0" value="<?php echo $numbers; ?>" placeholder="" readonly></td>
                            <td class="hidden number_production"><input class="form-control" <?php echo $type; ?> name="contract_product[number_production][]" type="number" min="0" value="<?php echo $number_production; ?>" placeholder="cm"></td>
                            <td class="stock"><input class="form-control" type="text" readonly value="<?php echo $product_detail['stock']; ?>"></td>
                            <td class="product-name"><input class="form-control" type="text" readonly value="<?php echo $product_detail['product_name']; ?>" title="<?php echo $product_detail['product_name']; ?>"></td>
                            <td class="carpet-color"><input class="form-control"  type="text" readonly value="<?php echo $this->carpet_color[$product_detail['carpet_color_id']]['name']; ?>"></td>
                            <!-- <td class="number_carpet"><input class="form-control" <?php echo $type; ?> name="contract_product[number_carpet][]" type="number" min="0" value="<?php echo $number_carpet; ?>"></td> -->
                            <td class="tangled-color"><input class="form-control" type="text" readonly value="<?php echo $this->tangled_color[$product_detail['tangled_color_id']]['name']; ?>"></td>
                            <!-- <td class="number_tangled"><input class="form-control" <?php echo $type; ?> name="contract_product[number_tangled][]" type="number" min="0" value="<?php echo $number_tangled; ?>" ></td> -->
                            <td class="flooring"><input class="form-control" type="text" readonly value="<?php echo $this->flooring[$product_detail['flooring_id']]['name']; ?>"></td>
                            <td class="price"><input class="form-control" readonly type="text" value="<?php echo $product_detail['price']; ?>"></td>
                            <td class="sale_price"><input class="form-control" readonly type="number"value="<?php echo $product_detail['sale_price']; ?>" min="0"></td>
                            <td class="vat"><input class="form-control" readonly type="number" value="<?php echo $product_detail['vat']; ?>" min="0"></td>
                            <td class="total"><input class="form-control" readonly type="text" readonly value="<?php echo number_format($product_detail['total']); ?>"></td>
                            <td class="total_production hidden">
                                <input class="form-control" name="contract_product[total_production][]" readonly type="text" readonly value="<?php if(!empty($total_production_price)) : echo number_format($total_production_price); endif; ?>">
                            </td>
                        </tr>
                        <?php
                    }
                } else {
                    ?>
                    <tr align="center">
                        <td colspan="9" >Không có sản phẩm</td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
                <?php if (count($contract_options['product']) > 0) { ?>
                    <tfoot>
                    <tr>
                        <td>Tổng</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td style="padding: 10px 0 10px 19px;"><?php echo number_format($total_production); ?></td>
                        <td></td>
                        <td></td>
                        <td class="total_price_product" style="padding: 10px 0 10px 19px;"><?php echo number_format($total_price); ?></td>
                        <td class="hidden"></td>
                        <td class="hidden"></td>
                        <td class="total_price_production hidden" style="padding: 10px 0 10px 19px;"><?php echo number_format($total_production); ?></td>
                    </tr>
                    </tfoot>
                <?php } ?>
            </table>
        </div>
    </form>
    <?php
    if($this->params['data']['modal'] != 'success') {
    ?>
</div>
    <div class="modal-footer">
<!--        <button type="button" class="btn green --><?php //echo $this->contract['status_refund']?'save-close-custom':'save-close';?><!--">--><?php //echo $this->contract['status_refund']?'Duyệt hoàn':'Lưu & Đóng';?><!--</button>-->
        <button type="button" class="btn green save-close">Lưu & Đóng</button>
        <button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
    </div>
<?php
}
?>

<style>
    .custom-modal {
        width: 90%!important;
        margin-left: -45%!important;
    }
</style>
<script>
    var $modal 	= $('#ajax-modal');
    var $form 	= $('#adminForm');
    var status_refund = 1*'<?php echo $this->contract['status_refund']?:'0';?>';
    $('.btn-close-modal').on('click', function(){
        var table = $('#table-manager').find('table tbody');
        $('#table-manager tbody tr').each(function() {
            $(this).find('input[name="cid[]"]').removeAttr('checked');
        })
    });
    if (status_refund==1) {
        $('[name="history_content"]').attr('readonly',true);
        $('[name="contract_product[refund][]"]').attr('readonly',true);
    }

    $modal.on('click', '.save-close-custom', function(e){
        e.preventDefault();
        var error 	= null;
        var alertError 	= '';
        var type = $(this).data('type');

        if (error) {
            $('.alert-danger').remove();
            alertError = '<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert"></button><p>'+error+'</p></div>';
            $(alertError).insertBefore('input[name="type_of_carpet_id"]');
            // console.log(error);
        } else {
            $.ajax({
                url: '/xadmin/check/refund-split-contract',
                type: 'POST',
                data: $modal.find('form').serialize(),
                beforeSend: function() {
                    $modal.modal('loading');
                    $modal.find('.btn').addClass('disabled');
                },
                success: function(result) {
                    if(result == 'success') {
                        $modal.modal('hide');
                        location.reload();
                    } else {
                        $modal.modal('loading');
                        $modal.find('.btn').removeClass('disabled');
                        $modal.find('.modal-body').html(result);
                        reloadScript();
                    }
                },
                error: function (request, status, error) {
                    console.log(error);
                }
            });
        }

    });

    var type = $('input[class="production_type"]').val();
    var status = $('select[name="production_department_type"]').val();
    if (status == 'da-giao-hang' && type == 1) {
        $('#shipper').removeClass('hidden');
    }

    $('select[name="production_department_type"]').change(function() {
        var type = $('input[class="production_type"]').val();
        if ($(this).val() == 'da-giao-hang' && type == 1) {
            $('#shipper').removeClass('hidden');
        } else {
            $('#shipper').addClass('hidden');
        }
    })

    $('input[name="price_promotion"]').change(function() {
        update_price_contract();
    });

    $('input[name="contract_product[number_production][]"]').change(function() {
        var me = $(this);
        var price_production = me.parents('tr').find('input[name="contract_product[price_production][]"]').val();
        total = 0;
        total = parseInt(me.val()) * parseInt(price_production);
        var total_production = me.parents('tr').find('input[name="contract_product[total_production][]"]');
        total_production.val(formatNumber(total));
        var total_price = 0;
        $('.product_row').each(function() {
            total_price = parseInt(total_price) + parseInt(unFormatNumber($(this).find('input[name="contract_product[total_production][]"]').val()));
        })
        $('.total_price_production').html(formatNumber(total_price));
    });

    function update_price_contract() {
        var price_carpet 			= $('input[name="price_carpet"]').autoNumeric('get');
        var price_nano 				= $('input[name="price_nano"]').autoNumeric('get');
        var price_promotion 		= $('input[name="price_promotion"]').autoNumeric('get');

        var total = 0;
        var vat = 0;
        total = parseInt(total) + parseInt(price_carpet);
        if (price_nano > 0) {
            total = total + parseInt(price_nano);
        }
        vat = total * 10/100;
        total = total + vat;
        $('input[name="vat"]').autoNumeric('set', vat);
        if (price_promotion > 0) {
            total = total - parseInt(price_promotion);
        }
        $('input[name="price_total"]').autoNumeric('set', total);
    }
</script>
