<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <title><?php echo $this->settings['General.System.Title']['value'];?></title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="MobileOptimized" content="320">
    
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap&subset=vietnamese" rel="stylesheet">
    
    <link href="<?php echo $this->arrParams['template']['urlPlugin'];?>/font-awesome/css/font-awesome.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->arrParams['template']['urlPlugin'];?>/bootstrap/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->arrParams['template']['urlCss'];?>/style-metronic.css" media="screen" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->arrParams['template']['urlCss'];?>/style.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->arrParams['template']['urlCss'];?>/login.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">
    <link href="<?php echo $this->arrParams['template']['urlCss'];?>/custom.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">

    <link href="<?php echo $this->arrParams['template']['urlImg'];?>/favicon.jpg" rel="icon" type="image/x-icon">
</head>
<body class="page_login">
	<?php echo $this->content;?>
    <?php include_once $this->arrParams['template']['pathHtml'] . '/copyright.php';?>

	<!-- BEGIN CORE PLUGINS -->
	<!--[if lt IE 9]>
	<script src="<?php echo $this->arrParams['template']['urlPlugin'] . '/respond.min.js';?>"></script>
	<script src="<?php echo $this->arrParams['template']['urlPlugin'] . '/excanvas.min.js';?>"></script> 
	<![endif]-->
	<script src="<?php echo $this->arrParams['template']['urlPlugin'] . '/jquery-1.12.4.min.js';?>" type="text/javascript"></script>
	<script src="<?php echo $this->arrParams['template']['urlPlugin'] . '/bootstrap/js/bootstrap.min.js';?>" type="text/javascript"></script>
	<!-- END CORE PLUGINS -->
	
	<script src="<?php echo $this->arrParams['template']['urlJs'] . '/define.js';?>" type="text/javascript"></script>
	<script src="<?php echo $this->arrParams['template']['urlJs'] . '/login.js';?>" type="text/javascript"></script>
	<script type="text/javascript">
	jQuery(document).ready(function() {
	   Login.init();
	});
	</script>
	<!-- END JAVASCRIPTS -->
	
	<?php echo $this->headScript();?>
</body>