<html>
<head>
<?php 
    // Title
    echo $this->headTitle();
    
    // Meta
    echo $this->headMeta()
              ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
              ->appendName('viewport', 'width=device-width, initial-scale=1.0')
    		  ->setCharset('utf-8');
    
    // CSS
    echo $this->headLink()
              ->appendStylesheet($this->arrParams['template']['urlPlugin'] . '/font-awesome/css/font-awesome.min.css')
              ->appendStylesheet($this->arrParams['template']['urlPlugin'] . '/bootstrap/css/bootstrap.min.css')
              ->appendStylesheet($this->arrParams['template']['urlCss'] . '/public.css');
?>
</head>
<body>
    <?php echo $this->content; ?>
    
    <script src="<?php echo $this->arrParams['template']['urlPlugin'] . '/jquery-1.12.4.min.js';?>" type="text/javascript"></script>
    <script src="<?php echo $this->arrParams['template']['urlPlugin'] . '/bootstrap/js/bootstrap.min.js';?>" type="text/javascript"></script>
</body>