<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('phone'), 'label' => 'Điện thoại khách hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => ' ', 'boxClass' => 'col-md-3'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th>Ngày tiếp nhận</th>';
    $xhtmlHead .= '<th>Điện thoại</th>';
    $xhtmlHead .= '<th>Họ tên</th>';
    $xhtmlHead .= '<th>Sản phẩm quan tâm</th>';
    $xhtmlHead .= '<th>Tên xe - Năm sản xuất</th>';
    $xhtmlHead .= '<th>Nội dung tư vấn</th>';
    $xhtmlHead .= '<th>Lịch sử chăm sóc cuối</th>';
    $xhtmlHead .= '<th>Người quản lý</th>';
    $xhtmlHead .= '<th>Công cụ</th>';
    $xhtmlHead .= '</tr>';

    // Danh sách
    $xhtmlItems = '';
    if (!empty($this->contacts)) {
        foreach ($this->contacts AS $item) {
            $cid = @$this->xFormInput('cid[]', $item->id, array('type' => 'checkbox', 'class' => 'checkboxes'));

            $id = $item->id;
            $date = $dateFormat->formatToView($item->date, 'd/m/Y H:i');
            $phone = $item->phone;
            $name = $item->name;
            $product_group = $item->product_group_id ? $this->product_group[$item->product_group_id]['name'] : '';
            $user_id = $item->user_id ? $this->user[$item->user_id]['name'] : '';
            $sale_group_id = $item->sale_group_id ? '<br>' . $this->sale_group[$item->sale_group_id]['name'] : '';
            $sale_branch_id = $item->sale_branch_id ? ' - ' . $this->sale_branch[$item->sale_branch_id]['name'] : '';
            $options = $item->options ? unserialize($item['options']) : array();
            $history_created = $dateFormat->formatToView($item['history_created']);
            $history_content = $options['history_content'];
            $history_action = $this->sale_history_action[$options['history_action_id']]['name'];
            $history_result = $this->sale_history_result[$options['history_result_id']]['name'];
            $history_type = $this->sale_history_type[$options['history_type_id']]['name'];
            $note = nl2br($options['note']);
            $content = nl2br($options['content']);

            $x_history = '';
            if (!empty($history_created)) {
                $x_history = $history_created . ' - ' . $history_action . ': ' . $history_result;
                $x_history .= '<div>Phân loại: ' . $history_type . '</div>';
                $x_history .= '<div>' . $history_content . '</div>';
                $x_history .= '<a style="font-size: 11px;" href="javascript:;" title="Xem lịch sử chăm sóc" onclick="javascript:popupAction(\'' . $this->url('routeAdmin/default',
                        array(
                            'controller' => 'Contact',
                            'action' => 'history-list'
                        )) . '\', {\'id\': \'' . $id . '\'});">Xem thêm ...</a>';
            }

            $xhtmlItems .= '<tr>';
            $xhtmlItems .= '<td>' . $date . '</td>';
            $xhtmlItems .= '<td>' . $phone . '</td>';
            $xhtmlItems .= '<td>' . $name . '</td>';
            $xhtmlItems .= '<td>' . $product_group . '</td>';
            $xhtmlItems .= '<td><div class="col-190 text-wrap">' . $note . '</div></td>';
            $xhtmlItems .= '<td><div class="col-190 text-wrap">' . $content . '</div></td>';
            $xhtmlItems .= '<td><div class="col-300 text-wrap">' . $x_history . '</div></td>';
            $xhtmlItems .= '<td>' . $user_id . $sale_group_id . $sale_branch_id . '</td>';
            $xhtmlItems .= '<td class="controls"><a class="btn btn-xs blue " href="/xadmin/contract/add-kov/id/'.$id.'/code/1"><i class="fa fa-plus"></i> Lên đơn</a></td>';
            $xhtmlItems .= '</tr>';
        }
    }
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->contacts)) {
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<?php echo $xhtmlHead; ?>
            				</thead>
            				<tbody>
                            <?php echo $xhtmlItems; ?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Khánh hàng chưa tồn tại trên hệ thống</div>';
		}
		?>
	</div>
</form>
<style>
    .control-label {
        min-height: 15px;
    }
    .link_add_contract {
        background: green;
        color: #ffffff;
        padding: 3px 5px;
    }
</style>