<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    // Set lại các giá trị của từng element
    $myForm->get('location_district_id')->setAttributes(array('data-parent' => $myForm->get('location_city_id')->getValue()));
    
    $elementsTop = array(
        array('section' => 'Thông tin khách hàng', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('phone'), 'label' => 'Số điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('name'), 'label' => 'Họ và tên', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('location_city_id'), 'label' => 'Tỉnh thành', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('location_district_id'), 'label' => 'Quận huyện', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('address'), 'label' => 'Địa chỉ nơi ở', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),

        array('section' => 'Thông tin người nhận', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('name_received'), 'label' => 'Họ và tên', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('phone_received'), 'label' => 'Số điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('address_received'), 'label' => 'Địa chỉ nhận hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),

        array('section' => 'Thông tin đơn hàng', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('date'), 'label' => 'Ngày ký', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
		array('element' => $myForm->get('production_type_id'), 'label' => 'Loại đơn sản xuất', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
		array('element' => $myForm->get('status_guarantee_id'), 'label' => 'Đơn bảo hành', 'boxClass' => 'col-md-1 guarantee hidden'),
		array('element' => $myForm->get('code_old'), 'label' => 'Mã đơn cũ', 'boxClass' => 'col-md-2 code-old'),
        array('element' => $myForm->get('sale_note'), 'label' => 'Ghi chú sales', 'boxClass' => 'col-md-3'),
    );
    
    $xhtmlTop = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsTop);

    $elementsBottom = array(
        array('div' => '', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('price_total'), 'label' => 'Tổng tiền', 'boxClass' => 'col-md-2 hidden'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
		
//        array('section' => 'Thông tin hoá đơn', 'boxClass' => 'col-md-12'),
//        array('element' => $myForm->get('bill_type_id'), 'label' => 'Hình thức thanh toán', 'validate' => array('require' => true), 'boxClass' => 'col-md-2 box-required'),
//        array('element' => $myForm->get('bill_date'), 'label' => 'Ngày thu', 'validate' => array('require' => true), 'boxClass' => 'col-md-2 box-required'),
//        array('element' => $myForm->get('bill_bank_id'), 'label' => 'Ngân hàng', 'boxClass' => 'col-md-2 box-bill_bank_id box-required'),
//        array('element' => $myForm->get('bill_paid_price'), 'label' => 'Tiền Cọc + Thanh Toán Trước', 'boxClass' => 'col-md-2 bill_paid_price box-required','validate' => array('require' => true), ),
//        array('element' => $myForm->get('bill_paid_type_id'), 'label' => 'Phân loại thu', 'boxClass' => 'col-md-2 box-required','validate' => array('require' => true), ),

        array('section' => 'DANH SÁCH ĐƠN HÀNG', 'boxClass' => 'col-md-12'),
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'load_contract', 'boxStyle' => 'margin-bottom: 20px;'),
    );
    $xhtmlBottom = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsBottom);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elementsTop);?>
	<?php echo @$this->xViewElementErrors($elementsBottom);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtmlTop;?>
            <div class="col-md-12">
                <h3 class="form-section">Thông tin sản phẩm</h3>
                <div id="form-product-return" data-url="<?php echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'get-contract-available')); ?>">
                    <input type="text" id="hang-co-san" value="" placeholder="Nhập mã đơn hàng có sẵn">
                    <input type="button" value="Tìm">

                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="control-element">
                                <select class="select2 select2_basic form-control" name="choice_combo">
                                    <option value="">- Mua sản phẩm theo combo -</option>
                                    <?php
                                    foreach ($this->combos as $combo) {
                                        ?>
                                        <option value="<?php echo $combo['id'] ?>" data-product="<?php echo $combo['id']; ?>"><?php echo $combo["name"] .' : '. number_format($combo['price_total']) ?></option>
                                        <?php
                                    }
                                    ?>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <p class="text-alert"></p>
                <?php
                    if(!empty($this->check_product_id)){
                    ?>
                    <div class="alert alert-block alert-danger">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <p><?php echo $this->check_product_id; ?></p>
                    </div>
                    <?php
                    }
                ?>
            </div>
		</div>
        <div class="contract_product table-scrollable" >
            <table class="table table-striped table-bordered table-hover table-product" style="min-width:1920px">
                <thead>
                    <tr>
                        <th width="200px">Sản phẩm</th>
                        <th width="">Mã ĐH có sẵn</th>
                        <th width="">Tên xe - năm sản xuất</th>
                        <th width="200px">Màu thảm</th>
                        <th width="200px">Màu rối</th>
                        <th width="200px">Loại sản phẩm</th>
                        <th class="hidden">Giá vốn mặc định</th>
                        <th>Số lượng</th>
                        <th>Giá niêm yết</th>
                        <th>Giá bán</th>
                        <th>Giảm giá</th>
                        <th>VAT</th>
                        <th>Thành tiền</th>
                        <th>Xóa</th>
                    </tr>
                </thead>
                <tbody class="product_body">
                    <?php
                    if (!empty($productList)) {
                        for($i = 0; $i < count($productList['product_id']) - 1; $i++) {
                        ?>
                        <tr class="product_row" data-code="<?php echo $productList['stock'][$i]; ?>">
                            <?php
                                if(!empty($productList['stock'][$i])){
                                    ?>
                                    <td class="hidden">
                                        <input type="hidden" name="contract_product[key_id][]" value="<?php echo $productList['key_id'][$i]; ?>">

                                        <input type="hidden" name="contract_product[product_id][]" value="<?php echo $productList['product_id'][$i]; ?>">
                                        <input type="hidden" name="contract_product[carpet_color_id][]" value="<?php echo $productList['carpet_color_id'][$i]; ?>">
                                        <input type="hidden" name="contract_product[tangled_color_id][]" value="<?php echo $productList['tangled_color_id'][$i]; ?>">
                                        <input type="hidden" name="contract_product[flooring_id][]" value="<?php echo $productList['flooring_id'][$i]; ?>">

                                        <input type="hidden" name="contract_product[keyUpdate][]" value="<?php echo $productList['keyUpdate'][$i]; ?>">
                                        <input type="hidden" name="contract_product[sale_branch_id][]" value="<?php echo $productList['sale_branch_id'][$i]; ?>">
                                        <input type="hidden" name="contract_product[type][]" value="<?php echo $productList['type'][$i]; ?>">
                                        <input type="hidden" name="contract_product[number_production][]" value="<?php echo $productList['number_production'][$i]; ?>">
                                        <input type="hidden" name="contract_product[number_carpet][]" value="<?php echo $productList['number_carpet'][$i]; ?>">
                                        <input type="hidden" name="contract_product[number_tangled][]" value="<?php echo $productList['number_tangled'][$i]; ?>">
                                        <input type="hidden" name="contract_product[price_production][]" value="<?php echo $productList['price_production'][$i]; ?>">
                                        <input type="hidden" name="contract_product[total_production][]" value="<?php echo $productList['total_production'][$i]; ?>">
                                    </td>
                                    <?php
                                }
                            ?>
                            <td class="products text-middle <?php if(trim($productList['product_id'][$i]) == "") echo "has-error"?>">
                                <?php
                                    if(!empty($productList['stock'][$i])){
                                        echo $this->product[$productList['product_id'][$i]]["name"];
                                    }
                                    else{
                                        ?>
                                        <select class="select-product select2 select2_basic form-control" name="contract_product[product_id][]">
                                            <option value="">- Chọn -</option>
                                            <?php
                                                foreach ($this->product as $value) {
                                                    ?>
                                                    <option <?php if($productList['product_id'][$i] == $value['id']){ echo 'selected'; } ?> value="<?php echo $value['id'] ?>" data-product="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                                    <?php
                                                }
                                            ?>
                                        </select>
                                        <?php
                                    }
                                ?>
                            </td>

                            <td class="stock"><input class="form-control" type="text" name="contract_product[stock][]" value="<?php if(!empty($productList['stock'][$i])){ echo $productList['stock'][$i]; } ?>" readonly></td>
                            <td class="product-name <?php if(trim($productList['product_name'][$i]) == "") echo "has-error"?>"><input class="form-control" type="text" name="contract_product[product_name][]" value="<?php if(!empty($productList['product_name'][$i])){ echo $productList['product_name'][$i]; } ?>"></td>

                            <td class="carpet-color text-middle <?php if(trim($productList['carpet_color_id'][$i]) == "") echo "has-error"?>">
                                <?php
                                    if(!empty($productList['stock'][$i])){
                                        echo $this->carpet_color[$productList['carpet_color_id'][$i]]["name"];
                                    }
                                    else{
                                        ?>
                                        <select class="select-product select2 select2_basic form-control" name="contract_product[carpet_color_id][]">
                                            <option value="">- Chọn -</option>
                                            <?php
                                                foreach ($this->carpet_color as $value) {
                                                    ?>
                                                    <option <?php if($productList['carpet_color_id'][$i] == $value['id']){ echo 'selected'; } ?> value="<?php echo $value['id'] ?>" data-carpet-color="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                                    <?php
                                                }
                                            ?>
                                        </select>
                                        <?php
                                    }
                                ?>
                            </td>
                            <td class="tangled-color text-middle <?php if(trim($productList['tangled_color_id'][$i]) == "") echo "has-error"?>">
                                <?php
                                    if(!empty($productList['stock'][$i])){
                                        echo $this->tangled_color[$productList['tangled_color_id'][$i]]["name"];
                                    }
                                    else{
                                        ?>
                                        <select class="select-product select2 select2_basic form-control" name="contract_product[tangled_color_id][]">
                                            <option value="">- Chọn -</option>
                                            <?php
                                                foreach ($this->tangled_color as $value) {
                                                    ?>
                                                    <option <?php if($productList['tangled_color_id'][$i] == $value['id']){ echo 'selected'; } ?> value="<?php echo $value['id'] ?>" data-tangled-color="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                                    <?php
                                                }
                                            ?>
                                        </select>
                                        <?php
                                    }
                                ?>
                            </td>
                            <td class="flooring text-middle <?php if(trim($productList['flooring_id'][$i]) == "") echo "has-error"?>">
                                <?php
                                    if(!empty($productList['stock'][$i])){
                                        echo $this->flooring[$productList['flooring_id'][$i]]["name"];
                                    }
                                    else{
                                        ?>
                                        <select class="select-product select2 select2_basic form-control" name="contract_product[flooring_id][]">
                                            <option value="">- Chọn -</option>
                                            <?php
                                                foreach ($this->flooring as $value) {
                                                    ?>
                                                    <option <?php if($productList['flooring_id'][$i] == $value['id']){ echo 'selected'; } ?> value="<?php echo $value['id'] ?>" data-flooring="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                                    <?php
                                                }
                                            ?>
                                        </select>
                                        <?php
                                    }
                                ?>
                            </td>

                            <td class="capital_default hidden"><input class="form-control text-right" readonly type="text" name="contract_product[capital_default][]" value="<?php if(!empty($productList['capital_default'][$i])){ echo $productList['capital_default'][$i]; } ?>" min="1"></td>
                            <td class="numbers"><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="<?php echo $productList['numbers'][$i]?:'1';?>" min="1"></td>
                            <td class="listed_price"><input class="form-control text-right" readonly type="text" name="contract_product[listed_price][]" value="<?php if(!empty($productList['listed_price'][$i])){ echo $productList['listed_price'][$i]; } ?>" min="1"></td>
                            <td class="price  <?php if(trim($productList['price'][$i]) == "") echo "has-error"?>"><input class="form-control text-right money" type="text" name="contract_product[price][]" value="<?php echo $productList['price'][$i]; ?>" min="0"></td>
                            <td class="sale_price"><input class="form-control text-right money" readonly type="text" name="contract_product[sale_price][]" value="<?php if(!empty($productList['sale_price'][$i])){ echo $productList['sale_price'][$i]; } ?>" min="0"></td>
                            <td class="vat <?php if(trim($productList['vat'][$i]) == "") echo "has-error"?>"><input class="form-control text-right money" type="text" name="contract_product[vat][]" value="<?php echo $productList['vat'][$i]; ?>" min="0"></td>
                            <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" value="<?php if(!empty($productList['total'][$i])){ echo $productList['total'][$i]; } ?>" readonly></td>
                            <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
                        </tr>
                        <?php
                        }
                    } else {
                        ?>
                        <tr class="product_row">
                            <td class="products">
                                <select class="select-product select2 select2_basic form-control" name="contract_product[product_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php
                                    foreach ($this->product as $value) {
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-product="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="stock"><input class="form-control" type="text" name="contract_product[stock][]" value="" readonly></td>
                            <td class="product-name"><input class="form-control" type="text" name="contract_product[product_name][]" value=""></td>
                            <td class="carpet-color">
                                <select class="select-product select2 select2_basic form-control" name="contract_product[carpet_color_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php
                                    foreach ($this->carpet_color as $value) {
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-carpet-color="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="tangled-color">
                                <select class="select-product select2 select2_basic form-control" name="contract_product[tangled_color_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php
                                    foreach ($this->tangled_color as $value) {
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-tangled-color="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="flooring">
                                <select class="select-product select2 select2_basic form-control" name="contract_product[flooring_id][]">
                                    <option value="">- Chọn -</option>
                                    <?php
                                    foreach ($this->flooring as $value) {
                                    ?>
                                        <option value="<?php echo $value['id'] ?>" data-flooring="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                    <?php
                                    }
                                    ?>
                                </select>
                            </td>
                            <td class="capital_default hidden"><input class="form-control text-right" readonly type="text" name="contract_product[capital_default][]" value="" min="1"></td>
                            <td class="numbers"><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="1" min="1"></td>
                            <td class="listed_price"><input class="form-control text-right" readonly type="text" name="contract_product[listed_price][]" value="" min="1"></td>
                            <td class="price"><input class="form-control money text-right" type="text" name="contract_product[price][]" value="" min="0"></td>
                            <td class="sale_price"><input class="form-control text-right money" readonly type="text" name="contract_product[sale_price][]" value="" min="0"></td>
                            <td class="vat"><input class="form-control text-right money" type="text" name="contract_product[vat][]" value="" min="0"></td>
                            <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" value="" readonly></td>
                            <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
                        </tr>
                        <?php
                    }
                    ?>
                    <!-- Dòng dữ liệu mặc định khi thêm mới một sản phẩm-->
                    <tr class="row_product_add hidden">
                        <td class="products">
                            <select class="select-product select2 select2_basic form-control" name="contract_product[product_id][]">
                                <option value="">- Chọn -</option>
                                <?php
                                    foreach ($this->product as $value) {
                                        ?>
                                        <option value="<?php echo $value['id'] ?>" data-product="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </td>
                        <td class="stock"><input class="form-control" type="text" name="contract_product[stock][]" value="" readonly></td>
                        <td class="product-name"><input class="form-control" type="text" name="contract_product[product_name][]" value=""></td>
                        <td class="carpet-color">
                            <select class="select-product select2 select2_basic form-control" name="contract_product[carpet_color_id][]">
                                <option value="">- Chọn -</option>
                                <?php
                                    foreach ($this->carpet_color as $value) {
                                        ?>
                                        <option value="<?php echo $value['id'] ?>" data-carpet-color="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </td>
                        <td class="tangled-color">
                            <select class="select-product select2 select2_basic form-control" name="contract_product[tangled_color_id][]">
                                <option value="">- Chọn -</option>
                                <?php
                                    foreach ($this->tangled_color as $value) {
                                        ?>
                                        <option value="<?php echo $value['id'] ?>" data-tangled-color="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </td>
                        <td class="flooring">
                            <select class="select-product select2 select2_basic form-control" name="contract_product[flooring_id][]">
                                <option value="">- Chọn -</option>
                                <?php
                                    foreach ($this->flooring as $value) {
                                        ?>
                                        <option value="<?php echo $value['id'] ?>" data-flooring="<?php echo $value['id']; ?>"><?php echo $value["name"] ?></option>
                                        <?php
                                    }
                                ?>
                            </select>
                        </td>
                        <td class="capital_default hidden"><input class="form-control text-right" readonly type="text" name="contract_product[capital_default][]" value="" min="1"></td>
                        <td class="numbers"><input class="form-control text-right money" type="text" name="contract_product[numbers][]" value="1" min="1"></td>
                        <td class="listed_price"><input class="form-control text-right" readonly type="text" name="contract_product[listed_price][]" value="" min="1"></td>
                        <td class="price"><input class="form-control money text-right" type="text" name="contract_product[price][]" value="" min="0"></td>
                        <td class="sale_price"><input class="form-control text-right money" readonly type="text" name="contract_product[sale_price][]" value="" min="0"></td>
                        <td class="vat"><input class="form-control text-right money" type="text" name="contract_product[vat][]" value="" min="0"></td>
                        <td class="total"><input class="form-control text-right" type="text" name="contract_product[total][]" value="" readonly></td>
                        <td><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 5px 0 0 5px; font-size: 20px;"></i></td>
                    </tr>
                </tbody>
                <tfoot>
                    <tr>
                        <td>Tổng</td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td></td>
                        <td class="total-listed-price text-right" style="padding: 10px 18px;"></td>
                        <td class="total-price-sell text-right" style="padding: 10px 18px;"></td>
                        <td></td> 
                        <td></td> 
                        <td class="total_price text-right" style="padding: 10px 18px;"></td>
                        <td></td>
                    </tr>
                </tfoot>
            </table>
            <a href="javascript:void(0);" class="btn btn-default" id="add_row_product" style="margin-bottom: 5px; background-color: #5cb85c; color: white;">Thêm sản phẩm</a>
        </div>
        <div class="hidden">
            <input type="hidden" name="total_price_product" value="" >
        </div>
    	<div class="row">
			<?php echo $xhtmlBottom;?>
		</div>
	</div>
</form>

<div class="hidden" id="contactPhone">
    <?php echo $this->contactPhone;?>
</div>
<div class="hidden" id="contactId">
    <?php echo $this->contactId;?>
</div>

<style>
#form-product-return {
    padding: 5px 0 10px 0;
    overflow: hidden;
}
#form-product-return input[type="text"] {
    float: left;
    padding: 4px 5px;
    border-right: 0px;
    border: 1px #ccc solid;
    font-size: 14px;
}
#form-product-return input[type="button"] {
    float: left;
    padding: 5px 10px 3px 10px;
    border-left: 0;
    border: 1px #5cb85c solid;
    background: #5cb85c;
    font-size: 14px;
    color: #fff;
}
</style>

<?php $this->headScript()->captureStart() ?>
    // Xử lý load tỉnh thành
    $('select[name="location_city_id"]').change(function() {
        var select = 'input[name="location_district_id"]';
        var parent = $(select).parent();
        $('.select2-container', parent).select2('val', '');
        $(select).attr('data-parent', $(this).val());
    });

    var contactPhone = $('#contactPhone').text().trim();
    if(contactPhone){
        load_action('#load_contract', '<?php echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'list-contract-by-phone'));?>', {phone: contactPhone});
    }

    // Kiểm tra thông tin khách hàng
    var contactId    = $('#contactId').text().trim();
    if(contactId) {
        checkContactToElement(contactId, 'element');
    }

    function optionBill(item) {
        if (item == '' || item == null) {
            $('.box-bill_bank_id').addClass('box-hidden');
        }
        if(item == 'cod') {
            $('.box-bill_paid_number').removeClass('box-hidden');
            $('.box-bill_paid_number .control-label').html('Số phiếu thu<span class="required">*</span>');
            $('.box-bill_bank_id').addClass('box-hidden');
            $('.bill_paid_price').addClass('box-hidden');
            $('.box-required').each(function() {
                $(this).find('label span').removeClass('box-hidden');
            });
        }
        if(item == 'tructiep' ) {
            $('.bill_paid_price').removeClass('box-hidden');
            $('.box-bill_paid_number').removeClass('box-hidden');
            $('.box-bill_paid_number .control-label').html('Số phiếu thu<span class="required">*</span>');
            $('.box-bill_bank_id').addClass('box-hidden');
            $('.box-required').each(function() {
                $(this).find('label span').removeClass('box-hidden');
            });
        }
        if(item == 'quet-the') {
            $('.bill_paid_price').removeClass('box-hidden');
            $('.box-bill_paid_number').removeClass('box-hidden');
            $('.box-bill_paid_number .control-label').html('Số bill<span class="required">*</span>');
            $('.box-bill_bank_id').addClass('box-hidden');
        }
        if(item == 'chuyen-khoan') {
            $('.bill_paid_price').removeClass('box-hidden');
            $('.box-bill_bank_id').removeClass('box-hidden');
            $('.box-bill_paid_number').addClass('box-hidden');
            $('.box-required').each(function() {
                $(this).find('label span').removeClass('box-hidden');
            });
        }
    }
    optionBill('<?php echo $myForm->get('bill_type_id')->getValue();?>');
    $('select[name="bill_type_id"]').change(function() {
        optionBill($(this).val());
    });

    // Check đơn hàng có sẵn
    $('#form-product-return input[type=button]').on('click', function() {
        var url = $('#form-product-return').data('url');
        var code = $('#form-product-return').find('input[type=text]').val();
        $.ajax({
            url: url,
            method: 'POST',
            data: {
                code: code
            },
            success: function(data) {
                $('.text-alert').html();
                if (data) {
                $('.text-alert').addClass('text-success');
                    var message = 'Tìm đơn hàng có sẵn thành công';
                } else {
                    $('.text-alert').addClass('text-danger');
                    var message = 'Đơn hàng không có trong kho hàng có sẵn';
                }
                $('.text-alert').html(message);
                $('.product_body tr[data-code="'+code+'"]').remove();
                $('.product_body').prepend(data);
                $('.product_body').find('select.select2').select2();
                updateTotal();
            }
        })
    });
    $('select[name="choice_combo"]').change(function() {
        var id = $(this).val();
        $.ajax({
            url: '/xadmin/api/get-combo-product/',
            method: 'POST',
            data: {
                id: id
            },
            success: function(data) {
                $('.text-alert').html();
                if (data) {
                    $('.text-alert').addClass('text-success');
                    var message = 'Chọn sản phẩm combo thành công';
                } else {
                    $('.text-alert').addClass('text-danger');
                    var message = 'Sản phẩm không tồn tại hoặc không được sử dụng';
                }
                $('.text-alert').html(message);
                $('.product_body tr[data-code="'+id+'"]').remove();
                $('.product_body').prepend(data);
                $('.product_body').find('select.select2').select2();
                updateTotal();
            }
        })
    });
    resize_col_table('#table-manager');

<?php $this->headScript()->captureEnd() ?>


<?php $this->headScript()->captureStart() ?>
var product_setting = [];
var setting_data = [];
$.ajax({
    url:'/xadmin/api/product-setting',method:'POST',data:{pagination:false},dataType:'json',
    success:function(resp) {
        product_setting = resp.setting;
        setting_data = resp.data;
    }
})
    $('input[name="vat"]').change(function() {
        update_price_contract();
    });
    $('body').delegate(".products select, .carpet-color select, .tangled-color select, .flooring select,.numbers input",'change',function(e){
        var total = 0;
        var tr_parent = $(this).parents('tr');
        var product = tr_parent.find('.products select option:selected').attr('data-product');
        var carpet = tr_parent.find('.carpet-color select option:selected').attr('data-carpet-color');
        var tangled = tr_parent.find('.tangled-color select option:selected').attr('data-tangled-color');
        var flooring = tr_parent.find('.flooring select option:selected').attr('data-flooring');
        var quantity = (tr_parent.find('.numbers input').val()||'1')*1;
        if (product_setting && product_setting.length) {
            var key = null;
            var index = 0;
            var parent = $(e.target).parents('td').attr('class');
            if (parent == 'products') {//product || 
                key = 'carpet-color';
                index = 1;
            }
            if (parent == 'carpet-color') {//product && carpet
                key = 'tangled-color';
                index = 2;
            }
            if (parent == 'tangled-color') {//product && carpet && tangled
                key = 'flooring';
                index = 3;
            }
            if (key) {
                var options = null;
                var allowed_ids = product_setting.filter(x => x.indexOf(product)>=0).map(x => x.split('-')[index]);
                if (index == 1) {
                    allowed_ids = product_setting.filter(x => x.indexOf(product)>=0).map(x => x.split('-')[index]);
                    options = setting_data.carpet_color.filter(x => allowed_ids.includes(x.id));
                    $(tr_parent).find('.carpet-color select').html(`<option value="">- Chọn -</option>`+options.map(x => `<option value="${x.id}" data-${key}="${x.id}">${x.name}</option>`).join(''));
                    $(tr_parent).find('.tangled-color select').html(`<option value="">- Chọn -</option>`).val('').trigger('change');
                    $(tr_parent).find('.flooring select').html(`<option value="">- Chọn -</option>`).val('').trigger('change');
                }
                if (index == 2) {
                    allowed_ids = product_setting.filter(x => x.indexOf(product)>=0 && x.indexOf(carpet)>=0).map(x => x.split('-')[index]);
                    options = setting_data.tangled_color.filter(x => allowed_ids.includes(x.id));
                    $(tr_parent).find('.tangled-color select').html(`<option value="">- Chọn -</option>`+options.map(x => `<option value="${x.id}" data-${key}="${x.id}">${x.name}</option>`).join(''));
                    $(tr_parent).find('.flooring select').html(`<option value="">- Chọn -</option>`).val('').trigger('change');
                }
                if (index == 3) {
                    allowed_ids = product_setting.filter(x => x.indexOf(product)>=0 && x.indexOf(carpet)>=0 && x.indexOf(tangled)>=0).map(x => x.split('-')[index]);
                    options = setting_data.flooring.filter(x => allowed_ids.includes(x.id));
                    $(tr_parent).find('.flooring select').html(`<option value="">- Chọn -</option>`+options.map(x => `<option value="${x.id}" data-${key}="${x.id}">${x.name}</option>`).join(''));
                }
                $(tr_parent).find('.'+key+' select').select2({placeholder: "- Chọn -",allowClear: true});
            }
        }

        $.ajax({
            url: '/xadmin/api/get-product-listed',
            method: 'POST',
            data: {
                product: product, carpet_color: carpet, tangled_color: tangled, flooring: flooring, type:'price'
            },
            success: function(data) {
                tr_parent.find('.listed_price input').val(formatNumber(parseInt(data)*quantity));
                updateTotal();
            }
        })

        $.ajax({
            url: '/xadmin/api/get-product-listed',
            method: 'POST',
            data: {
                product: product, carpet_color: carpet, tangled_color: tangled, flooring: flooring, type:'default'
            },
            success: function(data) {
                if (product&&carpet&&tangled&&flooring&&data==='0') {
                    toastr['error']('Sản phẩm chưa có giá vốn mặc định');
                }
                tr_parent.find('.capital_default input').val(formatNumber(parseInt(data)*quantity));
                updateTotal();
            }
        })
    });
    $("body").on("change", ".products select, .carpet-color select, .tangled-color select, .flooring select,.numbers input", function(){
    });

    function update_price_contract() {
		var total_price 		    = $('input[name="total_price_product"]').val();
		var total = 0;
		total = parseInt(total) + parseInt(total_price);
		$('input[name="price_total"]').autoNumeric('set', total);
    }

    //tổng tiền của mỗi sản phảm
    function updatePrice(){
        var tr_parent = element.parents("tr");
        var number = parseInt(tr_parent.find(".numbers input").val());
        if(!number || number < 0){
            number = 1;
            tr_parent.find(".numbers input").val(number);
        }      
        var price = parseInt(tr_parent.find(".price input").val().replace(/,/gm,'')*1);
        if(!price || price < 0){
            price = 0;
            tr_parent.find(".price input").val(price);
        } 
        tr_parent.find(".total input").val(formatNumber(number*price));
    };

    //tổng tiền của tất cả sác sản phẩm chưa trừ chiết khấu
    function updatePriceProduct(){
        var total_price_product = 0;
        $.each($('.product_row'), function (index, value) {
            var p = $(this).find('.price input').val() ? $(this).find('.price input').val().replace(/,/gm,'')*1 : 0;
            var numbs = $(this).find('.numbers input').val() ? $(this).find('.numbers input').val() : 0;
            total_price_product += (parseInt(p)*parseInt(numbs));
        });
        //$(".total_price_product").html(total_price_product);
        $("input[name=total_price_product]").val(total_price_product);
    }

    //tổng số lượng của tất cả sác sản phẩm 
    function updateNumberProduct(){
        var total_number_product = 0;
        $.each($('.product_row'), function (index, value) {
            var numbs = $(this).find('.numbers input').val() ? $(this).find('.numbers input').val() : 0;
            total_number_product += parseInt(numbs);
        });
        $(".total_number_product").html(total_number_product);
        $("input[name=total_number_product]").val(total_number_product);
            
    }

    // Cập nhật lại giảm giá cho từng sản phẩm - NTD
    function updateSalePriceProduct(){
        var salePrice = 0;
        $.each($('.product_row'), function (index, value) {
            var numbs = $(this).find('.numbers input').val() ? $(this).find('.numbers input').val() : 0;
            total_number_product += parseInt(numbs);
        });
        $(".total_number_product").html(total_number_product);
        $("input[name=total_number_product]").val(total_number_product);

    }

    // hàm tính tiền cho bảng sản phẩm
    $("body").on("change", ".price input", function(){
        var tr_parent = $(this).parents("tr");
        var price = parseInt(tr_parent.find(".price input").val().replace(/,/gm,'')*1);
        if(!price || price < 0){
            price = 0;
            tr_parent.find(".price input").val(price);
        } 
        tr_parent.find(".total input").val(formatNumber(price));
        var listed_price = parseInt(tr_parent.find(".listed_price input").val().replace(/,/gm,'')*1);
        var sale_price = listed_price - price;
        console.log(listed_price,price,sale_price);
        tr_parent.find(".sale_price input").val(formatNumber(sale_price));

        var vat = parseInt(tr_parent.find(".vat input").val().replace(/,/gm,'')*1);
        if(!vat || vat < 0){
            vat = 0;
        }
        total = price + vat;
        tr_parent.find(".total input").val(formatNumber(total));


        updatePriceProduct();
        updateNumberProduct();
        updateTotal();
    });

    $("body").on("change", ".vat input", function(){
        var total = 0;
        var tr_parent = $(this).parents("tr");
        var price = parseInt(tr_parent.find(".price input").val().replace(/,/gm,'')*1);
        var vat = parseInt($(this).val().replace(/,/gm,'')*1);
        if (isNaN(vat) || vat <= 0) {
            vat = 0;
        }
        total = price + vat;
        tr_parent.find(".total input").val(formatNumber(total));
        updatePriceProduct();
        updateTotal();
    });

    //Nút thêm một hàng trong bảng sản phẩm
    $('#add_row_product').on('click', function(){
        var table = $(this).parent().find('.table-product');
        table.find('select.select2').select2('destroy');
        var tr    = $(".row_product_add");

        var clone = tr.clone();
        clone.attr('class','product_row');
        clone.insertBefore(".row_product_add");
        clone.find('input').val('');
        clone.find('select.select2').val('');
        table.find('select.select2').select2();

        format_to_money();
    });

    //Xóa hàng trong bảng sản phẩm
    $('body').on('click', '.delete-row', function(){
        deleteTr($(this).parents('tr'));
    });

    function deleteTr(tr_parent){
        var row = $('.product_row').length;
        if(row > 1){
            tr_parent.remove();
        }else{
            tr_parent.find('.price input').val('');
            tr_parent.find('.numbers input').val('');
            tr_parent.find('.total input').val('');
            tr_parent.find('.select2').val(null).trigger('change');
        }
        updatePriceProduct();
        updateNumberProduct();
        updateTotal();
    }

    //tổng tiền của hóa đơn sau khi trừ chiết khấu
    function updateTotal(){
        var total_price = 0;
        var total_price_sell = 0;
        var total_listed_price = 0;
        $.each($('.product_row'), function (index, value) {
            var price = $(this).find('.total input').val() ? $(this).find('.total input').val() : 0;
            var price_sell = $(this).find('.price input').val() ? $(this).find('.price input').val().replace(/,/gm,'')*1 : 0;
            var price_listed = $(this).find('.listed_price input').val() ? $(this).find('.listed_price input').val().replace(/,/gm,'')*1 : 0;
            total_price += parseInt(unFormatNumber(price));
            total_price_sell += parseInt(unFormatNumber(price_sell));
            total_listed_price += parseInt(unFormatNumber(price_listed));
        });

        $(".total_price").html(formatNumber(total_price));
        $(".total-listed-price").html(formatNumber(total_listed_price));
        $(".total-price-sell").html(formatNumber(total_price_sell));
        $('input[name=total_price]').val(total_price);
        $('input[name=price_total]').autoNumeric('set', total_price);
    }

    $(document).ready(function() {
        updateTotal();
    })
<?php $this->headScript()->captureEnd() ?>

