<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'warehouse')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần cập nhật <a href="'. URL_FILES .'/template/Mau_nhap_don_hang_ton_kho.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => '', 'boxClass' => 'col-md-12'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->sheetData)) {  
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<tr>
									<th class="col-80">Công cụ</th>
            						<th class="col-50">STT</th>
            						<th>Ngày lên đơn</th>
            						<th>Cơ sở</th>
            						<th>Tên sản phẩm</th>
            						<th>Số lượng</th>
            						<th>CM sản phẩm</th>
            						<th>Tên xe<br>năm sản xuất</th>
            						<th>Màu thảm</th>
            						<th>CM Thảm</th>
            						<th>Màu rối</th>
            						<th>CM rối</th>
            						<th>Loại sản phẩm</th>
            						<th>giá niêm yết</th>
            						<th>Giá bán</th>
            						<th>Giá vốn</th>
            						<th>Ghi chú</th>
                                    <th>Giá vốn mặc định</th>
            					</tr>
            				</thead>
            				<tbody>
            					<?php
            					$index = 0;
            					foreach ($this->sheetData AS $key => $val) {
                                    if ($key != 1) {
                                        $index++;
            					?>
								<tr id="tr_<?php echo $index;?>" data-index="<?php echo $index;?>">
									<td><a href="javascript:;" data-index="<?php echo $index;?>" class="btn btn-xs default">Import</a></td>
        							<td><?php echo $index;?></td>
        							<td><span class="date"><?php echo trim($val['B']);?></span></td> <!--Ngày -->
        							<td><span class="sale_branch_id"><?php echo trim($val['C']);?></span></td><!--Cơ sở -->

        							<td><span class="product"><?php echo trim($val['D']);?></span></td><!--Tên sản phẩm -->
        							<td><span class="quantity"><?php echo trim($val['E']);?></span></td><!--Số lượng -->
        							<td><span class="number_production"><?php echo trim($val['F']);?></span></td><!--cm sản phẩm -->
        							<td><span class="product_name"><?php echo trim($val['G']);?></span></td><!--Tên xe năm sản xuất -->
        							<td><span class="carpet_color_id"><?php echo trim($val['H']);?></span></td><!--Màu thảm -->
        							<td><span class="number_carpet"><?php echo trim($val['I']);?></span></td><!--cm thảm -->
        							<td><span class="tangled_color_id"><?php echo trim($val['J']);?></span></td><!--màu rối -->
        							<td><span class="number_tangled"><?php echo trim($val['K']);?></span></td><!--cm rối -->
        							<td><span class="flooring_id"><?php echo trim($val['L']);?></span></td><!--loại sản phẩm -->
        							<td><span class="listed_price"><?php echo trim($val['M']);?></span></td><!--giá niêm yết -->
        							<td><span class="price"><?php echo trim($val['N']);?></span></td><!--giá bán -->
        							<td><span class="total_production"><?php echo trim($val['O']);?></span></td><!--giá vốn -->
        							<td><span class="sale_note"><?php echo trim($val['P']);?></span></td><!--Ghi chú -->
        							<td><span class="capital_default"><?php echo trim($val['Q']);?></span></td><!--Giá vốn mặc định -->
        						</tr>
        						<?php
            					    }
            					} 
        						?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
	<?php
	if(!empty($this->import) && !empty($this->sheetData)) {
	?>
	function startImportContact(index) {
		var item = '#tr_'+ index;

		if($(item).size() > 0) {
		    var data = {
		    	'type': $('select[name="type"]').val(),
		    };
		    $(item +' span').each(function() {
		        data[$(this).attr('class')] = $(this).text();
		    });
            $.ajax({
    			url: "<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action']));?>",
    			type: 'POST',
    			data: data,
    			beforeSend: function() {
    				$(item + ' .btn').html('Đang xử lý ...').removeClass('default').addClass('yellow');
    			},
    			success: function(result) {
    				setTimeout(function(){
    					$(item).removeClass('active');
    					if(result == 'Hoàn thành') {
    						$(item + ' .btn').html('Hoàn thành').removeClass('yellow').addClass('green');
    					} else {
    						$(item + ' .btn').html(result).removeClass('yellow').addClass('red');
    					}

						var index_next = parseInt(index) + 1;
    				    startImportContact(index_next);
    			    }, 100);
    			}
    		});
		} else {
			alert('Import thành công');
		}
	}
    startImportContact(1);
    <?php
	}
    ?>
<?php $this->headScript()->captureEnd() ?>