<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần cập nhật <a href="'. URL_FILES .'/template/Mau_nhap_don_hang_co_san.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => '', 'boxClass' => 'col-md-12'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->sheetData)) {  
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<tr>
									<th class="col-80">Công cụ</th>
            						<th class="col-50">STT</th>
            						<th>Ngày lên đơn</th>
            						<th>Mã vận đơn</th>
            						<th>Mã đơn hàng</th>
            						<th>Tổng giá trị</th>
            						<th>Đặt cọc</th>
            						<th>Phụ phí không<br>tính doanh thu</th>
            						<th>Số tiền thu</th>
            						<th>Số tiền nợ</th>
            						<th>Điện thoại khách hàng</th>
            						<th>Mã NV MKT</th>
            						<th>Mã NV sales</th>
            						<th>Nhóm SP<br>quan tâm</th>
            						<th>Trạng thái<br>sản xuất</th>
            						<th>Trạng thái<br>giục đơn</th>
            						<th>Trạng thái<br>kế toán</th>
            						<th>Loại đơn<br>sản xuất</th>
            						<th>Nhân viên giao hàng</th>
            						<th>Cơ sở</th>
            						<th>Đội nhóm</th>
            						<th>Đơn bảo hành</th>
            						<th>Mã đơn cũ</th>
            						<th>Ngày bảo hành</th>
            						<th>Nội dung<br>bảo hành</th>
            						<th>Ghi chú sales</th>
            						<th>Ghi chú<br>sản xuất</th>
            						<th>Loại khách hàng</th>
            						<th>Tên sản phẩm</th>
            						<th>Số lượng</th>
            						<th>CM sản phẩm</th>
            						<th>Tên xe<br>năm sản xuất</th>
            						<th>Mã đơn có sẵn</th>
            						<th>Màu thảm</th>
            						<th>CM Thảm</th>
            						<th>Màu rối</th>
            						<th>CM rối</th>
            						<th>Loại sản phẩm</th>
            						<th>giá niêm yết</th>
            						<th>Giá bán</th>
            						<th>Tiền thuế VAT</th>
            						<th>Giá vốn</th>
            						<th>Loại vận chuyển</th>
            					</tr>
            				</thead>
            				<tbody>
            					<?php
            					$index = 0;
            					foreach ($this->sheetData AS $key => $val) { 
            					    if((int)$val['J'] > 0) {
            							$index++;
            							
                					    $phone = $number->formatToData(trim($val['J']));
            							if(substr($phone, 0, 1) != '0') {
            								$phone = '0'. $phone;
            						}
            					?>
								<tr id="tr_<?php echo $index;?>" data-index="<?php echo $index;?>">
									<td><a href="javascript:;" data-index="<?php echo $index;?>" class="btn btn-xs default">Import</a></td>
        							<td><?php echo $index;?></td>
        							<td><span class="date"><?php echo trim($val['B']);?></span></td> <!--Ngày -->
        							<td><span class="bill_code"><?php echo trim($val['C']);?></span></td><!--Mã vận đơn -->
        							<td><span class="code"><?php echo trim($val['D']);?></span></td><!--Mã đơn hàng -->
        							<td><span class="price_total"><?php echo trim($val['E']);?></span></td><!--Tổng giá trị -->
        							<td><span class="price_deposits"><?php echo trim($val['F']);?></span></td><!--Tiền đặt cọc -->
        							<td><span class="price_surcharge"><?php echo trim($val['G']);?></span></td><!--Phụ phí -->
        							<td><span class="price_paid"><?php echo trim($val['H']);?></span></td><!--Số tiền thu -->
        							<td><span class="price_owed"><?php echo trim($val['I']);?></span></td><!--Số tiền còn nợ -->
                                    <td><span class="phone"><?php echo $phone;?></span></td><!--Điện thoại -->
        							<td><span class="marketer_id"><?php echo trim($val['K']);?></span></td><!--MKT -->
        							<td><span class="user_id"><?php echo trim($val['L']);?></span></td><!--sales -->
        							<td><span class="product_group_id"><?php echo trim($val['M']);?></span></td><!--Nhóm sp quan tâm -->
        							<td><span class="production_department_type"><?php echo trim($val['N']);?></span></td><!--Trạng thái sx -->
        							<td><span class="status_check_id"><?php echo trim($val['O']);?></span></td><!--Trạng thái giục đơn -->
        							<td><span class="status_acounting_id"><?php echo trim($val['P']);?></span></td><!--Trạng thái kế toán -->
        							<td><span class="production_type_id"><?php echo trim($val['Q']);?></span></td><!--Loại đơn sản xuất -->
        							<td><span class="shipper_id"><?php echo trim($val['R']);?></span></td><!--Nhân viên giao hàng -->
        							<td><span class="sale_branch_id"><?php echo trim($val['S']);?></span></td><!--Cơ sở -->
        							<td><span class="sale_group_id"><?php echo trim($val['T']);?></span></td><!--Đội nhóm -->
        							<td><span class="status_guarantee_id"><?php echo trim($val['U']);?></span></td><!--Đơn bảo hành -->
        							<td><span class="code_old"><?php echo trim($val['V']);?></span></td><!--Mã đơn cũ -->
        							<td><span class="guarantee_date"><?php echo trim($val['W']);?></span></td><!--Ngày bảo hành -->
        							<td><span class="guarantee_note"><?php echo trim($val['X']);?></span></td><!--Nội dung bảo hành -->

                                    <td><span class="sale_note"><?php echo trim($val['Y']);?></span></td><!--Ghi chú sale -->
        							<td><span class="production_note"><?php echo trim($val['Z']);?></span></td><!--Ghi chú sản xuất -->
        							<td><span class="contact_type"><?php echo trim($val['AA']);?></span></td><!--Loại khách hàng -->

        							<td><span class="product"><?php echo trim($val['AB']);?></span></td><!--Tên sản phẩm -->
        							<td><span class="quantity"><?php echo trim($val['AC']);?></span></td><!--Số lượng -->
        							<td><span class="number_production"><?php echo trim($val['AD']);?></span></td><!--cm sản phẩm -->
        							<td><span class="product_name"><?php echo trim($val['AE']);?></span></td><!--Tên xe năm sản xuất -->
        							<td><span class="stock"><?php echo trim($val['AF']);?></span></td><!--Mã đơn có sẵn -->
        							<td><span class="carpet_color_id"><?php echo trim($val['AG']);?></span></td><!--Màu thảm -->
        							<td><span class="number_carpet"><?php echo trim($val['AH']);?></span></td><!--cm thảm -->
        							<td><span class="tangled_color_id"><?php echo trim($val['AI']);?></span></td><!--màu rối -->
        							<td><span class="number_tangled"><?php echo trim($val['AJ']);?></span></td><!--cm rối -->
        							<td><span class="flooring_id"><?php echo trim($val['AK']);?></span></td><!--loại sản phẩm -->
        							<td><span class="listed_price"><?php echo trim($val['AL']);?></span></td><!--giá niêm yết -->
        							<td><span class="price"><?php echo trim($val['AM']);?></span></td><!--giá bán -->
        							<td><span class="vat"><?php echo trim($val['AN']);?></span></td><!--vat -->
        							<td><span class="total_production"><?php echo trim($val['AO']);?></span></td><!--giá vốn -->
        							<td><span class="transport_id"><?php echo trim($val['AP']);?></span></td><!-- Loại vận chuyển -->
        						</tr>
        						<?php
            					    }
            					} 
        						?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
	<?php
	if(!empty($this->import) && !empty($this->sheetData)) {
	?>
	function startImportContact(index) {
		var item = '#tr_'+ index;

		if($(item).size() > 0) {
		    var data = {
		    	'type': $('select[name="type"]').val(),
		    };
		    $(item +' span').each(function() {
		        data[$(this).attr('class')] = $(this).text();
		    });
            $.ajax({
    			url: "<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action']));?>",
    			type: 'POST',
    			data: data,
    			beforeSend: function() {
    				$(item + ' .btn').html('Đang xử lý ...').removeClass('default').addClass('yellow');
    			},
    			success: function(result) {
    				setTimeout(function(){
    					$(item).removeClass('active');
    					if(result == 'Hoàn thành') {
    						$(item + ' .btn').html('Hoàn thành').removeClass('yellow').addClass('green');
    					} else {
    						$(item + ' .btn').html(result).removeClass('yellow').addClass('red');
    					}

						var index_next = parseInt(index) + 1;
    				    startImportContact(index_next);
    			    }, 100);
    			}
    		});
		} else {
			alert('Import thành công');
		}
	}
    startImportContact(1);
    <?php
	}
    ?>
<?php $this->headScript()->captureEnd() ?>