<?php
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('section' => 'Thông tin chung', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('name'), 'label' => 'Tên', 'validate' => array('require' => true)),
        array('element' => $myForm->get('date'), 'label' => 'Ngày cập nhật'),
        array('element' => $myForm->get('status'), 'label' => 'Tình trạng'),
        array('section' => 'Kịch bản', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('content_by'), 'label' => 'Người viết kịch bản'),
        array('element' => $myForm->get('content_link'), 'label' => 'Link xem chi tiết'),
        array('element' => $myForm->get('content_date'), 'label' => 'Ngày viết'),
        array('element' => $myForm->get('content_status'), 'label' => 'Trạng thái'),
        array('section' => 'Quay', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('camera_by'), 'label' => 'Người quay'),
        array('element' => $myForm->get('camera_date'), 'label' => 'Ngày quay'),
        array('element' => $myForm->get('camera_status'), 'label' => 'Trạng thái'),
        array('section' => 'Dựng video', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('editor_by'), 'label' => 'Người dựng video'),
        array('element' => $myForm->get('editor_date'), 'label' => 'Ngày dựng'),
        array('element' => $myForm->get('editor_status'), 'label' => 'Trạng thái'),
        array('section' => 'Youtube', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('youtube_by'), 'label' => 'Upload bởi'),
        array('element' => $myForm->get('youtube_link'), 'label' => 'Link'),
        array('element' => $myForm->get('youtube_date'), 'label' => 'Ngày đăng'),
        array('element' => $myForm->get('youtube_status'), 'label' => 'Trạng thái'),
        array('element' => $myForm->get('youtube_view'), 'label' => 'Lượt xem'),
        array('element' => $myForm->get('youtube_comment'), 'label' => 'Comment'),
        array('element' => $myForm->get('youtube_like'), 'label' => 'Like'),
        array('element' => $myForm->get('youtube_dislike'), 'label' => 'Dislike'),
        array('section' => 'Facebook', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('facebook_by'), 'label' => 'Đăng bởi'),
        array('element' => $myForm->get('facebook_link'), 'label' => 'Link'),
        array('element' => $myForm->get('facebook_date'), 'label' => 'Ngày đăng'),
        array('element' => $myForm->get('facebook_status'), 'label' => 'Trạng thái'),
        array('element' => $myForm->get('facebook_like'), 'label' => 'Like'),
        array('element' => $myForm->get('facebook_comment'), 'label' => 'Comment'),
        array('element' => $myForm->get('facebook_share'), 'label' => 'Share'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form form-tab" role="form" name="adminForm" id="adminForm">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
	</div>
</form>