<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần import check dữ liệu <a href="'. URL_FILES .'/demo/CheckContact.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => '&nbsp;'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->sheetData)) {  
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<tr>
            					    <th class="col-80">Công cụ</th>
            						<th class="col-50">STT</th>
            						<th>Số điện thoại</th>
            						<th>Ngày</th>
            						<th>Họ tên</th>
            						<th>Email</th>
            						<th>Họ tên trên hệ thồng</th>
            						<th>Email trên hệ thống</th>
            						<th>Nguồn trên hệ thống</th>
            					</tr>
            				</thead>
            				<tbody>
            					<?php
            					$index = 0;
            					foreach ($this->sheetData AS $key => $val) { 
            					    if((int)$val['C'] > 0) {
            							$index++;
            							
                					    $phone = $number->formatToData(trim($val['C']));
            							if(substr($phone, 0, 1) != '0') {
            								$phone = '0'. $phone;
            							}
            					?>
            					<tr id="tr_<?php echo $index;?>" data-index="<?php echo $index;?>">
            					    <td><a href="javascript:;" data-index="<?php echo $index;?>" class="btn btn-xs default">Check info</a></td>
        							<td><?php echo $index;?></td>
        							<td><span class="phone"><?php echo $phone;?></span></td>
        							<td><span class="created"><?php echo $val['B'];?></span></td>
        							<td><span class="name"><?php echo trim($val['D']);?></span></td>
        							<td><span class="email"><?php echo trim($val['E']);?></span></td>
        							<td><span class="name_data"></span></td>
        							<td><span class="email_data"></span></td>
        							<td><span class="source_group_data"></span></td>
        						</tr>
        						<?php
            					    }
            					} 
        						?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
	<?php
	if(!empty($this->import) && !empty($this->sheetData)) {  
	?>
	function startImportContact(index) {
		var item = '#tr_'+ index;
		
		if($(item).size() > 0) {
		    var data = {};
		    $(item +' span').each(function() {
		        data[$(this).attr('class')] = $(this).text();
		    });
            $.ajax({
    			url: "<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action']));?>",
    			type: 'POST',
    			data: data,
    			beforeSend: function() {
    				$(item + ' .btn').html('Đang xử lý ...').removeClass('default').addClass('yellow');
    			},
    			success: function(result) {
    			value = JSON.parse(result);
    				setTimeout(function(){
    					$(item).removeClass('active');
    					$(item + ' .btn').html('Hoàn thành').removeClass('yellow').addClass('green');
						$(item + ' .name_data').html(value.name);
						$(item + ' .email_data').html(value.email);
						$(item + ' .source_group_data').html(value.source_group);
    				    var index_next = parseInt(index) + 1;
    				    startImportContact(index_next); 
    			    }, 100);
    			}
    		});
		} else {
		   alert('Kiểm tra thành công');
		}
	}
    startImportContact(1);
    <?php
	}
    ?>
<?php $this->headScript()->captureEnd() ?>