<?php
    $userInfo = new \ZendX\System\UserInfo();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    // Set lại các giá trị của từng element
    $myForm->get('location_district_id')->setAttributes(array('data-parent' => $myForm->get('location_city_id')->getValue()));
    $myForm->get('location_town_id')->setAttributes(array('data-parent' => $myForm->get('location_district_id')->getValue()));
    if(!empty($this->item['location_district_id'])) {
        $myForm->get('location_district_id')->setAttributes(array('data-text-label' => $this->document[$this->item['location_district_id']]['name']));
        $myForm->get('location_town_id')->setAttributes(array('data-text-label' => $this->document[$this->item['location_town_id']]['name']));
    }
    
    $elements = array(
        array('section' => 'Nhập thông tin chung', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('phone'), 'label' => 'Số điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('sex'), 'label' => 'Giới tính', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('product_group_id'), 'label' => 'Sản phẩm quan tâm', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('type'), 'label' => 'Phân loại khách hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
//        array('element' => $myForm->get('marketer_id'), 'label' => 'Nhân viên Marketing', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('contact_group'), 'label' => 'Nhóm khách hàng', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('name'), 'label' => 'Họ và tên', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('location_city_id'), 'label' => 'Tỉnh thành', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('location_district_id'), 'label' => 'Quận huyện', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('location_town_id'), 'label' => 'Phường xã', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('address'), 'label' => 'Địa chỉ nơi ở', 'boxClass' => 'col-md-2'),

        array('element' => $myForm->get('email'), 'label' => 'Email', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('birthday_year'), 'label' => 'Năm sinh', 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('facebook'), 'label' => 'Facebook', 'boxClass' => 'col-md-2'),
//        array('element' => $myForm->get('source_group_id'), 'label' => 'Nguồn liên hệ', 'boxClass' => 'col-md-2'),
//        array('element' => $myForm->get('source_known_id'), 'label' => 'Nguồn biết đến', 'boxClass' => 'col-md-2'),
//        array('element' => $myForm->get('job'), 'label' => 'Nghề nghiệp', 'boxClass' => 'col-md-2'),
//        array('element' => $myForm->get('license_plate'), 'label' => 'Biển số xe', 'boxClass' => 'col-md-2'),
//        array('element' => $myForm->get('marketer_id'), 'label' => 'Nhân viên MKT', 'boxClass' => 'col-md-2'),
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
//        array('div' => '', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('note'), 'label' => 'Ghi chú', 'boxClass' => 'col-md-12'),
//        array('element' => $myForm->get('content'), 'label' => 'Nội dung tư vấn', 'validate' => array('require' => true), 'boxClass' => 'col-md-6'),

        array('section' => 'Thêm lịch sử chăm sóc mới', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('history_action_id'), 'label' => 'Hành động', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('history_result_id'), 'label' => 'Kết quả', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('history_type_id'), 'label' => 'Phân loại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('sales_expected'), 'label' => 'Doanh số tạm tính', 'validate' => array('require' => true), 'boxClass' => 'col-md-2 hidden', 'boxId' => 'sales_expected'),
        array('element' => $myForm->get('history_return'), 'label' => 'Hẹn ngày chăm sóc lại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('history_success'), 'label' => 'Trạng thái chăm sóc', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('history_content'), 'label' => 'Nội dung/Ghi chú', 'validate' => array('require' => true), 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    
    if(!empty($this->item)) {
        $elements[] = array('section' => 'Danh sách lịch sử chăm sóc', 'boxClass' => 'col-md-12');
        $elements[] = array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'load_history', 'boxStyle' => 'margin-bottom: 50px;');
    }
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
	// Xử lý load tỉnh thành
	$('select[name="location_city_id"]').change(function() {
		var select = 'input[name="location_district_id"]';
		var parent = $(select).parent();
		$('.select2-container', parent).select2('val', '');
		$(select).attr('data-parent', $(this).val());
    });

    $('input[name="location_district_id"]').change(function() {
        var select = 'input[name="location_town_id"]';
        var parent = $(select).parent();
        $('.select2-container', parent).select2('val', '');
        $(select).attr('data-parent', $(this).val());
    });
    
    $('select[name="type"]').change(function() {
    	if($(this).val() == 'lost') {
        	$('#input_lost').removeClass('hidden');
    	} else {
    		$('#input_lost').addClass('hidden');
    	}
    });
    <?php
    if($myForm->get('type')->getValue() == 'lost') {
    ?>
    $('#input_lost').removeClass('hidden');
    <?php
    } else {
    ?>
    $('#input_lost').addClass('hidden');
    <?php
    }
    ?>
    
    // Check phân loại
    function checkSubject(id) {
		if(id == 'sinh-vien' || id == 'nguoi-di-lam') {
			$('#school_name').removeClass('hidden');
			$('#major_name').removeClass('hidden');
			$('#class_name').addClass('hidden');
		} else if (id == 'hoc-sinh') {
			$('#major_name').addClass('hidden');
			$('#school_name').removeClass('hidden');
			$('#class_name').removeClass('hidden');
		} else {
		    $('#school_name').addClass('hidden');
			$('#major_name').addClass('hidden');
			$('#class_name').addClass('hidden');
		}
    }
    var subject_id = '<?php echo $myForm->get('subject_id')->getValue(); ?>';
    if(subject_id) {
        checkSubject(subject_id);
    }
    $('select[name="subject_id"]').change(function() {
        checkSubject($(this).val());
    });
    
    <?php if(empty($myForm->get('id')->getValue())) {?>
    <?php }?>
    
    <?php
    if(!empty($this->item)) { 
    ?>
    load_action('#load_history', '<?php echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'list-history'));?>', {contact_id: '<?php echo $this->item['id'];?>'});
    <?php
    } 
    ?>
    function optionBill(type) {
        if(type == '<?php echo DA_CHOT;?>') {
            $('#sales_expected').removeClass('hidden');
        }
        else {
            $('#sales_expected').addClass('hidden');
        }
    }

    optionBill($('select[name="history_type_id"]').find('option:selected').attr('data-code'));

    $('select[name="history_type_id"]').change(function() {
        console.log($(this).find('option:selected').attr('data-code'));
        optionBill($(this).find('option:selected').attr('data-code'));
    });
<?php $this->headScript()->captureEnd() ?>