<?php
    $myForm = $this->myForm;
    $myForm->prepare();

    $history_contract = $this->history_contract;
    
    $elements = array(
        array('element' => $myForm->get('history_content'), 'label' => 'Nội dung ghi chú', 'boxClass' => 'col-md-12', 'validate' => array('require' => true)),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true))
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
    if(!empty($history_contract)) {
        $xhtmlHead = '<tr>';
        $xhtmlHead .= '<th>Ngày chăm sóc</th>';
        $xhtmlHead .= '<th>Người chăm sóc</th>';
        $xhtmlHead .= '<th>Nội dung</th>';
        $xhtmlHead .= '</tr>';

        foreach ($history_contract as $key => $value){
            $user_created = $this->user[$value['created_by']]->name;
            $xhtmlItems .= '<tr>
    							<td>'. $value['created'] .'</td>
    							<td>'. $user_created .'</td>
    							<td>'. $value['content'] .'</td>
                            </tr>';
        }
    }
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
        <?php if(!empty($history_contract)) { ?>
            <div class="table-manager" id="table-manager">
                <div class="table-scrollable">
                    <table class="table table-striped table-bordered table-hover">
                        <thead>
                        <?php echo $xhtmlHead;?>
                        </thead>
                        <tbody>
                        <?php echo $xhtmlItems;?>
                        </tbody>
                    </table>
                </div>
            </div>
        <?php } ?>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>
