<?php
$dateFormat = new \ZendX\Functions\Date();
$debt_item = $this->debt_item;
$invoice_type = $this->invoice_type;
$show_invoice_vat = $this->item['invoice_type'] == 'vat' ? '' : 'hidden';
$show_option_vat = $this->item['option_vat'] == 'yes' ? '' : 'hidden';
$option_vat = array('yes' => 'Lấy VAT', 'no' => 'Không lấy VAT');


$elementsContact = array(
    array('section' => 'Thông tin khách hàng', 'boxClass' => 'col-md-12'),
    array('element' => $this->item['name'], 'label' => 'Họ và tên', 'boxClass' => 'col-md-3'),
//    array('element' => $this->customer_type[$this->item['customer_type_id']]['name'], 'label' => 'Nhóm khách hàng', 'boxClass' => 'col-md-2'),
    array('element' => $this->contact['phone'], 'label' => 'Số điện thoại', 'boxClass' => 'col-md-2'),
    array('element' => $this->warehouse[$this->item['inventory_id']]['name'], 'label' => 'Kho hàng', 'boxClass' => 'col-md-2'),
    array('element' => $this->sale_branch[$this->item['sale_branch_id']]['name'], 'label' => 'Chi nhánh', 'boxClass' => 'col-md-2'),
    array('element' => $this->item['sale_note'] ? $this->item['sale_note'] : '.', 'label' => 'Ghi chú', 'boxClass' => 'col-md-3'),
    array('element' => $this->location_city[$this->item['location_city_id']]['name'], 'label' => 'Tỉnh thành', 'boxClass' => 'col-md-3'),
    array('element' => $this->location_district[$this->item['location_district_id']]['name'], 'label' => 'Phường xã', 'boxClass' => 'col-md-3'),
    array('element' => $this->item['address'], 'label' => 'Địa chỉ nơi ở', 'boxClass' => 'col-md-3'),
    array('element' => $this->fee_type[$this->item['fee_type']]['name'], 'label' => 'Người trả phí', 'boxClass' => 'col-md-3'),
    array('element' => $this->production_type[$this->item['production_type_id']]['name'], 'label' => 'Loại đơn', 'boxClass' => 'col-md-3'),
    array('element' => $option_vat[$this->item['option_vat']], 'label' => 'Lấy VAT', 'boxClass' => 'col-md-3'),
    array('element' => $invoice_type[$this->item['invoice_type']]['name'], 'label' => 'Xuất hóa đơn', 'boxClass' => 'col-md-3 '.$show_option_vat),
    array('section' => 'Thông tin xuất hóa đơn', 'boxClass' => 'col-md-12 '.$show_option_vat),
    array('element' => $this->item['company_user'], 'label' => 'Họ và tên', 'boxClass' => 'col-md-4 '.$show_option_vat),
    array('element' => $this->item['company_phone'], 'label' => 'ĐT công ty', 'boxClass' => 'col-md-4 '.$show_option_vat),
    array('element' => $this->item['company_name'], 'label' => 'Tên công ty', 'boxClass' => 'col-md-4 '.$show_invoice_vat),
    array('element' => $this->item['company_mst'], 'label' => 'Mã số thuế', 'boxClass' => 'col-md-4 '.$show_invoice_vat),
    array('element' => $this->item['company_address'], 'label' => 'Địa chỉ', 'boxClass' => 'col-md-4 '.$show_option_vat),
    array('element' => $this->item['company_email'], 'label' => 'Email công ty', 'boxClass' => 'col-md-4 '.$show_invoice_vat),
);
$elementsContract = array(

    array('section' => 'Thông tin đơn hàng', 'boxClass' => 'col-md-12'),
    array('element' => $this->item['code'], 'label' => 'Mã đơn hàng', 'boxClass' => 'col-md-2'),
    array('element' => $dateFormat->formatToView($this->item['created'], 'd/m/Y H:i:s'), 'label' => 'Ngày tạo', 'boxClass' => 'col-md-2'),
    array('element' => $this->user[$this->item['user_id']]['name'], 'label' => 'Người tạo', 'boxClass' => 'col-md-2'),
    array('element' => $this->sale_group[$this->item['sale_group_id']]['name'], 'label' => 'Đội nhóm', 'boxClass' => 'col-md-2'),
//    array('element' => $this->sale_branch[$this->item['sale_branch_id']]['name'], 'label' => 'Cơ sở', 'boxClass' => 'col-md-2'),
    array('element' => '<span class="text-orange">'.$this->order_status[$this->item['state']]->name.'</span> ', 'label' => 'Trạng thái', 'boxClass' => 'col-md-2'),
);
$elementsPrice = array(
    array('section' => 'Thông tin thanh toán', 'boxClass' => 'col-md-12'),
    array('element' => '<span class="mask_currency text-green">'. $this->item['price_total'] .'</span> ', 'label' => 'Tổng tiền hàng (1)', 'boxClass' => 'col-md-4',),
    array('element' => '<span class="mask_currency text-green">'. $this->item['vat'] .'</span>', 'label' => 'VAT', 'boxClass' => 'col-md-4 '.$show_option_vat),
    array('element' => '<span class="mask_currency text-green">'. $this->item['fee_shipp'] .'</span>', 'label' => 'Phí giao hàng', 'boxClass' => 'col-md-4 hidden'),
    array('element' => '<span class="mask_currency text-green">'. $this->item['fee_other'] .'</span>', 'label' => 'Thu khác', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-purple">'. $this->item['paid_cash'] .'</span>', 'label' => 'Trả tiền mặt (2)', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-purple">'. $this->item['paid_transfer'] .'</span>', 'label' => 'Chuyển khoản (3)', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-purple">'. $this->item['discount'] .'</span>', 'label' => 'Giảm giá (4)', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-red">'. $debt_item->old_debt .'</span> ', 'label' => 'Nợ cũ (5)', 'boxClass' => 'col-md-6'),
    array('element' => '<span class="mask_currency text-orange">'. $debt_item->new_debt .'</span> ', 'label' => 'Nợ lại:', 'boxClass' => 'col-md-6'),
);
$elementsProducts = array(
    array('section' => 'Danh sách sản phẩm của đơn hàng', 'boxClass' => 'col-md-12'),
    array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'load_product'),
);
$xhtmlContact = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsContact);
$xhtmlContract = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsContract);
$xhtmlPrice = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsPrice);
$xhtmlProducts = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsProducts);

$linkEdit   = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'edit-kov', 'id' => $this->item['id']));
$linkIndex  = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index'));

$permission_ids = $this->permission_ids;
//$processing_action = array('name' => 'save', 'caption' => 'Xử lý đơn', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'processing\', \' Bạn có chắc chắn muốn chuyển trạng thái xử lý đơn hàng\');', 'class' => 'btn blue'));
//$cancel_action = array('name' => 'cancel', 'caption' => 'Hủy đơn', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'cancel\', \' Bạn có chắc chắn muốn hủy đơn hàng\');', 'class' => 'btn red'));
//$complete_action = array('name' => 'complete', 'caption' => 'Hoàn thành', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'complete\', \' Bạn có chắc chắn muốn hoàn thành đơn hàng\');', 'class' => 'btn green'));
//$edit_action = array('name' => 'edit', 'caption' => 'Sửa', 'link' => $linkEdit, 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn yellow'));

$processing_action = $cancel_action = $complete_action = $edit_action = $return_action = array();

if ($this->item['state'] == NEW_STATUS) {
    if ($this->item['created_by'] == $this->uid || in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids)) {
        $cancel_action = array('name' => 'cancel', 'caption' => 'Hủy đơn', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'cancel\', \' Bạn có chắc chắn muốn hủy đơn hàng\');', 'class' => 'btn red'));
        $edit_action = array('name' => 'edit', 'caption' => 'Sửa', 'link' => $linkEdit, 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn yellow'));
    }
}
if ($this->item['state'] == PROCESSING_STATUS) {
    if ($this->item['created_by'] == $this->uid || in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids)) {
//        $complete_action = array('name' => 'complete', 'caption' => 'Hoàn thành', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'complete\', \' Bạn có chắc chắn muốn hoàn thành đơn hàng\');', 'class' => 'btn green'));
    }
    if (in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids)) {
//        $cancel_action = array('name' => 'cancel', 'caption' => 'Hủy đơn', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'cancel\', \' Bạn có chắc chắn muốn hủy đơn hàng\');', 'class' => 'btn red'));
        $edit_action = array('name' => 'edit', 'caption' => 'Sửa', 'link' => $linkEdit, 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn yellow'));
    }
}
if ($this->item['state'] == DELIVERING_STATUS) {
    if ($this->item['created_by'] == $this->uid || in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids)) {
        $complete_action = array('name' => 'complete', 'caption' => 'Hoàn thành', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'complete\', \' Bạn có chắc chắn muốn hoàn thành đơn hàng\');', 'class' => 'btn green'));
    }
    if (in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids)) {
        $return_action = array('name' => 'return', 'caption' => 'Hoàn đơn', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitFormConfirm(\'return\', \' Bạn có chắc chắn muốn hoàn đơn hàng\');', 'class' => 'btn purple'));
        $edit_action = array('name' => 'edit', 'caption' => 'Sửa', 'link' => $linkEdit, 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn yellow'));
    }
}
if ($this->item['state'] == COMPLETE_STATUS) {
    if (in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids)) {
        $edit_action = array('name' => 'edit', 'caption' => 'Sửa', 'link' => $linkEdit, 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn yellow'));
    }
}

$arrControl = array(
    $processing_action,
    $cancel_action,
    $return_action,
    $complete_action,
    $edit_action,
    array('name' => 'close', 'caption' => 'Đóng', 'link' => $linkIndex, 'onclick' => '', 'icon' => 'fa fa-pencil', 'attributes' => array('class' => 'btn default'))
);

?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->renderCurrent('error', array('alert', 'alert-danger')); ?>
    <?php echo $this->flashMessenger()->renderCurrent('success', array('alert', 'alert-success')); ?>

    <div class="page-content">
        <div class="row">
            <div class="col-md-12">
                <?php echo $xhtmlContract;?>
            </div>
            <div class="col-md-8">
                <?php echo $xhtmlContact;?>
            </div>
            <div class="col-md-4">
                <?php echo $xhtmlPrice;?>
            </div>
            <div class="col-md-12">
                <?php echo $xhtmlProducts;?>
            </div>
        </div>
    </div>
</form>

<?php $this->headScript()->captureStart() ?>
    load_action('#load_product', '<?php echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'list-product'));?>', {contract_id: '<?php echo $this->item['id'];?>'});
<?php $this->headScript()->captureEnd() ?>