<?php
$dateFormat = new \ZendX\Functions\Date();

$contact_options = !empty($this->contact['options']) ? unserialize($this->contact['options']) : array();
$contract_options = !empty($this->item['options']) ? unserialize($this->item['options']) : array();
$contract_pending = !empty($this->item['pending']) ? unserialize($this->item['pending']) : array();
$debt_item = $this->debt_item;

$elementsContact = array(
    array('section' => 'Thông tin khách hàng', 'boxClass' => 'col-md-12'),
    array('element' => $this->item['name'], 'label' => 'Họ và tên', 'boxClass' => 'col-md-3'),
    array('element' => $this->customer_type[$this->item['customer_type_id']]['name'], 'label' => 'Nhóm khách hàng', 'boxClass' => 'col-md-3'),
    array('element' => $this->contact['phone'], 'label' => 'Số điện thoại', 'boxClass' => 'col-md-3'),
    array('element' => $this->warehouse[$this->item['inventory_id']]['name'], 'label' => 'Kho hàng', 'boxClass' => 'col-md-3'),
    array('element' => $this->location_city[$this->item['location_city_id']]['name'], 'label' => 'Tỉnh thành', 'boxClass' => 'col-md-3'),
    array('element' => $this->location_district[$this->item['location_district_id']]['name'], 'label' => 'Quận huyện', 'boxClass' => 'col-md-3'),
    array('element' => $this->location_town[$this->item['location_town_id']]['name'], 'label' => 'Phường xã', 'boxClass' => 'col-md-3'),
    array('element' => $this->item['address'], 'label' => 'Địa chỉ nơi ở', 'boxClass' => 'col-md-3')
);
$elementsContract = array(

    array('section' => 'Thông tin đơn hàng', 'boxClass' => 'col-md-12'),
    array('element' => $dateFormat->formatToView($this->item['created'], 'd/m/Y H:i:s'), 'label' => 'Ngày tạo', 'boxClass' => 'col-md-2'),
    array('element' => $this->user[$this->item['user_id']]['name'], 'label' => 'Người tạo', 'boxClass' => 'col-md-2'),
    array('element' => $this->sale_group[$this->item['sale_group_id']]['name'], 'label' => 'Đội nhóm', 'boxClass' => 'col-md-2'),
    array('element' => $this->sale_branch[$this->item['sale_branch_id']]['name'], 'label' => 'Cơ sở', 'boxClass' => 'col-md-2'),
    array('element' => $this->order_status[$this->item['state']]->name, 'label' => 'Trạng thái', 'boxClass' => 'col-md-2'),
    array('element' => $this->item['sale_note'] ? $this->item['sale_note'] : '.', 'label' => 'Ghi chú', 'boxClass' => 'col-md-2'),

    array('section' => 'Danh sách sản phẩm của đơn hàng', 'boxClass' => 'col-md-12'),
    array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'load_product'),
);
$elementsPrice = array(
    array('section' => 'Thông tin thanh toán', 'boxClass' => 'col-md-12'),
    array('element' => '<span class="mask_currency text-info">'. $debt_item->old_debt .'</span> ', 'label' => 'Nợ cũ', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-info">'. $this->item['price_total'] .'</span> ', 'label' => 'Tổng tiền hàng', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-info">'. $debt_item->new_debt .'</span> ', 'label' => 'Nợ lại', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-info">'. $this->item['paid_cash'] .'</span>', 'label' => 'Trả tiền mặt', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-purple">'. $this->item['paid_transfer'] .'</span>', 'label' => 'Chuyển khoản', 'boxClass' => 'col-md-4'),
    array('element' => '<span class="mask_currency text-info">'. $this->item['discount'] .'</span>', 'label' => 'Giảm giá', 'boxClass' => 'col-md-4'),
);
$xhtmlContact = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsContact);
$xhtmlContract = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsContract);
$xhtmlPrice = $this->partialLoop($this->params['module'] . '/partial/form-view.phtml', $elementsPrice);

?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
        <div class="title pull-left">
            <?php echo $this->caption;?>
        </div>
        <div class="control pull-right">
            <?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
        </div>
        <div class="clearfix"></div>
    </div>

    <?php echo $this->flashMessenger()->render();?>

    <div class="page-content">
        <div class="row">
            <div class="col-md-8">
                <?php echo $xhtmlContact;?>
            </div>
            <div class="col-md-4">
                <?php echo $xhtmlPrice;?>
            </div>
            <div class="col-md-12">
                <?php echo $xhtmlContract;?>
            </div>
        </div>
    </div>
</form>

<?php $this->headScript()->captureStart() ?>
    // Load danh sách sản phẩm
    load_action('#load_product', '<?php echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'list-product'));?>', {contract_id: '<?php echo $this->item['id'];?>'});
<?php $this->headScript()->captureEnd() ?>