<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );

    // Set lại các giá trị của từng element
    $myForm->get('location_district_id')->setAttributes(array('data-parent' => $myForm->get('location_city_id')->getValue()));
    $myForm->get('location_town_id')->setAttributes(array('data-parent' => $myForm->get('location_district_id')->getValue()));
    if(!empty($this->item['location_district_id'])) {
        $myForm->get('location_district_id')->setAttributes(array('data-text-label' => $this->document[$this->item['location_district_id']]['name']));
        $myForm->get('location_town_id')->setAttributes(array('data-text-label' => $this->document[$this->item['location_town_id']]['name']));
    }
    
    $elementsTop = array(
        array('section' => 'Thông tin khách hàng', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('name'), 'label' => 'Họ và tên', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('customer_type_id'), 'label' => 'Nhóm khách hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('phone'), 'label' => 'Số điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('inventory_id'), 'label' => 'Kho hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('sale_note'), 'label' => 'Ghi chú', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('location_city_id'), 'label' => 'Tỉnh thành', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('location_district_id'), 'label' => 'Quận huyện', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('location_town_id'), 'label' => 'Phường xã', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('address'), 'label' => 'Địa chỉ nơi ở', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('section' => 'Thông tin xuất hóa đơn', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('company_name'), 'label' => 'Tên công ty', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('company_mst'), 'label' => 'Mã số thuế', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('company_address'), 'label' => 'Địa chỉ', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('company_email'), 'label' => 'Email', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('company_user'), 'label' => 'Nhân viên', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('company_phone'), 'label' => 'Điện thoại', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
    );
    
    $xhtmlTop = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsTop);

    $elementsBottom = array(
        array('section' => 'Thành tiền hóa đơn', 'boxClass' => 'col-md-12'),
        array('element' => $myForm->get('price_total'), 'label' => 'Tổng tiền hàng', 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('vat'), 'label' => 'VAT', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('fee_shipp'), 'label' => 'Phí giao hàng', 'validate' => array('require' => true), 'boxClass' => 'col-md-4 hidden'),
        array('element' => $myForm->get('fee_other'), 'label' => 'Thu khác', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('paid_cash'), 'label' => 'Trả tiền mặt', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('paid_transfer'), 'label' => 'Chuyển khoản', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('discount'), 'label' => 'giảm giá', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('invoice_type'), 'label' => 'Xuất hóa đơn', 'validate' => array('require' => true), 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('amount_owed'), 'label' => 'Nợ cũ', 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('new_debt'), 'label' => 'Nợ lại', 'boxClass' => 'col-md-4'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );
    $xhtmlBottom = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elementsBottom);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>

    <?php echo $this->flashMessenger()->render('success', array('alert', 'alert-success'));?>
	<?php echo @$this->xViewElementErrors($elementsTop);?>
	<?php echo @$this->xViewElementErrors($elementsBottom);?>
	
    <div class="page-content">
    	<div class="row">
            <div class="col-md-8">
			<?php echo $xhtmlTop;?>
            </div>
            <div class="col-md-4">
                <?php echo $xhtmlBottom;?>
            </div>
            <div class="col-md-10">
                <p class="text-alert"></p>
                <?php
                    if(!empty($this->check_product_id)){
                    ?>
                    <div class="alert alert-block alert-danger">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <p><?php echo $this->check_product_id; ?></p>
                    </div>
                    <?php
                    }
                ?>
            </div>
		</div>

        <div class="col-md-5">
            <div class="row">
                <div class="col-md-12 form-section" style="padding: 0px;">
                    <div>
                        <span class="title-load-product">Sản phẩm</span>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group" style="margin-bottom: 5px;">
                            <select name="filter_products_type" class="form-control select2 select2_basic" style="display: none;">
                                <option value="">- Chọn nhóm hàng -</option>
                                <?php foreach($this->products_type as $key => $value){?>
                                    <option value="<?=$key?>"><?=$value?></option>
                                    <?php
                                } ?>
                            </select>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="form-group">
                            <div class="control-element">
                                <input type="text" name="filter_keyword" class="form-control" value="" placeholder="Nhập tên sản phẩm" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-md-12" style="padding: 0px;">
                    <div id="loadProducts">
                    </div>
                </div>
            </div>
        </div>

        <div class="col-md-7">
            <div class="row">
                <div class="col-md-12">
                    <h3 class="form-section">Danh sách sản phẩm</h3>
                    <div class="contract_product table-scrollable" style="min-height: 400px" >
                        <table class="table table-striped table-bordered table-hover table-product">
                            <thead>
                            <tr>
                                <th width="100px" class="text-center">Mã sản phẩm</th>
                                <th width="150px" class="text-center">Tên sản phẩm</th>
                                <th width="" class="text-center">Tên xe năm sản xuất</th>
                                <th width="80px" class="text-center">S.lượng</th>
                                <th width="150px" class="text-center">Giá tiền</th>
                                <th width="150px" class="text-center">Thành tiền</th>
                                <th width="10px" class="text-center hidden">C.Dài</th>
                                <th width="10px" class="text-center hidden">C.Rộng</th>
                                <th width="10px" class="text-center hidden">C.Cao</th>
                                <th width="10px" class="text-center">KG</th>
                                <th width="30px" class="text-center">Xóa</th>
                            </tr>
                            </thead>
                            <tbody class="product_body list-product-contract">
                            <?php
                            if(!empty($this->productList)){
                                $number   = new \ZendX\Functions\Number();
                                $productList = $this->productList;
                                $productHtml = '';
                                for($i = 0; $i < count($productList['product_id']); $i++) {
                                    $check_name = empty($productList['product_name'][$i]) ? 'has-error' : "";
                                    $check_number = empty($productList['numbers'][$i]) ? 'has-error' : "";
                                    $check_price = empty($productList['price'][$i]) ? 'has-error' : "";
                                    $check_car_year = empty($productList['car_year'][$i]) ? 'has-error' : "";
                                    $check_length = empty($productList['length'][$i]) ? 'has-error' : "";
                                    $check_width = empty($productList['width'][$i]) ? 'has-error' : "";
                                    $check_height = empty($productList['height'][$i]) ? 'has-error' : "";
                                    $check_weight = empty($productList['weight'][$i]) ? 'has-error' : "";

                                    $productHtml .= '<tr id="tr_'.$productList['product_id'][$i].' data-id="'.$productList['product_id'][$i].'">
                                                        <td width="100px" class="text-bold text-red text-middle">'.$productList['code'][$i].'</td>
                                                        <td width="100px" class="text-middle">'.$productList['full_name'][$i].'</td>
                                                        <td class="car_year '.$check_car_year.'"><input class="form-control text-right" type="text" name="contract_product[car_year][]" value="'.$productList['car_year'][$i].'" ></td>
                                                        <td class="numbers '.$check_number.'"><input class="form-control text-right w-60 p5" type="number" name="contract_product[numbers][]" value="'.$productList['numbers'][$i].'" min="1"></td>
                                                        <td class="price text-middle text-right box-price '.$check_price.'">
                                                            <input class="form-control text-right money base_price w-100" name="contract_product[price][]" type="text" value="'.$productList['price'][$i].'" min="0">
                                                        </td>
                                                        <td class="text-middle text-right hidden">'.number_format($productList['listed_price'][$i]).'</td>
                                                        <td class="total"><input class="form-control text-right w-100" type="text" name="contract_product[total][]" value="'.$productList['total'][$i].'" readonly></td>
                                                        <td class="length hidden">
                                                            <input class="form-control text-right w-60 p5 '.$check_length.'" type="number" name="contract_product[length][]" value="'.$productList['length'][$i].'" required min="1" max="300">
                                                        </td>
                                                        <td class="width hidden">
                                                            <input class="form-control text-right w-60 p5 '.$check_width.'" type="number" name="contract_product[width][]" value="'.$productList['width'][$i].'" required min="1" max="300">
                                                        </td>
                                                        <td class="height hidden">
                                                            <input class="form-control text-right w-60 p5 '.$check_height.'" type="number" name="contract_product[height][]" value="'.$productList['height'][$i].'" required min="1" max="300">
                                                        </td>
                                                        <td class="weight">
                                                            <input class="form-control text-right w-60 p5 '.$check_weight.'" type="number" name="contract_product[weight][]" value="'.$productList['weight'][$i].'" required>
                                                        </td>
                                                        <td class="hidden">
                                                            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$productList['product_id'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[full_name][]" value="'.$productList['full_name'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[code][]" value="'.$productList['code'][$i].'">
                                                            <input class="form-control" type="text" name="contract_product[cost][]" value="'.$productList['cost'][$i].'"> 
                                                            <input class="form-control" type="text" name="contract_product[categoryId][]" value="'.$productList['categoryId'][$i].'"> 
                                                            <input class="form-control" type="text" name="contract_product[categoryName][]" value="'.$productList['categoryName'][$i].'"> 
                                                        </td>
                                                       
                                                        <td class="text-center"><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 10px 0 0 5px; font-size: 20px;"></i></td>
                                                    </tr>';
                                }
                                echo $productHtml;
                            }
                            else if(!empty($this->option_product)){
                                $productHtml = '';
                                foreach($this->option_product as $pro_item){

                                    $tr_name = 'id="tr_'.$pro_item['product_id'].'"';
                                    $text_number = '';
                                    $productHtml .= '<tr '.$tr_name.' data-id="'.$pro_item['product_id'].'">
                                                    <td width="100px" class="text-bold text-red text-middle">'.$pro_item['code'].'</td>
                                                    <td width="100px" class="text-middle">'.$pro_item['full_name'].'</td>
                                                    <td class="car_year"><input class="form-control text-right" type="text" name="contract_product[car_year][]" value="'.$pro_item['car_year'].'" ></td>
                                                    <td class="numbers "><input class="form-control text-right w-60 p5" type="number" name="contract_product[numbers][]" value="'.$pro_item['numbers'].'" min="1"></td>
                                                    <td class="price text-middle text-right box-price">
                                                        <input class="form-control text-right money base_price w-100" name="contract_product[price][]" type="text" value="'.number_format($pro_item['price']).'" min="0">
                                                    </td>
                                                    <td class="total"><input class="form-control text-right w-100" type="text" name="contract_product[total][]" value="'.number_format($pro_item['total']).'" readonly></td>
                                                    <td class="length hidden">
                                                        <input class="form-control text-right w-60 p5" type="number" name="contract_product[length][]" value="'.$pro_item['length'].'" required min="1" max="300">
                                                    </td>
                                                    <td class="width hidden">
                                                        <input class="form-control text-right w-60 p5" type="number" name="contract_product[width][]" value="'.$pro_item['width'].'" required min="1" max="300">
                                                    </td>
                                                    <td class="height hidden">
                                                        <input class="form-control text-right w-60 p5" type="number" name="contract_product[height][]" value="'.$pro_item['height'].'" required min="1" max="300">
                                                    </td>
                                                    <td class="weight">
                                                        <input class="form-control text-right w-60 p5" type="number" name="contract_product[weight][]" value="'.$pro_item['weight'].'" required>
                                                    </td>
                                                    <td class="hidden">
                                                        <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$pro_item['product_id'].'">
                                                        <input class="form-control" type="text" name="contract_product[full_name][]" value="'.$pro_item['full_name'].'">
                                                        <input class="form-control" type="text" name="contract_product[code][]" value="'.$pro_item['code'].'">
                                                        <input class="form-control" type="text" name="contract_product[cost][]" value="'.$pro_item['cost'].'"> 
                                                        <input class="form-control" type="text" name="contract_product[categoryId][]" value="'.$pro_item['categoryId'].'"> 
                                                        <input class="form-control" type="text" name="contract_product[categoryName][]" value="'.$pro_item['categoryName'].'"> 
                                                    </td>
                                                    <td class="text-center"><i class="fa fa-trash delete-row" aria-hidden="true" style="color:red; margin: 10px 0 0 5px; font-size: 20px;"></i></td>
                                                </tr>';
                                }
                                echo $productHtml;
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
	</div>
</form>

<div class="hidden" id="vatvalue">
    <?php echo $this->params['settings']['General.System.Vat']['value'];?>
</div>

<link href="/public/template/backend/css/contract.css?v=<?php echo date('dmYHis');?>" media="screen" rel="stylesheet" type="text/css">

<?php $this->headScript()->captureStart() ?>
var params = JSON.parse('<?php echo json_encode($this->discounts_params); ?>');


$("input[name='filter_keyword']").on('keydown', function (e) {
    if (e.key === 'Enter' || e.keyCode === 13) {
        var data = {filter_products_type: $(`select[name="filter_products_type"]`).val(), filter_keyword: $(`input[name="filter_keyword"]`).val(), filter_customer_type: $(`select[name="customer_type_id"]`).val(), filter_warehouse: $(`select[name="inventory_id"]`).val()};
        load_action('#loadProducts', '<?php echo $this->url('routeAdmin/default',array('controller' => 'api', 'action' => 'loadKovProducts'));?>', data);
        return false;
    }
});

$(`select[name="filter_products_type"], select[name="customer_type_id"], select[name="inventory_id"]`).change(function () {
    var data = {filter_products_type: $(`select[name="filter_products_type"]`).val(), filter_keyword: $(`input[name="filter_keyword"]`).val(), filter_customer_type: $(`select[name="customer_type_id"]`).val(), filter_warehouse: $(`select[name="inventory_id"]`).val()};
    load_action('#loadProducts', '<?php echo $this->url('routeAdmin/default',array('controller' => 'api', 'action' => 'loadKovProducts'));?>', data);
});

<?php $this->headScript()->captureEnd() ?>


<?php $this->HeadScript()->appendFile('/public/template/backend/js/contracts/contract.js','text/javascript');?>



