<?php
    $dateFormat = new \ZendX\Functions\Date();
    $number = new \ZendX\Functions\Number();

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-arrow-left', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('div' => '', 'boxClass' => 'col-md-12', 'boxId' => 'result_check_contact'),
        array('element' => $myForm->get('file_import'), 'label' => 'Chọn file cần cập nhật <a href="'. URL_FILES .'/template/Nhap_ngay_xuat_kho_trang_thai_viettel.xlsx"><b>(Tải file mẫu)</b></a>', 'validate' => array('require' => true), 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('submit'), 'label' => '', 'boxClass' => 'col-md-12'),
    );
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" enctype="multipart/form-data">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml;?>
		</div>
		<?php
		if(!empty($this->import) && !empty($this->sheetData)) {  
		?>
    	<div class="row">
			<div class="col-md-12">
			    <div class="table-manager" id="table-manager">
                    <div class="table-scrollable" style="height: 600px;">
        				<table class="table table-striped table-bordered table-hover">
            				<thead>
            					<tr>
									<th width="200px" class=" text-center"><a href="javascript:;" class="btn btn-xs green begin-check">Bắt đầu</a></th>
            						<th class="col-50 text-center">STT</th>
            						<th>Mã Vận Đơn Đơn vị vận chuyển</th>
            						<th>Mã đơn hàng CRM</th>
                                    <th>Ngày xuất kho</th>
                                    <th>Trạng thái</th>
            					</tr>
            				</thead>
            				<tbody>
            					<?php
            					$index = 0;
            					foreach ($this->sheetData AS $key => $val) {
            					    if(strlen(trim($val['B'])) > 0 && (int)$val['A'] > 0){
            							$index++;
            					?>
								<tr id="tr_<?php echo $index;?>" data-index="<?php echo $index;?>">
									<td><a href="javascript:;" data-index="<?php echo $index;?>" class="btn btn-xs default">Sẵn sàng</a></td>
        							<td class="text-center"><?php echo $index;?></td>
        							<td><span class="ghtk_code"><?php echo trim($val['B']);?></span></td>
        							<td><span class="code"><?php echo trim($val['C']);?></span></td>
                                    <td><span class="shipped_date"><?php echo $dateFormat->formatToData(trim($val['D']), 'Y-m-d');?></span></td>
                                    <td><span class="ghtk_status"><?php echo trim($val['E']);?></span></td>
        						</tr>
        						<?php
            					    }
            					} 
        						?>
        					</tbody>
            			</table>
        			</div>
    			</div>
			</div>
		</div>
		<?php
		} else {
			echo '<div class="alert alert-danger">Không có dữ liệu import</div>';
		}
		?>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
	<?php
	if(!empty($this->import) && !empty($this->sheetData)) {  
	?>
            $('.load-data').addClass('hidden');
	function startImportContact(index) {
		var item = '#tr_'+ index;
		
		if($(item).size() > 0) {
		    var data = {
		    	'type': $('select[name="type"]').val(),
		    };
		    $(item +' span').each(function() {
		        data[$(this).attr('class')] = $(this).text();
		    });
            $.ajax({
    			url: "<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action']));?>",
    			type: 'POST',
    			data: data,
    			beforeSend: function() {
    				$(item + ' .btn').html('Đang xử lý ...').removeClass('default').addClass('yellow');
    			},
    			success: function(result) {
    				setTimeout(function(){
    					$(item).removeClass('active');
                        result = JSON.parse(result)
    					if(result['status'] == 2) {
    						$(item + ' .btn').html(result['message']).removeClass('yellow').addClass('green');
    					}
                        else if(result['status'] == 1){
                            $(item + ' .btn').html(result['message']).removeClass('yellow').addClass('red');
                        }

						var index_next = parseInt(index) + 1;
    				    startImportContact(index_next); 
    			    }, 100);
    			}
    		});
		} else {
			alert('Import thành công');
		}
	}
        $('.begin-check').click(function(){
            startImportContact(1);
        });
    <?php
	}
    ?>
<?php $this->headScript()->captureEnd() ?>