<?php
$dateFormat = new \ZendX\Functions\Date();
$number = new \ZendX\Functions\Number();
$i = 0;
foreach ($this->items as $item) {
    $company = $this->branch[$item['sale_branch_id']]['content'];
    $code = $item['code'];
    $user = $this->user[$item['created_by']]['name'];
    $options = !empty($item['options']) ? unserialize($item['options']) : array();
    $contact_name = $item['contact_name'];
    $contact_phone = $item['contact_phone'];
    $contact_license_plate = $item['contact_license_plate'];
    $note = $options['sale_note'];
    $date = date('d/m/Y');
//        $contact_phone = substr_replace($contact_phone, "****", 3, 4);
    $products = $options['product'];
    $address = $item['address'];
    $location_district = $this->location_district[$item['location_district_id']]['name'];
    $location_city = $this->location_city[$item['location_city_id']]['name'];


    $infor_contact = '<div class="label">
                            <p><span class="title text-bold">Khách hàng:</span> ' . $contact_name . '</p>
                            <p><span class="title text-bold">Số điện thoại:</span> ' . $contact_phone . '</p>
                            <p><span class="title text-bold">Địa chỉ:</span> ' . $address.', '. $location_district .', '.$location_city. '</p>
                        </div>
                        <div class="label">
                            <p><span class="title text-bold">Ngày tháng:</span> ' . $date . '</p>
                            <p><span class="title text-bold">Đơn hàng:</span> ' . $code . '</p>
                            <p><span class="title text-bold">Tên sales:</span> ' . $user . '</p>
                        </div>
                        <p></p>';


    $product_html = '';
    $index = 0;
    $total_vat = $total_price = 0;
    $vat_value = $item['option_vat'] == 'yes' ? 1.08 : 1;
    foreach ($products as $key => $value) {
        $index++;
        $product_code   = $value['code'];
        $product_name   = $value['full_name'];
        $product_unit   = $this->units[$this->products[$value['product_id']]['unit_id']]['name'];
        $product_number = $value['numbers'];
        $product_price  = round($value['price']/$vat_value);
        $product_total  = $product_price * $product_number;
        $total_vat += $value['total'] - $product_total;
        $total_price += $product_total;

        $contract_code_return = $value['product_return_id'] ? '<span class="text-red">('.$this->ProductReturn[$value['product_return_id']]['contract_code'].')</span>' : '';

        $product_html .= '<tr>
                                <td>' . $index . '</td>
                                <td>' . $product_code . '</td>
                                <td>' . $product_name . '</td>
                                <td class="text-center">' . $product_unit . '</td>
                                <td class="text-center">' . $product_number . '</td>
                                <td class="text-right">' . number_format($product_price) . '</td>
                                <td class="text-right">' . number_format($product_total) . '</td>
                            </tr>
                            ';
    }
    $product_html .= '<tr><td colspan="3" rowspan="9">Ghi chú' . $note . '</td></tr>';
    $product_html .= '<tr><td colspan="3" class="text-bold">Tiền hàng</td><td class="text-bold text-right">'.number_format($total_price).'</td></tr>';
    $product_html .= '<tr><td colspan="3">Phí giao hàng</td><td class="text-right">'.number_format($item['fee_shipp']).'</td></tr>';
    $product_html .= '<tr><td colspan="3" class="text-bold">Tiền trước thuế</td><td  class="text-bold text-right">'.number_format($total_price).'</td></tr>';
    $product_html .= '<tr><td colspan="3">Thuế GTGT</td><td class="text-right">'.number_format($total_vat).'</td></tr>';
    $product_html .= '<tr><td colspan="3" class="text-bold">Tổng thanh toán</td><td class="text-bold text-right">'.number_format($total_price + $total_vat + $item['fee_shipp']).'</td></tr>';
    $product_html .= '<tr><td colspan="3" class="text-bold">Giảm giá</td><td class="text-bold text-right">'.number_format($item['discount']).'</td></tr>';
    $product_html .= '<tr><td colspan="3" class="text-bold">Đã thanh toán</td><td class="text-bold text-right">'.number_format($item['paid_cash'] + $item['paid_transfer']).'</td></tr>';
    $product_html .= '<tr><td colspan="3" class="text-bold">Còn phải thu</td><td class="text-bold text-right">'.number_format($item['price_total'] + $item['fee_shipp'] - ($item['discount'] + $item['paid_cash'] + $item['paid_transfer'])).'</td></tr>';

    ?>
<div class="print-page">
    <div class="content-print">
        <div class="head-print">
            <div class="company">
                <h3><?php echo $company; ?></h3>
                <p><?php echo $this->warehouse[$item['inventory_id']]['address']; ?></p>
                <p>Hotline: <?php echo $this->user[$item['created_by']]['phone']; ?></p>
            </div>
        </div>
        <div class="infor-contact">
            <h4>PHIẾU GIAO HÀNG</h4>
            <?php echo $infor_contact; ?>
        </div>
        <div class="infor-order">
            <table border="1">
                <tr>
                    <th>STT</th>
                    <th>Mã SKU</th>
                    <th>Tên hàng hóa</th>
                    <th>ĐVT</th>
                    <th>SL</th>
                    <th>Đơn giá</th>
                    <th>Thành tiền</th>
                </tr>
                <?php echo $product_html; ?>
            </table><br>
            <p>Số tiền viết bằng chữ: <i class="text-bold"><?php echo $number->convertString($item['price_total'] + $item['fee_shipp'] - ($item['discount'] + $item['paid_cash'] + $item['paid_transfer']))?></i></p><br>
            <p class="text-center">Cảm ơn quý khách đã tin tưởng lựa chọn sản phẩm của cửa hàng</p>
        </div>
        <div class="sign">
            <div class="left">
                <p><b>Người lập</b><br>(ký/họ tên)</p>
            </div>
            <div class="right">
                <p><b>Khách hàng</b><br>(ký/họ tên)</p>
            </div>
        </div>

    </div>
</div>

<?php
}
?>

<style>
    *{
        margin:0px;
        padding:0px;
        box-sizing:border-box;
        moz-box-sizing:border-box;
        webkit-box-sizing:border-box;
    }
    .sign{
        display: flex;
        justify-content: space-between;
    }
    .sign > div{
        padding: 20px 60px;
        text-align: center;
    }
    .text-center{
        text-align: center;
    }
    .text-right{
        text-align: right;
    }
    .text-red{
        color: #ff0000;
    }
    .text-bold{
        font-weight: bold;
    }
    body{
        background: rgba(0,0, 0, 0.7);
        font-family: Arial, Helvetica, sans-serif;
    }
    table{
        border-collapse: collapse;
        width: 100%;
    }
    table th{
        padding: 5px;
        text-transform: capitalize;
        font-size: 14px;
    }
    table td{
        padding: 5px;
        text-transform: capitalize;
        font-size: 13px;
    }
    .content-print {
        width: 100%;
        max-width: 210mm;
        margin: auto;
        background: #fff;
        padding: 20px;
    }

    .print-page {
        page-break-after: always;
        page-break-inside: avoid;
        margin-bottom: 10px;
    }
    .content-print .head-print{
        width: 100%;
        display: flex;
    }
    .content-print .head-print .logo{
        width: 30%;
        text-align: center;
    }
    .content-print .head-print .logo img {
        width: 70%;
    }
    .content-print .head-print .company {
        width: 100%;
        padding: 0 20px;
        text-align: center;
    }
    .content-print .head-print .company h3{
        font-weight: bold;
        font-size: 18px;
        text-transform: uppercase;
        margin: 5px 0px;
        width: 100%;
    }
    .content-print .head-print .company p {
        padding: 3px 0;
        font-size: 14px;
        text-transform: capitalize;
        margin: 0;
    }
    .content-print .infor-contact{
        width: 100%;
        margin-bottom: 20px;
    }
    .content-print .infor-contact h4{
        text-align: center;
        font-size: 20px;
        text-transform: capitalize;
        padding: 10px 0 20px;
    }
    .content-print .infor-contact .label{
        width: 50%;
        float: left;
    }
    .content-print .infor-contact p {
        margin: 0;
        padding: 5px 30px;
        font-size: 15px;
        display: flex;
        text-transform: capitalize;
    }
    .content-print .infor-contact p span{
        min-width: 160px;
        display: inline-block;
    }

    /* Cấu hình đặc biệt khi nhấn Ctrl + P (In thực tế) */
    @media print {
        body {
            background: #fff;
            color: #000;
        }

        /* Loại bỏ hoàn toàn margin/padding thừa của trình duyệt */
        @page {
            size: A4 portrait;
            margin: 10mm 10mm 10mm 10mm;
        }

        .content-print {
            padding: 0;
            margin: 0;
            width: 100%;
        }

        .print-page {
            display: block;
            page-break-after: always; /* Luôn ngắt trang khi hết 1 đơn */
        }

        /* Cho phép bảng tự động ngắt sang trang thứ 2 nếu dài quá 297mm */
        table {
            page-break-inside: auto;
        }
        tr {
            page-break-inside: avoid;
            page-break-after: auto;
        }

        tr.title{
            background-color: #d8d8d8 !important;
            -webkit-print-color-adjust: exact;
        }
    }

</style>
