<?php
$dateFormat = new \ZendX\Functions\Date();
$number = new \ZendX\Functions\Number();
$i = 0;
foreach ($this->items as $item) {
    if(1) {

        $code = $item['code'];
        $user = $this->user[$item['created_by']]['name'];
        $options = !empty($item['options']) ? unserialize($item['options']) : array();
        $contact_name = $item['contact_name'];
        $contact_phone = $item['contact_phone'];
        $contact_license_plate = $item['contact_license_plate'];
        $note = $options['sale_note'];
        $date = date('d/m/Y');
//        $contact_phone = substr_replace($contact_phone, "****", 3, 4);
        $products = $options['product'];
        $address = $item['address'];
        $location_district = $this->location_district[$item['location_district_id']]['name'];
        $location_city = $this->location_city[$item['location_city_id']]['name'];


        $infor_contact = '<div class="label">
                                <p><span class="title text-bold">Khách hàng:</span> ' . $contact_name . '</p>
                                <p><span class="title text-bold">Số điện thoại:</span> ' . $contact_phone . '</p>
                                <p><span class="title text-bold">Địa chỉ:</span> ' . $address.', '. $location_district .', '.$location_city. '</p>
                            </div>
                            <div class="label">
                                <p><span class="title text-bold">Ngày tháng:</span> ' . $date . '</p>
                                <p><span class="title text-bold">Đơn hàng:</span> ' . $code . '</p>
                                <p><span class="title text-bold">Tên sales:</span> ' . $user . '</p>
                            </div>
                            <p></p>';


        $product_html = '';
        $index = 0;
        foreach ($products as $key => $value) {
            $index++;
            $product_code   = $value['code'];
            $product_name   = $value['full_name'];
            $product_unit   = $this->units[$this->products[$value['product_id']]['unit_id']]['name'];
            $product_number = $value['numbers'];
            $product_price = $value['price'];
            $product_total = $value['total'];

            $contract_code_return = $value['product_return_id'] ? '<span class="text-red">('.$this->ProductReturn[$value['product_return_id']]['contract_code'].')</span>' : '';

            $product_html .= '<tr>
                                    <td>' . $index . '</td>
                                    <td>' . $product_code . '</td>
                                    <td>' . $product_name . '</td>
                                    <td class="text-center">' . $product_unit . '</td>
                                    <td class="text-center">' . $product_number . '</td>
                                    <td class="text-right">' . number_format($product_price) . '</td>
                                    <td class="text-right">' . number_format($product_total) . '</td>
                                </tr>
                                ';
        }
        $product_html .= '<tr><td colspan="3" rowspan="8">Ghi chú' . $note . '</td></tr>';
        $product_html .= '<tr><td colspan="3" class="text-bold">Tiền hàng</td><td class="text-bold">100</td></tr>';
        $product_html .= '<tr><td colspan="3">Phí giao hàng</td><td>100</td></tr>';
        $product_html .= '<tr><td colspan="3" class="text-bold">Tiền trước thuế</td><td class="text-bold">100</td></tr>';
        $product_html .= '<tr><td colspan="3">Thuế GTGT</td><td>100</td></tr>';
        $product_html .= '<tr><td colspan="3" class="text-bold">Tổng thanh toán</td><td class="text-bold">100</td></tr>';
        $product_html .= '<tr><td colspan="3" class="text-bold">Ghi nợ</td><td class="text-bold">100</td></tr>';
        $product_html .= '<tr><td colspan="3" class="text-bold">Còn phải thu</td><td class="text-bold">100</td></tr>';

        ?>

        <div class="content-print">
            <div class="head-print">
<!--                <div class="logo">-->
<!--                    <img src="/public/files/upload/default/images/logo-ok2.png">-->
<!--                </div>-->
                <div class="company">
                    <h3>CÔNG TY TNHH SẢN XUẤT VÀ THƯƠNG MẠI XUẤT<br>NHẬP KHẨU FOREWIN</h3>
                    <p>Cụm công nghiệp làng nghề Minh Phương, TT Yên Lạc, Yên Lạc, Vĩnh Phúc</p>
                    <p>Hotline: 0389835912</p>
                </div>
            </div>
            <div class="infor-contact">
                <h4>PHIẾU GIAO HÀNG</h4>
                <?php echo $infor_contact; ?>
            </div>
            <div class="infor-order">
                <table border="1">
                    <tr>
                        <th>STT</th>
                        <th>Mã SKU</th>
                        <th>Tên hàng hóa</th>
                        <th>ĐVT</th>
                        <th>SL</th>
                        <th>Đơn giá</th>
                        <th>Thành tiền</th>
                    </tr>
                    <?php echo $product_html; ?>
                </table>
            </div>
        </div>
        <br clear="all" style="page-break-before:always"/>
        <?php
    }
    else{?>
        <div class="content-print">
            Đơn <?php echo $item['code']; ?> chưa có trạng thái sản xuất
        </div>
        <?php
    }
}
?>

<style>
    *{
        margin:0px;
        padding:0px;
        box-sizing:border-box;
        moz-box-sizing:border-box;
        webkit-box-sizing:border-box;
    }
    .text-center{
        text-align: center;
    }
    .text-right{
        text-align: right;
    }
    .text-red{
        color: #ff0000;
    }
    .text-bold{
        font-weight: bold;
    }
    body{
        background: rgba(0,0, 0, 0.7);
        font-family: Arial, Helvetica, sans-serif;
    }
    table{
        border-collapse: collapse;
        width: 100%;
    }
    table th{
        padding: 5px;
        text-transform: capitalize;
        font-size: 14px;
    }
    table td{
        padding: 5px;
        text-transform: capitalize;
        font-size: 13px;
        /*font-weight: bold;*/
    }
    .content-print {
        min-width: 210mm;
        max-width: 297mm;
        margin: auto;
        background: #fff;
        padding: 20px;
        /*background: #fff url("/public/files/upload/default/images/bg.png") no-repeat center;*/
    }
    .content-print .head-print{
        width: 100%;
        display: flex;
    }
    .content-print .head-print .logo{
        width: 30%;
        text-align: center;
    }
    .content-print .head-print .logo img {
        width: 70%;
    }
    .content-print .head-print .company {
        width: 100%;
        padding: 0 20px;
        text-align: center;
    }
    .content-print .head-print .company h3{
        font-weight: bold;
        font-size: 18px;
        text-transform: uppercase;
        margin: 5px 0px;
        width: 100%;
    }
    .content-print .head-print .company p {
        padding: 3px 0;
        font-size: 14px;
        text-transform: capitalize;
        margin: 0;
    }
    .content-print .infor-contact{
        width: 100%;
        margin-bottom: 20px;
    }
    .content-print .infor-contact h4{
        text-align: center;
        font-size: 20px;
        text-transform: capitalize;
        padding: 10px 0 20px;
    }
    .content-print .infor-contact .label{
        width: 50%;
        float: left;
    }
    .content-print .infor-contact p {
        margin: 0;
        padding: 5px 30px;
        font-size: 15px;
        display: flex;
        text-transform: capitalize;
    }
    .content-print .infor-contact p span{
        min-width: 160px;
        display: inline-block;
    }

    @media print {
        tr.title{
            background-color: #d8d8d8 !important;
            -webkit-print-color-adjust: exact;
        }
    }

</style>
