<?php
    $inventories = $this->inventories;
    $xhtml = '';
    $onhand_total = 0;
    $actualReserved_total = 0;
    $reserved_total = 0;
    foreach($inventories as $key => $value){
        $onhand_total += $value['onHand'];
        $actualReserved_total += $value['actualReserved'];
        $reserved_total += $value['reserved'];
        $xhtml .= '
            <tr>
                <td class="text-bold">'.$value['branchName'].'</td>
                <td class="text-center">'.$value['onHand'].'</td>
                <td class="text-center">'.$value['actualReserved'].'</td>
                <td class="text-center">'.$value['reserved'].'</td>
                <td class="text-center">'.($value['onHand'] - $value['reserved']).'</td>
            </tr>';
    }

    $body = '<tr>
                <td class="text-bold">Tổng</td>
                <td class="text-center">'.$onhand_total.'</td>
                <td class="text-center">'.$actualReserved_total.'</td>
                <td class="text-center">'.$reserved_total.'</td>
                <td class="text-center">'.($onhand_total - $reserved_total).'</td>
            </tr>'.$xhtml;
?>

<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
    <div class="row">
        <?php if(count($inventories) > 0){ ?>
        <div class="table-scrollable">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th class="text-center"></th>
                        <th class="text-center">Tồn</th>
                        <th class="text-center">Đặt NCC</th>
                        <th class="text-center">Tổng khách hàng đặt</th>
                        <th class="text-center">Có thể bán</th>
                    </tr>
                </thead>
                <tbody>
                    <?php echo $body;  ?>
                </tbody>
            </table>
        </div>
        <?php
        }else{
            echo "<p style='padding:10px; color: red;' >Sản phẩm không tồn tại hoặc đã bị xóa!</p>";
        }
        ?>
    </div>
</div>
<div class="modal-footer">
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
