<?php
    $myForm 		= $this->myForm;

    $elements 		= array(
        array('element' => $myForm->get('shopid'), 'label' => 'ID Shop', 'boxClass' => 'col-md-3', 'validate' => array('require' => true)),
        array('element' => $myForm->get('pick_shift'), 'label' => 'Ca lấy hàng', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('required_note'), 'label' => 'Ghi chú giao hàng', 'boxClass' => 'col-md-3', 'validate' => array('require' => true)),
        array('element' => $myForm->get('numbers_data'), 'label' => 'Số đơn đã chọn', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('list_data_id'), 'label' => 'Danh sách đơn hàng', 'boxClass' => 'col-md-3'),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true)),
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>

	<form  method="post"  class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
    	<div class="row">
	        <?php echo $xhtml;?>
		</div>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>

<script type="text/javascript">
    var data_id = new Array();
    $("#table-manager tbody tr input.checkboxes").each(function(){
        if($(this).is(':checked')){
            var item_data = {
                id: $(this).val(),
            };
            data_id.push(item_data);
        }
    });
    if(data_id.length > 0){
        $('input[name="numbers_data"]').val(data_id.length);
        $('input[name="list_data_id"]').val(JSON.stringify(data_id));
    }
</script>