<?php
    $myForm = $this->myForm;
    $myForm->prepare();
    $data = $this->data;
    $classx = $data['unit_transport'] == '5sauto' ? '' : 'hidden';
    $classy = $data['unit_transport'] == '5sauto' ? 'hidden' : '';

    $elements = array(
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
        array('element' => $myForm->get('modal'), 'validate' => array('require' => true))
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<?php
if($this->params['data']['modal'] != 'success') { 
?>
<div class="modal-header">
	<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
	<h4 class="modal-title"><?php echo $this->caption;?></h4>
</div>
<div class="modal-body">
<?php
} 
?>
    <?php echo @$this->xViewElementErrors($elements);?>
	<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminFormModal" id="adminFormModal">
        <div class="row">
            <div class="col-md-12">
                <p class="text-alert"></p>
                <?php
                if(!empty($this->check_product_id)){
                    ?>
                    <div class="alert alert-block alert-danger">
                        <button type="button" class="close" data-dismiss="alert"></button>
                        <p><?php echo $this->check_product_id; ?></p>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    	<div class="row">
			<?php echo $xhtml;?>
            <div class="col-md-12">
                <h3 class="form-section">Danh sách sản phẩm</h3>
                <div class="contract_product table-scrollable" style="min-height: 213px;" >
                    <table class="table table-striped table-bordered table-hover table-product">
                        <thead>
                        <tr>
                            <th width="100px" class="text-center">Mã sản phẩm</th>
                            <th width="150px" class="text-center">Tên sản phẩm</th>
                            <th width="" class="text-center">Tên xe - năm sản xuât</th>
                            <th width="80px" class="text-center">S.lượng</th>
                            <th width="100px" class="text-center">Giá tiền</th>
                            <th width="100px" class="text-center">Thành tiền</th>
                            <th width="100px" class="text-center">Giá vốn kiotviet</th>
                            <th width="100px" class="text-center">Giá vốn CRM</th>
                        </tr>
                        </thead>
                        <tbody class="product_body list-product-contract">
                        <?php
                        if(!empty($this->productList)){
                            $number   = new \ZendX\Functions\Number();
                            $productList = $this->productList;
                            $productHtml = '';
                            for($i = 0; $i < count($productList['product_id']); $i++) {
                                $check_cost = empty($productList['cost'][$i]) ? 'has-error' : "";
                                $check_cost_new = empty($productList['cost_new'][$i]) ? 'has-error' : "";

                                $productHtml .= '<tr id="tr_'.$productList['product_id'][$i].' data-id="'.$productList['product_id'][$i].'">
                                                        <td width="100px" class="text-bold text-red text-middle">'.$this->option_product[$i]['code'].'</td>
                                                        <td width="100px" class="text-middle">'.$this->option_product[$i]['full_name'].'</td>
                                                        <td width="100px" class="text-middle">'.$this->option_product[$i]['car_year'].'</td>
                                                        <td class="numbers text-center text-middle" >'.$this->option_product[$i]['numbers'].'</td>
                                                        <td class="price text-middle text-right box-price">'.$this->option_product[$i]['price'].'</td>
                                                        <td class="total text-right text-middle">'.$this->option_product[$i]['total'].'</td>
                                                        <td class="cost '.$check_cost.'"><input class="form-control text-right money" type="text" name="contract_product[cost][]" value="'.$productList['cost'][$i].'"></td>
                                                        <td class="cost_new '.$check_cost_new.'"><input class="form-control text-right money" type="text" name="contract_product[cost_new][]" value="'.$productList['cost_new'][$i].'"></td>
                                                        <td class="hidden">
                                                            <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$productList['product_id'][$i].'">
                                                        </td>
                                                    </tr>';
                            }
                            echo $productHtml;
                        }
                        else if(!empty($this->option_product)){
                            $productHtml = '';
                            foreach($this->option_product as $pro_item){

                                $tr_name = 'id="tr_'.$pro_item['product_id'].'"';
                                $text_number = '';
                                $productHtml .= '<tr '.$tr_name.' data-id="'.$pro_item['product_id'].'">
                                                    <td width="100px" class="text-bold text-red text-middle">'.$pro_item['code'].'</td>
                                                    <td width="100px" class="text-middle">'.$pro_item['full_name'].'</td>
                                                    <td class="car_year">'.$pro_item['car_year'].'</td>
                                                    <td class="numbers text-center text-middle ">'.$pro_item['numbers'].'</td>
                                                    <td class="price text-middle text-right box-price">'.number_format($pro_item['price']).'</td>
                                                    <td class="total text-middle text-right">'.number_format($pro_item['total']).'</td>
                                                    <td class="cost"><input class="form-control text-right money" type="text" name="contract_product[cost][]" value="'.number_format($pro_item['cost']).'"></td>
                                                    <td class="cost_new"><input class="form-control text-right money" type="text" name="contract_product[cost_new][]" value="'.number_format($pro_item['cost_new']).'"></td>
                                                    <td class="hidden">
                                                        <input class="form-control" type="text" name="contract_product[product_id][]" value="'.$pro_item['product_id'].'">
                                                    </td>
                                                </tr>';
                            }
                            echo $productHtml;
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
		</div>
    </form>
<?php
if($this->params['data']['modal'] != 'success') { 
?>
</div>
<div class="modal-footer">
	<button type="button" class="btn green save-close">Lưu & Đóng</button>
	<button type="button" data-dismiss="modal" class="btn btn-default">Đóng</button>
</div>
<?php
} 
?>

