<?php
    $dateFormat = new \ZendX\Functions\Date();

    $myForm = $this->myForm;
    $myForm->prepare();

    $permission_ids = explode(',', $curent_user['permission_ids']);
    $encode_phone = explode(',', $curent_user['encode_phone']);
    $phone_code = true;
    if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || !in_array('sale_contract', $encode_phone)) {
        $phone_code = false;
    }

    $myForm->get('filter_action')->setValue($this->params['action']);
    if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || in_array(GDCN, $permission_ids) || in_array(MANAGER, $permission_ids)){
        $elements = array(
//            array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_product'), 'boxClass' => 'col-md-3 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('filter_action'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('order')),
            array('element' => $myForm->get('order_by')),
        );
    }

    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
    
    // Danh sách
    $xhtmlItems = '';

    if(count($this->items) > 0) {
        $stt = 0;

        foreach ($this->items AS $key => $item) {
            $stt++;
            $order = isset($item['order']) ? number_format($item['order']) : 0;
            $ghtk = isset($item['ghtk']) ? number_format($item['ghtk']): 0;
            $onHand = isset($item['onHand']) ? number_format($item['onHand']) : 0;
            $xhtmlItems .= '<tr>
    							<td >'. $stt .'</td>
    							<td >'. $item['code'] .'</td>
    							<td >'. $item['name'] .'</td>
    							
    							<td class="text-right">'. $order .'</td>
    							<td class="text-right">'. $ghtk .'</td>
    							<td class="text-right">'. $onHand .'</td>
                            </tr>';
        }
    }

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th width="40" class="text-center">STT</th>';
    $xhtmlHead .= '<th>Mã sản phẩm</th>';
    $xhtmlHead .= '<th>Tên sản phẩm</th>';
    $xhtmlHead .= '<th>Số lượng khách đặt</th>';
    $xhtmlHead .= '<th>Đã giao cho GHTK</th>';
    $xhtmlHead .= '<th>Tồn kho trên Kiotviet</th>';
    $xhtmlHead .= '</tr>';

?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
<!--			--><?php //echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable table-fixed">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
        	?>
    	</div>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
<!-- resize_col_table('#table-manager'); -->
<?php $this->headScript()->captureEnd() ?>
