<?php
    // Filter
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    $elements = array(
        array('element' => $myForm->get('filter_contract_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_contract_price_owed'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('id')),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th>STT</th>';
    $xhtmlHead .= '<th>Ngày ký</th>';
    $xhtmlHead .= '<th>Số điện thoại</th>';
    $xhtmlHead .= '<th>Họ tên</th>';
    $xhtmlHead .= '<th>Ngày sinh</th>';
    $xhtmlHead .= '<th>Thành tiền</th>';
    $xhtmlHead .= '<th>Đã thu</th>';
    $xhtmlHead .= '<th>Đã chi</th>';
    $xhtmlHead .= '<th>Còn nợ</th>';
    $xhtmlHead .= '<th>Test đầu vào</th>';
    $xhtmlHead .= '<th>Khóa học</th>';
    $xhtmlHead .= '<th>Lớp học</th>';
    $xhtmlHead .= '<th>Người quản lý</th>';
    $xhtmlHead .= '<th>Đội nhóm</th>';
    $xhtmlHead .= '<th>Cơ sở</th>';
    $xhtmlHead .= '<th>Chuyển nhượng</th>';
    $xhtmlHead .= '<th>Bảo lưu</th>';
    $xhtmlHead .= '<th>Học lại</th>';
    $xhtmlHead .= '<th>Học bù</th>';
    $xhtmlHead .= '<th>Công cụ</th>';
	$xhtmlHead .= '</tr>';

    // Danh sách
    $xhtmlItems         = '';
    $total              = $this->items->count();
    $percent_owed_60    = 0;
    $percent_owed_30    = 0;
    $percent_owed_rest  = 0;
    $index              = 0;
    foreach ($this->items AS $item) {
        $index++;
        $id                     = $item->id;
        $contact_id             = $item->contact_id;
        $register_date          = date_format(date_create($item->register_date), 'd/m/Y');
        $contact_phone          = $item->contact_phone;
        $contact_name           = $item->contact_name;
        $contact_birthday       = $item->contact_birthday ? date_format(date_create($item->contact_birthday), 'd/m/Y') : '';
        $contact_test_online    = $item->contact_test_online;
        $price_unit             = $item->price_unit;
        $price_promotion        = $item->price_promotion;
        $price_total            = $item->price_total;
        $price_paid             = $item->price_paid;
        $price_accrued          = $item->price_accrued;
        $price_owed             = $item->price_owed;
        $product_id             = $item->product_id ? $this->product[$item->product_id]['name'] : '';
        $training_class_id      = $item->training_class_id ? $this->training_class[$item->training_class_id]['name'] : '';
        $user_id                = $item->user_id ? $this->user[$item->user_id]['name'] : '';
        $company_group_id       = $item->company_group_id ? $this->company_group[$item->company_group_id]['name'] : '';
        $company_branch_id      = $item->company_branch_id ? $this->company_branch[$item->company_branch_id]['name'] : '';
        $transfer               = !empty($item->transfer) ? date_format(date_create($item->transfer), 'd/m/Y') : '';
        $reserve                = !empty($item->reserve) ? date_format(date_create($item->reserve), 'd/m/Y') : '';
        $relearn                = !empty($item->relearn) ? date_format(date_create($item->relearn), 'd/m/Y') : '';
        $makeup                 = !empty($item->makeup) ? date_format(date_create($item->makeup), 'd/m/Y') : '';
        $str_note               = '';
        if(!empty($item['makeup_training_class'])) {
            $str_note       = ' <span class="text-red">(Học bù)</span>';
        }
        if(!empty($item['reserve_training_class'])) {
            $str_note       = ' <span class="text-red">(Học bảo lưu)</span>';
        }
        if(!empty($item['relearn_training_class'])) {
            $str_note       = ' <span class="text-red">(Học lại)</span>';
        }
        if($item->product_id != $this->class['product_id'] && $str_note == '') {
            $training_class_id .= ' <span class="text-red">(Học ghép)</span>';
        }
        
        $created            = date_format(date_create($item->created), 'd/m/Y H:i:s');
        $created_by         = $this->user[$item->created_by]['name'];
        $modified           = date_format(date_create($item->modified), 'd/m/Y H:i:s');
        $modified_by        = $this->user[$item->modified_by]['name'];
        $cid                = @$this->xFormInput('cid[]', $contact_id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        
        // Link Action
        $linkView           = $this->url('routeAdmin/default', array('controller' => 'contract', 'action' => 'view', 'id' => $id));
        
        // Control Action
        $controlView        = $this->linkAdminHtml($linkView, array('type' => 'icon', 'title' => 'Xem chi tiết', 'class' => 'btn btn-xs blue', 'icon' => 'fa fa-info', 'target' => '_blank'));
        $controls           = $controlView;
        
        $percent_owed = ($price_total > 0) ? $price_owed/$price_total * 100 : 0;;
        $class = '';
        if ($percent_owed > 60){
            $class = 'danger';
            $percent_owed_60++;
        } else if ($percent_owed > 30){
            $class = 'warning';
            $percent_owed_30++;
        } else if ($percent_owed > 0){
            $class = 'active';
            $percent_owed_rest++;
        }
      
        $xhtmlItems .= '<tr class="'.$class.'" id="tr_'. $id .'">
							<td>'. $cid .'</td>
							<td>'. $index .'</td>
							<td>'. $register_date .'</td>
							<td>'. $contact_phone .'</td>
							<td>'. $contact_name .'</td>
							<td>'. $contact_birthday .'</td>
							<td class="mask_currency">'. $price_total .'</td>
							<td class="mask_currency">'. $price_paid .'</td>
							<td class="mask_currency">'. $price_accrued .'</td>
							<td class="mask_currency">'. $price_owed .'</td>
							<td>'. $contact_test_online .'</td>
							<td>'. $product_id .'</td>
							<td>'. $training_class_id . $str_note .'</td>
							<td>'. $user_id .'</td>
							<td>'. $company_group_id .'</td>
							<td>'. $company_branch_id .'</td>
							<td class="text-red">'. $transfer .'</td>
							<td class="text-red">'. $reserve .'</td>
							<td class="text-red">'. $relearn .'</td>
							<td class="text-red">'. $makeup .'</td>
						    <td>'. $controls .'</td>
						</tr>';
    }
    $arrControl = array(
        array('name' => 'close', 'caption' => 'Quay lại danh sách lớp', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
        array( 'name' => 'export', 'caption' => 'Xuất bản excel', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'export', 'id' => $this->route['id'])), 'icon' => 'fa-file-excel-o', 'attributes' => array('class' => 'btn', 'onclick' => 'javascript:exportList();')),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminForm" id="adminForm" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    		<input type="hidden" id="idContact" value="">
    	</div>
    </div>
    <div class="page-report">
        <div class="text">
            <span class="item">Tổng số học viên: <span class="value<?php if($total >= $this->class['student_max']) echo ' text-red';?>"><?php echo $total .'/'. $this->class['student_max'];?></span></span>
            <span class="item">Nợ trên 60%: <span class="value text-danger"><?php echo $percent_owed_60;?></span></span>
            <span class="item">Nợ 30% - 60%: <span class="value text-warning"><?php echo $percent_owed_30;?></span></span>
            <span class="item">Nợ dưới 30%: <span class="value text-active"><?php echo $percent_owed_rest;?></span></span>
        </div>
    </div>
    <div class="page-content">
        <?php
        if($this->items->count() > 0) { 
        ?>
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    	</div>
    	<?php
        } else {
            echo '<div class="alert alert-danger">Không có dữ liệu</div>';
        } 
    	?>
	</div>
</form>
<?php $this->headScript()->captureStart() ?>
    
    $('#adminForm select').change(function() {
		$('#adminForm').submit();
    });
<?php $this->headScript()->captureEnd() ?>