<?php
    $dateFormat = new \ZendX\Functions\Date();
    
    // Thông tin lớp học
    $infoClass      = $this->item;
    $edu_class_note = !empty($infoClass['note']) ? unserialize($infoClass['note']) : array();
    
    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th>STT</th>';
    $xhtmlHead .= '<th>Công cụ</th>';
    $xhtmlHead .= '<th>Mã HĐ</th>';
    $xhtmlHead .= '<th>Ngày HĐ</th>';
    $xhtmlHead .= '<th>Số điện thoại</th>';
    $xhtmlHead .= '<th>Họ tên</th>';
    $xhtmlHead .= '<th>Ngày sinh</th>';
    $xhtmlHead .= '<th>Giới tính</th>';
    $xhtmlHead .= '<th>Email</th>';
    $xhtmlHead .= '<th>Người quản lý</th>';
    $xhtmlHead .= '<th>Đơn giá</th>';
    $xhtmlHead .= '<th>Ưu đãi</th>';
    $xhtmlHead .= '<th>Thành tiền</th>';
    $xhtmlHead .= '<th>Đã đóng</th>';
    $xhtmlHead .= '<th>Đã chi</th>';
    $xhtmlHead .= '<th>Công nợ</th>';
    $xhtmlHead .= '<th>Trạng thái</th>';
    $xhtmlHead .= '<th>Ghi chú đơn hàng</th>';
    $xhtmlHead .= '<th>Ghi chú học viên</th>';
    $xhtmlHead .= '</tr>';
    
    // Danh sách
    $xhtmlItems = '';
    $stt = 0;
    foreach ($this->items AS $item){
        $stt++;
        
        $cid                    = @$this->xFormInput('cid[]', $item->id, array('type' => 'checkbox', 'class' => 'checkboxes'));
        $id                     = $item->id;
        $index                  = $item->index;
        $date                   = $dateFormat->formatToView($item->date);
        $contact_phone          = $item->contact_phone;
        $contact_name           = $item->contact_name;
        $contact_email          = $item->contact_email;
        $contact_birthday       = $dateFormat->formatToView($item->contact_birthday);
        $contact_sex            = $this->sex[$item->contact_sex]['name'];
        $user_id                = $item->user_id ? $this->user[$item->user_id]['name'] : '';
        $sale_group_id          = $item->sale_group_id ? '<br>'.  $this->sale_group[$item->sale_group_id]['name'] : '';
        $sale_branch_id         = $item->sale_branch_id ? ' - '. $this->sale_branch[$item->sale_branch_id]['name'] : '';
        $price                  = $item->price;
        $price_promotion        = $item->price_promotion;
        $price_total            = $item->price_total;
        $price_paid             = $item->price_paid;
        $price_accrued          = $item->price_accrued;
        $price_owed             = $item->price_owed;
        
        $contact_options        = $item->contact_options ? unserialize($item->contact_options) : array();
        $contract_options       = $item->options ? unserialize($item->options) : array();
        $edu_class_ids          = !empty($item['edu_class_ids']) ? unserialize($item['edu_class_ids']) : array();
        
        $color_price_owed       = '';
        if($price_total > 0){
            if(($price_paid / $price_total * 100) < 60) {
                $color_price_owed   = ' text-red';
            } elseif (($price_paid / $price_total * 100) < 100) {
                $color_price_owed   = ' text-purple';
            }
        }

        $edu_class_info = '';
        if(!empty($edu_class_ids[$infoClass['id']]['reserve_sessions'])) {
            $edu_class_info .= '<div class="text-purple text-normal">Bảo lưu: '. $dateFormat->formatToView($edu_class_ids[$infoClass['id']]['reserve_date_begin']) .'</div>';
        }
        if (!empty($edu_class_ids[$infoClass['id']]['reserve_from'])) {
            if($infoClass['id'] != $item['edu_class_id']) {
                $edu_class_info .= '<div class="text-purple text-normal">Học bảo lưu đến: <a href="'. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'detail', 'id' => $edu_class_ids[$infoClass['id']]['reserve_from'])) .'">'. $this->edu_class[$edu_class_ids[$infoClass['id']]['reserve_from']]['name'] .'</a></div>';
            } else {
                $edu_class_info .= '<div class="text-purple text-normal">Học bảo lưu từ: <a href="'. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'detail', 'id' => $edu_class_ids[$infoClass['id']]['reserve_from'])) .'">'. $this->edu_class[$edu_class_ids[$infoClass['id']]['reserve_from']]['name'] .'</a></div>';
            }
        }
        if(!empty($edu_class_ids[$item['edu_class_id']]['leave_sessions'])) {
            $edu_class_info .= '<div class="text-red text-normal">Nghỉ học từ: '. $dateFormat->formatToView($item['leave_date']) .'</div>';
            $edu_class_info .= '<div class="text-normal">Lý do: '. $edu_class_ids[$infoClass['id']]['leave_content'] .'</div>';
        }
        if(!empty($contract_options['edu_class_move'])) {
            $edu_class_info .= '<div class="text-purple text-normal">Chuyển từ lớp: '. $this->edu_class[$contract_options['edu_class_move']]['name'] .'</div>';
        }
        if(!empty($contract_options['edu_class_relearn'])) {
            $edu_class_info .= '<div class="text-purple text-normal">Học lại từ lớp: '. $this->edu_class[$contract_options['edu_class_relearn']]['name'] .'</div>';
        }
        
        $note = '';
        if (!empty($edu_class_note[$id])){
            krsort($edu_class_note[$id]);
            $stt_note = 0;
            foreach ($edu_class_note[$id] AS $k => $v){
                $stt_note++;
                if($stt_note == 1) {
                    $view = '';
                    if(count($edu_class_note[$id]) > 1) {
                        $view = ' <a href="javascript:;" onclick="showNoteStudent(this)" data-id="'. $id .'">(Xem thêm)</a>';
                    }
                    $note .= '<div><b>'. $dateFormat->formatToView($v['note_date']) .' - '. $this->user[$v['note_by']]['name'] .'</b>: '. $v['note_content'] . $view .'</div>';
                } else {
                    $note .= '<div class="hidden note_'. $id .'"><b>'. $dateFormat->formatToView($v['note_date']) .' - '. $this->user[$v['note_by']]['name'] .'</b>: '. $v['note_content'] .'</div>';
                }
            }
        }
        
        $controlNote            = $this->linkAdminHtml('javascript:;', array('type' => 'icon', 'title' => 'Ghi chú', 'class' => 'btn btn-xs blue', 'icon' => 'fa fa-commenting', 'onclick' => 'javascript:popupAction(\''. $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'note')) .'\', {\'id\': \''. $id .'\', \'edu_class_id\': \''. $infoClass['id'] .'\'});'));
        $controls               = $controlNote;
        
        $xhtmlItems .= '<tr id="tr_'. $id .'" data-id-contact="'. $item->contact_id .'">
                            <td>'. $cid .'</td>
							<td>'. $stt .'</td>
							<td>'. $controls .'</td>
							<td>'. $index .'</td>
							<td>'. $date .'</td>
							<td>'. $contact_phone .'</td>
							<td>'. $contact_name .'</td>
							<td>'. $contact_birthday .'</td>
							<td>'. $contact_sex .'</td>
							<td>'. $contact_email .'</td>
						    <td>'. $user_id . $sale_branch_id .'</td>
							<td><span class="mask_currency">'. $price .'</span></td>
							<td><span class="mask_currency">'. $price_promotion .'</span></td>
							<td><span class="mask_currency text-primary">'. $price_total .'</span></td>
							<td><span class="mask_currency">'. $price_paid .'</span></td>
							<td><span class="mask_currency">'. $price_accrued .'</span></td>
							<td><span class="mask_currency'. $color_price_owed .'">'. $price_owed .'</span></td>
							<td>'. $edu_class_info .'</td>
						    <td><div class="col-200 text-wrap">'. $contract_options['contract_note'] .'</div></td>
							<td><div class="col-200 text-wrap">'. $note .'</div></td>
					    </tr>';
    }
?>

<div class="page-report" style="padding: 10px 0;">
    <div class="text">
        <span class="item">Tổng số học viên: <span class="value"><?php echo $infoClass['student_total'] .'/'. $infoClass['student_max'];?></span></span>
    </div>
</div>
<div class="page-content">
    <?php
    if($this->items->count() > 0) { 
    ?>
	<div class="table-manager" id="table-manager">
		<div class="table-scrollable">
			<table class="table table-striped table-bordered table-hover tableContract">
				<thead>
					<?php echo $xhtmlHead;?>
				</thead>
				<tbody>
					<?php echo $xhtmlItems;?>
				</tbody>
			</table>
		</div>
	</div>
	<?php
    } else {
        echo '<div class="alert alert-danger">Không có dữ liệu</div>';
    } 
	?>
</div>
<script type="text/javascript">
	function showNoteStudent(element) {
		$(element).hide();
		$('.note_'+ $(element).attr('data-id')).removeClass('hidden');
	}
</script>