<?php 
    $dateFormat = new \ZendX\Functions\Date();

    // Thông tin lớp học
    $infoClass          = $this->item;
    $edu_class_note     = !empty($this->item['note']) ? unserialize($this->item['note']) : array();
    $edu_class_sessions = $infoClass['sessions'];
    $edu_class_route    = $infoClass['route'] ? unserialize($infoClass['route']) : array();
    $edu_class_muster   = $infoClass['muster'] ? unserialize($infoClass['muster']) : array();
    $edu_class_point    = $infoClass['point'] ? unserialize($infoClass['point']) : array();
    $product_type_id    = $this->product_type[$this->product[$infoClass['product_id']]['type']]['id'];

    // Tiêu đề của bảng
    $headHtmlRow = '<tr>';
    foreach ($this->edu_point_type AS $point_type) {
        if($point_type['document_id'] == $product_type_id) {
            $col = 0;
            foreach ($this->edu_point AS $point){
                if($point['document_id'] == $product_type_id) {
                    $col++;
                    $headHtmlRow .= '<th>'. $point['name'] .'</th>';
                }
            }
        }
    }
    $headHtmlRow .= '</tr>';
    
    $headHtml  = '<tr>
                    <th rowspan="2">STT</th>
                    <th rowspan="2">Họ Tên</th>
                    <th rowspan="2">Ngày sinh</th>
                    <th rowspan="2">Điện thoại</th>
                    <th rowspan="2">Email</th>';
    foreach ($this->edu_point_type AS $point_type) {
        if($point_type['document_id'] == $product_type_id) {
            $headHtml .= '<th colspan="'. $col .'">'. $point_type['name'] .'</th>';
        }
    }
    $headHtml .= '<th rowspan="2">Lên lớp</th>';
    $headHtml .= '</tr>';
    $headHtml .= $headHtmlRow;
    
    // Đưa danh sách vào
    $xhtml = '';
    $stt= 0;
    foreach ($this->items as $item){
        $stt++;
        
        $id                 = $item->id;
        $contact_phone      = $item->contact_phone;
        $contact_name       = $item->contact_name;
        $contact_email      = $item->contact_email;
        $contact_birthday   = $dateFormat->formatToView($item->contact_birthday);
                
        $xhtml .= '<tr class="'. $id .'">
                    <td>'. $stt .'</td>
                    <td>'. $contact_name .'</td>
                    <td>'. $contact_birthday .'</td>
                    <td>'. $contact_phone .'</td>
                    <td>'. $contact_email .'</td>';
        foreach ($this->edu_point_type AS $point_type) {
            if($point_type['document_id'] == $product_type_id) {
                foreach ($this->edu_point AS $point){
                    if($point['document_id'] == $product_type_id) {
                        $xhtml .= '<td><input name="number" step="any" type="number" class="form-control input-xs" min="0" data-contract-id="'. $id .'" data-point-type-id="'. $point_type['id'] .'" data-point-id="'. $point['id'] .'" value="'. $edu_class_point[$id][$point_type['id']][$point['id']] .'"></td>';
                    }
                }
            }
        }
        
        $style       = 'background: #FFF; color: #000;';
        $selectNull  = '';
        $select1     = '';
        $select0     = '';
        $dataValue   = $edu_class_point[$id]['end']['value'];
        if($dataValue == '') {
            $selectNull = ' selected="selected"';
        } else if($dataValue == '1') {
            $select1 = ' selected="selected"';
        } else if($dataValue == '0') {
            $select0 = ' selected="selected"';
            $style = 'background: #fd8c8c !important;';
        }
        
        $xhtml .= '<td>
                        <select class="form-control input-xs" data-contract-id="'. $id .'" data-point-type-id="end" data-point-id="value" name="number" style="'. $style .'">
                            <option value=""'. $selectNull .'></option>
                            <option value="1"'. $select1 .'>Có</option>
                            <option value="0"'. $select0 .'>Không</option>
                        </select>
                    </td>';
        $xhtml .= '</tr>';
    }
?>
<form method="post" action="" role="form" name="adminFormAjaxTest" id="adminFormAjaxTest">
    <div class="table-manager" id="table-manager">
		<div class="table-scrollable">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <?php echo $headHtml; ?>
                </thead>
                <tbody>
                    <?php echo $xhtml; ?>
                </tbody>
            </table>
        </div>
    </div>
</form>
<script type="text/javascript">
	$('#adminFormAjaxTest input[name="number"]').change(function() {
		$.ajax({
			url: '<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action']));?>',
			type: 'POST',
			data: { 
    			id: '<?php echo $infoClass['id'];?>',
    			contract_id: $(this).attr('data-contract-id'), 
    			point_type_id: $(this).attr('data-point-type-id'),
    			point_id: $(this).attr('data-point-id'),
    		    point: $(this).val(),
		    },
			beforeSend: function() {
				pageLoading('loading', '.page-container');
			},
			success: function(result) {
				if(result != '') {
					xToastr('error', 'Lỗi không thể xử lý yêu cầu', '');
				}
				pageLoading('close', '.page-container');
			}
		});
    });

	$('#adminFormAjaxTest select').change(function() {
		var value = $(this).val();
		if(value == '' || value == '1'){
            $(this).css({'background-color': '#FFF', 'color': '#000'});
        } else if(value == '0') {
            $(this).css({'background-color': '#fd8c8c', 'color': '#000'});
        }

		$.ajax({
			url: '<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => $this->params['action']));?>',
			type: 'POST',
			data: { 
    			id: '<?php echo $infoClass['id'];?>',
    			contract_id: $(this).attr('data-contract-id'), 
    			point_type_id: $(this).attr('data-point-type-id'),
    			point_id: $(this).attr('data-point-id'),
    		    point: $(this).val(),
		    },
			beforeSend: function() {
				pageLoading('loading', '.page-container');
			},
			success: function(result) {
				if(result != '') {
					xToastr('error', 'Lỗi không thể xử lý yêu cầu', '');
				}
				pageLoading('close', '.page-container');
			}
		});
    });
</script>