<?php 
    $myForm = $this->myForm;
    $myForm->prepare();

    $string = new \ZendX\Functions\Gid();
    $random = $string->random();

    $myForm->get('sale_group_id')->setAttributes(array('data-parent' => $myForm->get('sale_branch_id')->getValue()));
    if(!empty($this->params['ssFilter']['sale_group_id'])) {
        $myForm->get('sale_group_id')->setAttributes(array('data-text-label' => $this->saleGroup[$this->params['ssFilter']['sale_group_id']]['name']));
    }
    $this->_userInfo = new \ZendX\System\UserInfo();
    $curent_user = $this->_userInfo->getUserInfo();
    $permission_ids = explode(',', $curent_user['permission_ids']);
    if(in_array(SYSTEM, $permission_ids) || in_array(ADMIN, $permission_ids) || in_array(MANAGER, $permission_ids)){
        $elements = array(
            array('element' => $myForm->get('date_begin'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('date_end'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('sale_branch_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('sale_group_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('marketer_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        );
    }
    elseif(in_array(GDCN, $permission_ids)){
        $elements = array(
            array('element' => $myForm->get('date_begin'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('date_end'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('sale_group_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('marketer_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        );
    }
    elseif(in_array(GROUP_MKT_LEADER, $permission_ids)){
        $elements = array(
            array('element' => $myForm->get('date_begin'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('date_end'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('marketer_id'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        );
    }
    else{
        $elements = array(
            array('element' => $myForm->get('date_begin'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('date_end'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
            array('element' => $myForm->get('submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        );
    }

    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>
<div class="report" id="adminReport_<?php echo $random; ?>">
    <div class="report-control">
    	<div class="title pull-left"><?php echo $this->caption;?></div>
		<div class="clearfix"></div>
	</div>
	<div class="report-wrapper">
    	<div class="report-filter">
    	    <form>
        	    <div class="row">
                    <?php echo $xhtmlFilter;?>
                </div>
            </form>
    	</div>
    	<div class="report-content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="report-table">
                        <div class="table-scrollable table-report">
                			<table class="table table-striped table-bordered table-hover">
                				<?php echo $this->reportTable;?>
                			</table>
            			</div>
        			</div>
                </div>
                <?php
                if(!isset($_GET['hideChart']) || $_GET['hideChart'] == 0) { 
                ?>
                <div class="col-sm-12">
                    <div class="report-chart"></div>
                    <h3 class="text-center">Biểu đồ data marketing theo kênh nguồn</h3>
                </div>
                <?php
                } 
                ?>
            </div>
        </div>
    </div>
</div>
<style>
    table thead tr th{
        vertical-align: middle !important;
    }
</style>

<script type="text/javascript">
    $(document).ready(function() {
        var idReport = '#adminReport_<?php echo $random; ?>';
        var ajaxUrl = "<?php echo $this->url('routeReport/default', array('controller' => $this->params['controller'], 'action' => $this->params['action'])); ?>";
        function report_<?php echo $random?>() {
            $.ajax({
        		url: ajaxUrl,
        		type: 'POST',
        		data: $(idReport + ' form').serialize(),
        		beforeSend: function() {
        			pageLoading('loading', idReport + ' .report-content');
        		},
        		success: function(result) {
        			result = JSON.parse(result);

        			// Load dữ liệu ra table
        			$(idReport + ' .report-table table').html(result.reportTable);

        			// Load dữ liệu ra biểu đồ
        			if($(idReport + ' .report-chart').length) {
        				$(idReport + ' .report-chart').html('');
            			$(idReport + ' .report-chart').append('<div id="chart_<?php echo $random;?>"></div>');
                		reportChart(result.reportChart, 'chart_<?php echo $random;?>', 'pie', null);
        			}
        			
        			pageLoading('close', idReport + ' .report-content');
        			Form.init();
        		}
        	});
        }
        report_<?php echo $random?>();
        $(idReport + ' form button[name="submit"]').click(function() {
        	report_<?php echo $random?>();
        });

        // Sự kiện thay đổi cơ sở
        $(idReport + ' select[name="sale_branch_id"]').change(function() {
            var select = 'input[name="sale_group_id"]';
            var parent = $(select).parent();
            $('.select2-container', parent).select2('val', '');
            $(select).attr('data-parent', $(this).val());
        });

        $(idReport + ' select').change(function() {
            report_<?php echo $random?>();
        });
        $(idReport + ' input').change(function() {
            report_<?php echo $random?>();
        });
    });
</script>
