<?php echo $this->flashMessenger()->render();?>

<div class="page-control">
	<div class="title pull-left">
		<?php echo $this->caption;?>
	</div>
	<div class="clearfix"></div>
</div>
	
<div class="page-content">
	<div class="table-manager" id="table-manager">
		<div class="table-scrollable">
			<table class="table table-striped table-bordered table-hover">
				<thead>
					<tr>
					    <th>STT</th>
					    <th>Tên file</th>
					    <th>Công cụ</th>
				    </tr>
				</thead>
				<tbody>
				    <?php
				    $i = 0;
				    foreach ($this->files AS $file) {
				        if(substr($file, 0, 1) != '.') {
				            $i++;
		            ?>
		            <tr>
		                <td><?php echo $i;?></td>
		                <td><?php echo $file;?></td>
		                <td><a href="<?php echo $this->dir .'/'. $file;?>" class="btn btn-xs green">Download</a></td>
		            </tr>
		            <?php
				        }
				    } 
				    ?>
				</tbody>
			</table>
		</div>
	</div>
</div>

