<?php
    $configs = $this->params['configs'];
    $myForm  = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdminDocument/default', array('slug' => $configs['code'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array();
    foreach ($configs['form']['fields'] AS $filed) {
        $elements[] = array('element' => $myForm->get($filed['name']), 'label' => $filed['caption'], 'validate' => $filed['validators'], 'boxClass' => $filed['boxClass']);
    }
    $elements[] = array('element' => $myForm->get('id'), 'label' => 'Id', 'validate' => array('require' => true));
    
    // Chỉ dành cho nhà phát triển
    $classDev = '';
    if($this->userInfo['id'] != '1111111111111111111111') {
        $classDev = 'hidden';
    }
    $elements[] = array('element' => $myForm->get('public'), 'label' => 'Công khai', 'boxClass' => $classDev);
    $elements[] = array('element' => $myForm->get('developer'), 'label' => 'Dành cho nhà phát triển', 'boxClass' => $classDev);
    
    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<?php
if(empty($this->item['developer']) || $this->userInfo['id'] == '1111111111111111111111') {
?>
<form method="post" action="" class="horizontal-form form-tab" role="form" name="adminForm" id="adminForm">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row">
			<?php echo $xhtml; ?>
		</div>
	</div>
</form>
<?php
} else {
    echo '<div class="alert alert-danger">Chức năng này chỉ dành cho nhà phát triển</div>';
} 
?>

<style type="text/css">
    .form-group .control-element > label {
        font-size: 12px;
        margin: 5px 3px;
        padding: 0;
    }
    .form-group .control-element > label input {
        margin: 0 3px 0 10px;
    }
    .form-group .control-element > label:first-child input {
        margin: 0 3px 0 0;
    }
</style>
