<?php
    $dateFormat = new \ZendX\Functions\Date();
    $configs = $this->params['configs'];
    $myForm  = $this->myForm;
    $myForm->prepare();
    
    $elements   = array();
    $elements[] = array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6');
    $elements[] = array('element' => $myForm->get('filter_status'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6');
    if(!empty($configs['list']['filter'])) {
        $elements[] = array('element' => $myForm->get('filter_document'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6');
    }
    $elements[] = array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6');
    $elements[] = array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6');
    $elements[] = array('element' => $myForm->get('order'));
    $elements[] = array('element' => $myForm->get('order_by'));
    
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Head
    $xhtmlHead  = '<tr>';
    if($configs['list']['general']['showCheckbox']['value'] == 1) {
        $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    }
    if($configs['list']['general']['showIndex']['value'] == 1) {
        $xhtmlHead .= '<th class="col-50">STT</th>';
    }
    foreach ($configs['list']['fields'] AS $field) {
        $xhtmlHead .= $this->linkAdminSort($field['caption'], $field['name'], $this->params['ssFilter'], $field['attributes']);
    }
    if($this->userInfo['id'] == '1111111111111111111111') {
        $xhtmlHead .= '<th class="col-80">Công khai</th>';
        $xhtmlHead .= '<th class="col-80">Developer</th>';
        $xhtmlHead .= '<th>ID</th>';
    }
	if($configs['list']['general']['showControl']['value'] == 1) {
        $xhtmlHead .= '<th class="col-80">Công cụ</th>';
	}
	$xhtmlHead .= '</tr>';

    // Danh sách
    $xhtmlItems = '';
    if(!empty($this->items)) {
        $index = 0;
        foreach ($this->items AS $item) {
            $index++;
            $id             = $item->id;
            $name           = $item->name;
            $public         = $item->public;
            $developer      = $item->developer;
            $ordering       = @$this->xFormInput('ordering['. $id .']', $item->ordering, array('class' => 'form-control input-xs'));
            $cid            = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
            
            // Link Action
            $linkEdit       = $this->url('routeAdminDocument/default', array('slug' => $configs['code'], 'action' => 'form', 'id' => $id));
            $linkCopy       = $this->url('routeAdminDocument/default', array('slug' => $configs['code'], 'action' => 'form', 'id' => $id, 'code' => 'copy'));
            
            // Control Action
            $controlEdit    = $this->linkAdminHtml($linkEdit, array('type' => 'icon', 'title' => 'Sửa', 'class' => 'btn btn-xs yellow', 'icon' => 'fa fa-edit'));
            $controlCopy    = $this->linkAdminHtml($linkCopy, array('type' => 'icon', 'title' => 'Copy', 'class' => 'btn btn-xs default', 'icon' => 'fa fa-copy'));
            $controlStatus  = $this->linkAdminStatus($id, $item->status);
            $controls       = $controlStatus . $controlEdit . $controlCopy;
            if($item->developer == 1 && $this->userInfo['id'] != '1111111111111111111111') {
                $controls   = '';
            }
            
            $xhtmlColumn    = '';
            if($configs['list']['general']['showCheckbox']['value'] == 1) {
                $xhtmlColumn .= '<td>'. $cid .'</td>';
            }
            if($configs['list']['general']['showIndex']['value'] == 1) {
                $xhtmlColumn .= '<td>'. $index .'</td>';
            }
            foreach ($configs['list']['fields'] AS $field) {
                switch ($field['name']) {
                    case 'name':
                        $fieldColumn = '<a href="'. $linkEdit .'"><b>'. $item[$field['name']] .'</b></a>';
                        break;
                    case 'color':
                        $fieldColumn = '<div style="background: '. $item[$field['name']] .'; padding: 4px 5px 3px 5px;">'. $item[$field['name']] .'</div>';
                        break;
                    case 'date_begin':
                        $fieldColumn = $dateFormat->formatToView($item[$field['name']]);
                        break;
                    case 'date_end':
                        $fieldColumn = $dateFormat->formatToView($item[$field['name']]);
                        break;
                    case 'ordering':
                        $fieldColumn = @$this->xFormInput('ordering['. $id .']', $item[$field['name']], array('class' => 'form-control input-xs'));
                        break;
                    case 'price':
                        $fieldColumn = number_format($item[$field['name']]);
                        break;
                    default:
                        $fieldColumn = $item[$field['name']];
                        if(!empty($field['data_source'])) {
                            $fieldNameView = !empty($field['data_source']['view']['field']) ? $field['data_source']['view']['field'] : 'name';
                            $fieldColumn = $this->data_source[$field['data_source']['table'] . $field['name']][$item[$field['name']]][$fieldNameView];
                        }
                }
                
                $fieldClass = $field['options']['class'] ? ' class="' . $field['options']['class'] . '"' : '';
                $xhtmlColumn .= sprintf('<td%s>%s</td>', $fieldClass, $fieldColumn);
            }
            
            if($this->userInfo['id'] == '1111111111111111111111') {
                $xhtmlColumn .= '<td>'. $public .'</td>';
                $xhtmlColumn .= '<td>'. $developer .'</td>';
                $xhtmlColumn .= '<td>'. $id .'</td>';
            }
            if($configs['list']['general']['showControl']['value'] == 1) {
                $xhtmlColumn .= '<td>'. $controls .'</td>';
            }
            
            $xhtmlItems    .= '<tr id="tr_'. $id .'">'. $xhtmlColumn .'</tr>';
        }
    }
    
    // Control
    $arrControl = array(
        array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdminDocument/default', array('slug' => $this->params['route']['slug'], 'action' => 'form')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => '', 'class' => 'btn', ) ),
        array('name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link',
            'attributes' => array(
                'class' => 'btn dropdown-toggle',
                'data-toggle' => 'dropdown',
                'data-hover' => 'dropdown',
                ),
            'children' =>  array(
                        array( 'name' => 'sort', 'caption' => 'Sắp xếp', 'link' => 'javascript:;', 'icon' => 'fa-sort-alpha-asc',
                        'attributes' => array(
                                'onclick' => 'javascript:changeOrdering();',
                        )
                    ),
                array( 'name' => 'divider' ),
                array( 'name' => 'active', 'caption' => 'Hiển thị', 'link' => 'javascript:;', 'icon' => 'fa-check-square-o',
                    'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 0);', ) ),
                array( 'name' => 'inactive', 'caption' => 'Không hiển thị', 'link' => 'javascript:;', 'icon' => 'fa-circle-o',
                    'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 1);', ) ),
                array( 'name' => 'divider' ),
                array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash',
                    'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');', ) )
                ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>
<form action="<?php echo $this->url('routeAdminDocument/default', array('slug' => $this->params['route']['slug'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdminDocument/default', array('slug' => $configs['code'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
            ?>
    	</div>
	</div>
</form>
