<?php
    // Filter
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_status'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_company_branch'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th class="col-50">STT</th>';
    $xhtmlHead .= '<th>Tên đăng nhập</th>';
    $xhtmlHead .= $this->linkAdminSort('Họ tên', 'name', $this->params['ssFilter'], null);
    $xhtmlHead .= '<th>Email</th>';
    $xhtmlHead .= '<th>Điện thoại</th>';
    $xhtmlHead .= '<th>Cơ sở làm việc</th>';
    $xhtmlHead .= '<th>Phòng ban</th>';
    $xhtmlHead .= '<th>Chức vụ</th>';
    $xhtmlHead .= '<th>Danh sách lớp học đang dạy</th>';
    $xhtmlHead .= '<th class="col-80">Công cụ</th>';
	$xhtmlHead .= '</tr>';

    // Danh sách
    $xhtmlItems = '';
    if(!empty($this->items)) {
        $index = 0;
        foreach ($this->items AS $item) {
            $index++;
            $id                     = $item->id;
            $username               = $item->username;
            $code                   = $item->code;
            $email                  = $item->email;
            $name                   = $item->name;
            $phone                  = $item->phone;
            $login_time             = $item->login_time ? date_format(date_create($item->login_time), 'd/m/Y H:i:s') : '';
            $company_branch_id      = $item->company_branch_id ? $this->company_branch[$item->company_branch_id]['name'] : '';
            $company_department_id  = $item->company_department_id ? $this->company_department[$item->company_department_id]['name'] : '';
            $company_position_id    = $item->company_position_id ? $this->company_position[$item->company_position_id]['name'] : '';
            $edu_class              = !empty($this->edu_class[$item['id']]) ? implode('<br>', $this->edu_class[$item['id']]) : '';
            
            $permission_ids         = explode(',', $item->permission_ids);
            $permissions            = '';
            foreach ($permission_ids AS $permission) {
                $permissions    .= '<p>'. $this->permission[$permission]['name'] .'</p>';
            }
            
            $ordering               = @$this->xFormInput('ordering['. $id .']', $item->ordering, array('class' => 'form-control input-xs'));
            $cid                    = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
            
            // Link Action
            $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form', 'id' => $id));
            
            // Control Action
            $controlEdit    = $this->linkAdminHtml($linkEdit, array('type' => 'icon', 'title' => 'Sửa', 'class' => 'btn btn-xs yellow', 'icon' => 'fa fa-edit'));
            $controlStatus  = $this->linkAdminStatus($id, $item->status);
            $controls       = $controlStatus . $controlEdit;
            
            $xhtmlItems .= '<tr id="tr_'. $id .'">
    							<td>'. $cid .'</td>
							    <td>'. $index .'</td>
    							<td>'. $username .'</td>
    							<td><a href="'. $linkEdit .'"><b>'. $name .'</b></a></td>
    							<td>'. $email .'</td>
    							<td>'. $phone .'</td>
    							<td>'. $company_branch_id .'</td>
    							<td>'. $company_department_id .'</td>
    							<td>'. $company_position_id .'</td>
    							<td>'. $edu_class .'</td>
    							<td>'. $controls .'</td>
    						</tr>';
        }
    }
    
    // Control
    $arrControl = array(
        array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => '', 'class' => 'btn', ) ),
        array( 'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown', ), 
            'children' => array( 
                //array( 'name' => 'sort', 'caption' => 'Sắp xếp', 'link' => 'javascript:;', 'icon' => 'fa-sort-alpha-asc', 'attributes' => array( 'onclick' => 'javascript:changeOrdering();', ) ), 
                //array( 'name' => 'divider' ), 
                array( 'name' => 'active', 'caption' => 'Hiển thị', 'link' => 'javascript:;', 'icon' => 'fa-check-square-o', 'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 0);', ) ), 
                array( 'name' => 'inactive', 'caption' => 'Không hiển thị', 'link' => 'javascript:;', 'icon' => 'fa-circle-o', 'attributes' => array( 'onclick' => 'javascript:changeStatus(\'multi\', 1);', ) ), 
                array( 'name' => 'divider' ), 
                array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash', 'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');', ) ), 
                array( 'name' => 'divider' ), array( 'name' => 'export', 'caption' => 'Xuất bản excel', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'export')), 'icon' => 'fa-file-excel-o', 'attributes' => array() ), 
            ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>

<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
			<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
            ?>
    	</div>
	</div>
</form>
<?php $this->headScript()->captureStart() ?>
    $('#adminForm select').change(function() {
		$('#adminForm').submit();
    });
<?php $this->headScript()->captureEnd() ?>
