<?php
    // Filter
    $myForm				= $this->myForm;
    $model = $this->model;
    $myForm->prepare();
    $dateFormat = new \ZendX\Functions\Date();
    $numberFormat = new \ZendX\Functions\Number();

    $userInfo = new \ZendX\System\UserInfo();
    $curent_user = $userInfo->getUserInfo();
    $permission_ids = explode(',', $curent_user['permission_ids']);
    
    if(count($myForm->get('filter_sale_branch')->getValueOptions()) == 1) {
        $myForm->get('filter_sale_branch')->setEmptyOption('');
    }
    $elements = array(
        array('element' => $myForm->get('filter_keyword'), 'boxClass' => 'col-md-2 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('order')),
        array('element' => $myForm->get('order_by')),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);

    // Danh sách
    $xhtmlItems = '';
    
    if(!empty($this->items)) {
        $index = 0;
        $list_item  = $this->items;
        $total_price = 0;
        foreach ($list_item AS $item) {
            $index++;
            $id                     = $item['id'];
            $cid                    = $this->xFormInput('cid[]', $item['id'], array('type' => 'checkbox', 'class' => 'checkboxes'));
            $created                = $dateFormat->formatToView($item['created'], 'd/m/Y H:i:s');
            $branchs                = explode(',', $item['sale_branch_ids']);
            $list_branch = [];
            foreach($branchs as $branch){
                $list_branch[] = $this->branch[$branch]['name'];
            }
            $template               = $this->template[$item['template_id']];
            $cid                    = @$this->xFormInput('cid[]', $id, array('type' => 'checkbox', 'class' => 'checkboxes'));
            
            // Link Action
            $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form', 'id' => $id));
            $controlStatus  = $this->linkAdminStatus($id, $item->status);
            $controls       = $controlStatus;
            
            $xhtmlItems .= '<tr id="tr_'. $id .'" data-contact="'.$item['contact_id'].'">
    							<td>'. $cid .'</td>
                                <td>'. $index .'</td>
    							<td><a href="'. $linkEdit .'">'.  $item['name'] .'</a></td>
    							<td>'. $item['code'] .'</td>
    							<td>'. $template .'</td>
    							<td>'. $item['order_status'] .'</td>
    							<td>'. $item['note'] .'</td>
    							<td>'. implode(', ', $list_branch) .'</td>
    							<td>'. $controls .'</td>
    						</tr>';
        }
    }

    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th width="30" class="table-checkbox"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';;
    $xhtmlHead .= '<th width="30">STT</th>';
    $xhtmlHead .= '<th width="160">Mô tả</th>';
    $xhtmlHead .= '<th width="150">Mã</th>';
    $xhtmlHead .= '<th width="150">Mẫu template</th>';
    $xhtmlHead .= '<th width="150">Mã trạng thái đơn hàng</th>';
    $xhtmlHead .= '<th width="130">Tên trạng thái chung</th>';
    $xhtmlHead .= '<th width="150">Bật cho chi nhánh</th>';
    $xhtmlHead .= '<th width="15"></th>';
    $xhtmlHead .= '</tr>';
    
    // Control
    $arrControl = array(
        array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => 'javascript:void(0)', 'class' => 'btn', ) ),
        array(
            'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown', ),
            'children' => array(
                array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash', 'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');' ) ),
            ),
            'children-class' => 'dropdown-menu pull-right'
        ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
<!--    		<div class="table-scrollable table-fixed-head">-->
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
            ?>
    	</div>
	</div>
</form>
