<?php
    $userInfo = new \ZendX\System\UserInfo();
    

    $myForm = $this->myForm;
    $myForm->prepare();
    
    $arrControl = array(
        array('name' => 'save', 'caption' => 'Lưu', 'link' => 'javascript:;', 'icon' => 'fa-check', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save\');', 'class' => 'btn')),
        array('name' => 'save-new', 'caption' => 'Lưu &amp; Mới', 'link' => 'javascript:;', 'icon' => 'fa-paste', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-new\');', 'class' => 'btn')),
        array('name' => 'save-close', 'caption' => 'Lưu &amp; Đóng', 'link' => 'javascript:;', 'icon' => 'fa-save', 'attributes' => array('onclick' => 'javascript:controlSubmitForm(\'save-close\');', 'class' => 'btn')),
        array('name' => 'close', 'caption' => 'Hủy', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'onclick' => '', 'icon' => 'fa-times', 'attributes' => array('class' => 'btn')),
    );
    
    $elements = array(
        array('element' => $myForm->get('title'), 'label' => 'Tiêu đề', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('sale_branch_id'), 'label' => 'Cơ sở', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('number'), 'label' => 'Số lượng data', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('status'), 'label' => 'Tự động chia', 'validate' => array('require' => true), 'boxClass' => 'col-md-2'),
        array('element' => $myForm->get('options'), 'label' => 'Nhân viên', 'boxClass' => 'col-sm-2'),
        array('element' => $myForm->get('id'), 'validate' => array('require' => true)),
    );

    $xhtml = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
?>

<form method="post" action="" class="horizontal-form adminForm" role="form" name="adminForm" id="adminForm" class="">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-default.phtml', array( 'control' => $arrControl )); ?>
		</div>
		<div class="clearfix"></div>
	</div>
	
    <?php echo $this->flashMessenger()->render();?>
	<?php echo @$this->xViewElementErrors($elements);?>
	
    <div class="page-content">
    	<div class="row" id="info_data">
			<?php echo $xhtml;?>
		</div>
	</div>
</form>

<?php $this->headScript()->captureStart() ?>
    $("body").on("click", "input[name=tick_all]", function(){
        if($(this).attr('checked')){
            $(this).parents().parents().find('input[type="checkbox"]').attr('checked', true);
        }else{
            $(this).parents().parents().find('input[type="checkbox"]').attr('checked', false);
        }
    });

    function userBranch(){
        $.ajax({
            url: '<?php echo $this->url('routeAdmin/default', array('controller' => 'api', 'action' => 'user-branch'));?>',
            type: 'POST',
            beforeSend: function() {
                $('#load_user_branch').remove();
            },
            data: {
                sale_branch_id: $('select[name="sale_branch_id"]').val(),
                user_hidden: $('input[name="options"]').val(),
            },
            success: function(result) {
                $(result).insertBefore('input[name="options"]');
            }
        });
    }
    userBranch();
    $('select[name="sale_branch_id"]').on('change', function(){userBranch()});

<?php $this->headScript()->captureEnd() ?>