<?php
    // Filter
    $myForm				= $this->myForm;
    $myForm->prepare();
    
    $elements = array(
        array('element' => $myForm->get('filter_date_begin'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_date_end'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_submit'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
        array('element' => $myForm->get('filter_reset'), 'boxClass' => 'col-md-1 col-sm-4 col-xs-6'),
    );
    $xhtmlFilter = $this->partialLoop($this->params['module'] . '/partial/form-default.phtml', $elements);
    
    // Head
    $xhtmlHead  = '<tr>';
    $xhtmlHead .= '<th class="table-checkbox col-40"><input type="checkbox" class="group-checkable" data-set="#table-manager .checkboxes"/></th>';
    $xhtmlHead .= '<th class="col-50">STT</th>';
	$xhtmlHead .= '<th>Tên cấu hình</th>';
	$xhtmlHead .= '<th>Nhân sự</th>';
	$xhtmlHead .= '<th class="text-center">Tự động chia</th>';
	$xhtmlHead .= $this->linkAdminSort('Ngày tạo', 'created', $this->params['ssFilter'], null);
	$xhtmlHead .= '</tr>';

    // Danh sách
    $xhtmlItems = '';
    if(!empty($this->items)) {
        $index = 0;
        
        foreach ($this->items AS $item) {
            $index++;
            $cid            = $this->xFormInput('cid[]', $item->id, array('type' => 'checkbox', 'class' => 'checkboxes'));
            $id             = $item->id;
            $created        = date_format(date_create($item->created), 'd/m/Y');
            $title          = $item->title;
            $status         = $item->status > 0 ? '<span class="status on">Bật</span>' : '<span class="status off">Tắt</span>';
            $users          = $item->options ? explode(',', $item->options) : '';

            $user = '';
            foreach ($users as $item) {
                $user .= '<span class="u_item">'.$this->user[$item]."</span>";
            }
            $linkEdit       = $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form', 'id' => $id));
            
            $xhtmlItems .= '<tr id="tr_'. $id .'">
    							<td>'. $cid .'</td>
    							<td>'. $index .'</td>
    							<td><b><a href="'.$linkEdit.'" >'. $title .'</a></b></td>
    							<td>'. $user .'</td>
    							<td class="text-center">'. $status .'</td>
    							<td>'. $created .'</td>
    						</tr>';
        }
    }
    
    // Control
    $arrControl = array(
        array( 'name' => 'add', 'caption' => 'Thêm', 'link' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'form')), 'icon' => 'fa-plus', 'attributes' => array( 'onclick' => '', 'class' => 'btn', ) ),
        array( 'name' => 'tool', 'caption' => 'Công cụ', 'link' => 'javascript:;', 'icon' => 'fa-link', 'attributes' => array( 'class' => 'btn dropdown-toggle', 'data-toggle' => 'dropdown', 'data-hover' => 'dropdown' ), 
            'children' => array( 
                array( 'name' => 'delete', 'caption' => 'Xóa', 'link' => 'javascript:;', 'icon' => 'fa-trash', 'attributes' => array( 'onclick' => 'javascript:deleteItem(\'multi\', \'all\');' ) ),
                array( 'name' => 'divider' ),
            ), 'children-class' => 'dropdown-menu pull-right' ),
    );
?>
<form action="<?php echo $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'filter')); ?>" name="adminFormFilter" id="adminFormFilter" method="post">
    <div class="page-control">
    	<div class="title pull-left">
    		<?php echo $this->caption;?>
    	</div>
    	<div class="control pull-right">
			<?php echo $this->partial($this->params['module'] . '/partial/control-index.phtml', array( 'control' => $arrControl, 'params' => $this->params));?>
		</div>
		<div class="clearfix"></div>
	</div>
    <?php echo $this->flashMessenger()->render();?>
    <div class="page-filter">
    	<div class="row">
    		<?php echo $xhtmlFilter;?>
    	</div>
    </div>
    <div class="page-content">
    	<div class="table-manager" id="table-manager">
    		<div class="table-scrollable">
    			<table class="table table-striped table-bordered table-hover">
    				<thead>
    					<?php echo $xhtmlHead;?>
    				</thead>
    				<tbody>
    					<?php echo $xhtmlItems;?>
    				</tbody>
    			</table>
    		</div>
    		<?php
            	echo $this->paginationControl(\ZendX\Paginator\Paginator::createPaginator($this->count, $this->params['paginator']), 'sliding', $this->params['module'] . '/partial/paginator.phtml', array('currentURL' => $this->url('routeAdmin/default', array('controller' => $this->params['controller'], 'action' => 'index')), 'options' => $this->params['paginator']['options'])); 
            ?>
    	</div>
	</div>
</form>

<style>
    span.u_item {
        background: rgba(122,189,26,0.85);
        color: #fff;
        padding: 3px 5px;
        border: 1px solid #d8d8d8;
        margin-right: 5px;
        border-radius: 5px !important;
        display: inline-block;
        font-size: 11px;
        cursor: default;
    }
    span.u_item:hover {
        background: rgba(247,140,21,0.85);
        text-decoration: underline;
    }
</style>
